window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push({
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  total_tasks: 24,
  items: [
    {
      id: "math-oge-016-p001",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 1,
      prompt: "Решите задачу.",
      intro: "Радиус окружности, вписанной в равносторонний треугольник, равен 8√3.",
      image: "images/task-16/task-16-001.png",
      image_alt: "Вписанная окружность",
      question_text: "Найдите длину стороны треугольника.",
      answer: "48",
      solution: "r = a√3 / 6 ⇒ a = 6r / √3 = 48."
    },
    {
      id: "math-oge-016-p002",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 2,
      prompt: "Решите задачу.",
      intro: "Центр описанной окружности треугольника ABC лежит на стороне AB. ∠BAC = 30°.",
      image: "images/task-16/task-16-002.png",
      image_alt: "Описанная окружность",
      question_text: "Найдите угол ABC.",
      answer: "60",
      solution: "Треугольник прямоугольный ⇒ ∠ABC = 90 − 30 = 60°."
    },
    {
      id: "math-oge-016-p003",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 3,
      prompt: "Решите задачу.",
      intro: "Сторона равностороннего треугольника равна 8√3.",
      image: "images/task-16/task-16-003.png",
      image_alt: "Описанная окружность",
      question_text: "Найдите радиус описанной окружности.",
      answer: "8",
      solution: "R = a / √3 = 8."
    },
    {
      id: "math-oge-016-p004",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 4,
      prompt: "Решите задачу.",
      intro: "Четырёхугольник ABCD вписан в окружность. ∠ABC = 92°, ∠CAD = 60°.",
      image: "images/task-16/task-16-004.png",
      image_alt: "Вписанный четырехугольник",
      question_text: "Найдите угол ABD.",
      answer: "30",
      solution: "Используем свойства вписанных углов ⇒ ∠ABD = 30°."
    },
    {
      id: "math-oge-016-p005",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 5,
      prompt: "Решите задачу.",
      intro: "Сторона равностороннего треугольника равна 20√3.",
      image: "images/task-16/task-16-005.png",
      image_alt: "Вписанная окружность",
      question_text: "Найдите радиус вписанной окружности.",
      answer: "10√3",
      solution: "r = a√3 / 6 = 10√3."
    },
    {
      id: "math-oge-016-p006",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 6,
      prompt: "Решите задачу.",
      intro: "Трапеция ABCD вписана в окружность, ∠A = 59°.",
      image: "images/task-16/task-16-006.png",
      image_alt: "Вписанная трапеция",
      question_text: "Найдите угол B.",
      answer: "121",
      solution: "180 − 59 = 121°."
    },
    {
      id: "math-oge-016-p007",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 7,
      prompt: "Решите задачу.",
      intro: "Сторона равностороннего треугольника равна 18√3.",
      image: "images/task-16/task-16-007.png",
      image_alt: "Описанная окружность",
      question_text: "Найдите радиус описанной окружности.",
      answer: "18",
      solution: "R = 18."
    },
    {
      id: "math-oge-016-p008",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 8,
      prompt: "Решите задачу.",
      intro: "Сторона квадрата равна 8√2.",
      image: "images/task-16/task-16-008.png",
      image_alt: "Квадрат и окружность",
      question_text: "Найдите радиус описанной окружности.",
      answer: "8",
      solution: "Диагональ = 16 ⇒ R = 8."
    },
    {
      id: "math-oge-016-p009",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 9,
      prompt: "Решите задачу.",
      intro: "Центр описанной окружности лежит на стороне AB. ∠BAC = 44°.",
      image: "images/task-16/task-16-009.png",
      image_alt: "Описанная окружность",
      question_text: "Найдите угол ABC.",
      answer: "46",
      solution: "90 − 44 = 46°."
    },
    {
      id: "math-oge-016-p010",
      subject: "Математика",
      number: 16,
      title: "Планиметрия",
      block: "",
      task_group: 1,
      item_number: 10,
      prompt: "Решите задачу.",
      intro: "Сторона квадрата равна 32√2.",
      image: "images/task-16/task-16-010.png",
      image_alt: "Квадрат и окружность",
      question_text: "Найдите радиус описанной окружности.",
      answer: "32",
      solution: "Диагональ = 64 ⇒ R = 32."
},
{
  id: "math-oge-016-p011",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 11,
  prompt: "Решите задачу.",
  intro: "Четырёхугольник ABCD вписан в окружность. ∠ABD = 51°, ∠CAD = 42°.",
  image: "images/task-16/task-16-011.png",
  image_alt: "Вписанный четырехугольник",
  question_text: "Найдите угол ABC.",
  answer: "93",
  solution: "∠ABC = ∠ADC = ∠ABD + ∠CAD = 51° + 42° = 93°."
},
{
  id: "math-oge-016-p012",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 12,
  prompt: "Решите задачу.",
  intro: "В треугольнике ABC угол C равен 120°, AB = 18√3.",
  image: "images/task-16/task-16-012.png",
  image_alt: "Описанная окружность",
  question_text: "Найдите радиус описанной окружности.",
  answer: "18",
  solution: "AB = 2R sin C ⇒ 18√3 = 2R·√3/2 ⇒ R = 18."
},
{
  id: "math-oge-016-p013",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 13,
  prompt: "Решите задачу.",
  intro: "Радиус вписанной окружности в равнобедренную трапецию равен 34.",
  image: "images/task-16/task-16-013.png",
  image_alt: "Трапеция",
  question_text: "Найдите высоту трапеции.",
  answer: "68",
  solution: "h = 2r = 68."
},
{
  id: "math-oge-016-p014",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 14,
  prompt: "Решите задачу.",
  intro: "Трапеция ABCD вписана в окружность, ∠A = 77°.",
  image: "images/task-16/task-16-014.png",
  image_alt: "Трапеция",
  question_text: "Найдите угол C.",
  answer: "103",
  solution: "∠A + ∠C = 180 ⇒ 180 − 77 = 103°."
},
{
  id: "math-oge-016-p015",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 15,
  prompt: "Решите задачу.",
  intro: "Около окружности радиуса 7 описан квадрат.",
  image: "images/task-16/task-16-015.png",
  image_alt: "Квадрат",
  question_text: "Найдите площадь квадрата.",
  answer: "196",
  solution: "a = 2r = 14 ⇒ S = 196."
},
{
  id: "math-oge-016-p016",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 16,
  prompt: "Решите задачу.",
  intro: "Радиус вписанной окружности в прямоугольную трапецию равен 10.",
  image: "images/task-16/task-16-016.png",
  image_alt: "Трапеция",
  question_text: "Найдите высоту трапеции.",
  answer: "20",
  solution: "h = 2r = 20."
},
{
  id: "math-oge-016-p017",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 17,
  prompt: "Решите задачу.",
  intro: "Периметр треугольника равен 54, радиус вписанной окружности равен 1.",
  image: "images/task-16/task-16-017.png",
  image_alt: "Треугольник",
  question_text: "Найдите площадь треугольника.",
  answer: "27",
  solution: "S = r·p/2 = 1·27 = 27."
},
{
  id: "math-oge-016-p018",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 18,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 26.",
  image: "images/task-16/task-16-018.png",
  image_alt: "Квадрат",
  question_text: "Найдите радиус вписанной окружности.",
  answer: "13",
  solution: "r = a/2 = 13."
},
{
  id: "math-oge-016-p019",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 19,
  prompt: "Решите задачу.",
  intro: "Центр описанной окружности лежит на стороне AB. ∠BAC = 75°.",
  image: "images/task-16/task-16-019.png",
  image_alt: "Треугольник",
  question_text: "Найдите угол ABC.",
  answer: "15",
  solution: "∠ABC = 90 − 75 = 15°."
},
{
  id: "math-oge-016-p020",
  subject: "Математика",
  number: 16,
  title: "Планиметрия",
  block: "",
  task_group: 1,
  item_number: 20,
  prompt: "Решите задачу.",
  intro: "В окружности диаметры AC и BD. ∠AOD = 114°.",
  image: "images/task-16/task-16-020.png",
  image_alt: "Окружность",
  question_text: "Найдите угол ACB.",
  answer: "33",
  solution: "Вписанный угол равен половине центрального: 114/2 = 57°, далее геометрия даёт 33°."
},
{
      "id": "math-oge-016-extra-p042",
      "subject": "Математика",
      "number": 16,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 42,
      "prompt": "Впишите правильный ответ.",
      "question": "Четырёхугольник 𝐴⁢𝐵⁢𝐶⁢𝐷 вписан в окружность. Угол 𝐴⁢𝐵⁢𝐶 равен 92°, угол 𝐶⁢𝐴⁢𝐷 равен 60°. Найдите угол 𝐴⁢𝐵⁢𝐷. Ответ дайте в градусах.",
      "answer": "",
      "solution": "",
      "source_guid": "049FC206D0C8806D46815DACEAFFDF11",
      "source_number": "BE804A",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.4 Окружность и круг",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/049FC206D0C8806D46815DACEAFFDF11/xs3qstsrc049FC206D0C8806D46815DACEAFFDF11_1_1456237436.png",
      "image_alt": "Иллюстрация к заданию 42",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"850\" valign=\"top\"> <p class=\"MsoNormal\">Четырёхугольник <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(7 0 4 1 5 2 6 3)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"7\" data-semantic-children=\"0,1,2,3\" data-semantic-content=\"4,5,6\" data-semantic-owns=\"0 4 1 5 2 6 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;вписан в окружность. Угол <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(5 0 3 1 4 2)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"5\" data-semantic-children=\"0,1,2\" data-semantic-content=\"3,4\" data-semantic-owns=\"0 3 1 4 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;равен <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"endpunct\" data-semantic-annotation=\"clearspeak:simple;depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-content=\"1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c39\" noic=\"true\" style=\"padding-top: 0.666em;\">9</mjx-c><mjx-c class=\"mjx-c32\" style=\"padding-top: 0.666em;\">2</mjx-c></mjx-mn><mjx-mi data-semantic-type=\"punctuation\" data-semantic-role=\"degree\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-operator=\"punctuated\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cB0 NCM-I\">°</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, угол <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(5 0 3 1 4 2)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"5\" data-semantic-children=\"0,1,2\" data-semantic-content=\"3,4\" data-semantic-owns=\"0 3 1 4 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;равен <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"endpunct\" data-semantic-annotation=\"clearspeak:simple;depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-content=\"1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c36\" noic=\"true\" style=\"padding-top: 0.666em;\">6</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.666em;\">0</mjx-c></mjx-mn><mjx-mi data-semantic-type=\"punctuation\" data-semantic-role=\"degree\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-operator=\"punctuated\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cB0 NCM-I\">°</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите угол <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(5 0 3 1 4 2)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"5\" data-semantic-children=\"0,1,2\" data-semantic-content=\"3,4\" data-semantic-owns=\"0 3 1 4 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Ответ дайте в градусах.</p> </td> <td width=\"419\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/049FC206D0C8806D46815DACEAFFDF11/xs3qstsrc049FC206D0C8806D46815DACEAFFDF11_1_1456237436.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/049FC206D0C8806D46815DACEAFFDF11/xs3qstsrc049FC206D0C8806D46815DACEAFFDF11_1_1456237436.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-016-extra-p052",
      "subject": "Математика",
      "number": 16,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 52,
      "prompt": "Впишите правильный ответ.",
      "question": "Сторона равностороннего треугольника равна 20⁢√3. Найдите радиус окружности, вписанной в этот треугольник.",
      "answer": "",
      "solution": "",
      "source_guid": "061D8C44C441933342D6B188C4F4F679",
      "source_number": "256E4F",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.2 Треугольник\n7.4 Окружность и круг\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/061D8C44C441933342D6B188C4F4F679/xs3qstsrc061D8C44C441933342D6B188C4F4F679_1_1485520920.png",
      "image_alt": "Иллюстрация к заданию 52",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/061D8C44C441933342D6B188C4F4F679/xs3qstsrc061D8C44C441933342D6B188C4F4F679_1_1485520920.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/061D8C44C441933342D6B188C4F4F679/xs3qstsrc061D8C44C441933342D6B188C4F4F679_1_1485520920.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Сторона равностороннего треугольника равна <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(4 0 3 (2 1))\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"4\" data-semantic-children=\"0,2\" data-semantic-content=\"3\" data-semantic-owns=\"0 3 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"4\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\" noic=\"true\" style=\"padding-top: 0.666em;\">2</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.666em;\">0</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msqrt data-semantic-type=\"sqrt\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-children=\"1\" data-semantic-parent=\"4\" data-semantic-owns=\"1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-sqrt><mjx-surd><mjx-mo><mjx-c class=\"mjx-c221A\">√</mjx-c></mjx-mo></mjx-surd><mjx-box style=\"padding-top: 0.211em;\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c33\">3</mjx-c></mjx-mn></mjx-box></mjx-sqrt></mjx-msqrt></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите радиус окружности, вписанной в этот треугольник.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-016-extra-p094",
      "subject": "Математика",
      "number": 16,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 94,
      "prompt": "Впишите правильный ответ.",
      "question": "Сторона равностороннего треугольника равна 18⁢√3. Найдите радиус окружности, описанной около этого треугольника.",
      "answer": "",
      "solution": "",
      "source_guid": "0A9AE9586A6F863B43AE3968EE31FAEA",
      "source_number": "C3CA4A",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.2 Треугольник\n7.4 Окружность и круг\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0A9AE9586A6F863B43AE3968EE31FAEA/xs3qstsrc0A9AE9586A6F863B43AE3968EE31FAEA_1_1485520288.png",
      "image_alt": "Иллюстрация к заданию 94",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0A9AE9586A6F863B43AE3968EE31FAEA/xs3qstsrc0A9AE9586A6F863B43AE3968EE31FAEA_1_1485520288.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0A9AE9586A6F863B43AE3968EE31FAEA/xs3qstsrc0A9AE9586A6F863B43AE3968EE31FAEA_1_1485520288.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Сторона равностороннего треугольника равна <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(4 0 3 (2 1))\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"4\" data-semantic-children=\"0,2\" data-semantic-content=\"3\" data-semantic-owns=\"0 3 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"4\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.666em;\">1</mjx-c><mjx-c class=\"mjx-c38\" style=\"padding-top: 0.666em;\">8</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msqrt data-semantic-type=\"sqrt\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-children=\"1\" data-semantic-parent=\"4\" data-semantic-owns=\"1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-sqrt><mjx-surd><mjx-mo><mjx-c class=\"mjx-c221A\">√</mjx-c></mjx-mo></mjx-surd><mjx-box style=\"padding-top: 0.211em;\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c33\">3</mjx-c></mjx-mn></mjx-box></mjx-sqrt></mjx-msqrt></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите радиус окружности, описанной около этого треугольника.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-016-extra-p115",
      "subject": "Математика",
      "number": 16,
      "title": "Планиметрия",
      "block": "",
      "page": 2,
      "item_number": 115,
      "prompt": "Впишите правильный ответ.",
      "question": "Радиус окружности, вписанной в прямоугольную трапецию, равен 10. Найдите высоту этой трапеции.",
      "answer": "",
      "solution": "",
      "source_guid": "15AC9B0A52DCBF8B49F4986165C1E544",
      "source_number": "1AE9FC",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.4 Окружность и круг\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/15AC9B0A52DCBF8B49F4986165C1E544/xs3qstsrc15AC9B0A52DCBF8B49F4986165C1E544_1_1487085466.png",
      "image_alt": "Иллюстрация к заданию 115",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/15AC9B0A52DCBF8B49F4986165C1E544/xs3qstsrc15AC9B0A52DCBF8B49F4986165C1E544_1_1487085466.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/15AC9B0A52DCBF8B49F4986165C1E544/xs3qstsrc15AC9B0A52DCBF8B49F4986165C1E544_1_1487085466.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Радиус окружности, вписанной в прямоугольную трапецию, равен 10. Найдите высоту этой трапеции.</p> <p class=\"MsoNormal\">&nbsp;</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
  ]
});
