window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push(
{
  "subject": "Математика",
  "number": 12,
  "title": "Расчёты по формулам",
  "total_tasks": 32,
  "items": [
    {
      "id": "math-oge-012-p001",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 1,
      "prompt": "Вычислите по формуле.",
      "question_raw": "В фирме «Родник» стоимость C (в рублях) колодца из железобетонных колец рассчитывается по формуле C = 6000 + 4100n, где n — число колец, установленных при рытье колодца. Пользуясь этой формулой, рассчитайте стоимость колодца из 7 колец."
    },
    {
      "id": "math-oge-012-p002",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 2,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Чтобы перевести значение температуры по шкале Цельсия в шкалу Фаренгейта, пользуются формулой t_F = 1.8t_C + 32, где t_C — градусы Цельсия, t_F — градусы Фаренгейта. Скольким градусам по шкале Фаренгейта соответствует -45 градусов по шкале Цельсия?"
    },
    {
      "id": "math-oge-012-p003",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 3,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Чтобы перевести значение температуры по шкале Фаренгейта в шкалу Цельсия, пользуются формулой t_C = 5(t_F - 32)/9, где t_C — температура в градусах Цельсия, t_F — температура в градусах Фаренгейта. Скольким градусам по шкале Цельсия соответствует 113 градусов по шкале Фаренгейта?"
    },
    {
      "id": "math-oge-012-p004",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 4,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Сила Архимеда, выталкивающая на поверхность погружённое в воду тело, вычисляется по формуле F = ρgV, где ρ = 1000 кг/м^3 — плотность воды, g = 9.8 м/с^2 — ускорение свободного падения, а V — объём тела в кубических метрах. Сила F измеряется в ньютонах. Найдите силу Архимеда, действующую на погружённое в воду тело объёмом 0.6 куб. м. Ответ дайте в ньютонах."
    },
    {
      "id": "math-oge-012-p005",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 5,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Если тело массой m кг подвешено на высоте h м над горизонтальной поверхностью земли, то его потенциальная энергия в джоулях вычисляется по формуле P = gmh, где g = 9.8 м/с^2 — ускорение свободного падения. Найдите массу тела, подвешенного на высоте 4 м над поверхностью земли, если его потенциальная энергия равна 1176 джоулям. Ответ дайте в килограммах."
    },
    {
      "id": "math-oge-012-p006",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 1,
      "item_number": 6,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Энергия заряженного конденсатора W (в джоулях) вычисляется по формуле W = CU^2/2, где C — ёмкость конденсатора (в фарадах), а U — разность потенциалов на обкладках конденсатора (в вольтах). Найдите энергию конденсатора ёмкостью 10^-4 фарад, если разность потенциалов на обкладках конденсатора равна 22 вольт. Ответ дайте в джоулях."
    },
    {
      "id": "math-oge-012-p007",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 2,
      "item_number": 7,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Кинетическая энергия тела массой m кг, двигающегося со скоростью v м/с, вычисляется по формуле E = mv^2/2 и измеряется в джоулях. Известно, что автомобиль массой 2500 кг обладает кинетической энергией 45000 джоулей. Найдите скорость этого автомобиля в метрах в секунду."
    },
    {
      "id": "math-oge-012-p008",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 2,
      "item_number": 8,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Мощность постоянного тока P (в ваттах) вычисляется по формуле P = I^2R, где I — сила тока (в амперах), R — сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление R, если мощность составляет 101.25 Вт, а сила тока равна 4.5 А. Ответ дайте в омах."
    },
    {
      "id": "math-oge-012-p009",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 2,
      "item_number": 9,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Центростремительное ускорение при движении по окружности a (в м/с^2) можно вычислить по формуле a = ω^2R, где ω — угловая скорость (в с^-1), а R — радиус окружности. Пользуясь этой формулой, найдите радиус R (в метрах), если угловая скорость равна 7.5 с^-1, а центростремительное ускорение равно 337.5 м/с^2."
    },
    {
      "id": "math-oge-012-p010",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "",
      "page": 2,
      "item_number": 10,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Площадь четырёхугольника можно вычислить по формуле S = d_1 d_2 sin(α) / 2, где d_1 и d_2 — длины диагоналей четырёхугольника, α — угол между диагоналями. Пользуясь этой формулой, найдите длину диагонали d_2, если d_1 = 12, sin(α) = 7/9, а S = 46.2."
    },
    {
      "id": "math-oge-012-p011",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "item_number": 1,
      "prompt": "Вычислите по формуле.",
      "question_raw": "В фирме «Эх, прокачу!» стоимость поездки на такси C (в рублях) рассчитывается по формуле C = 150 + 12(t - 5), где t — длительность поездки, выраженная в минутах, t > 5. Пользуясь этой формулой, рассчитайте стоимость 11-минутной поездки."
    },
    {
      "id": "math-oge-012-p012",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "item_number": 2,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Зная длину своего шага, человек может приближённо подсчитать пройденное им расстояние s по формуле s = nl, где n — число шагов, l — длина шага. Какое расстояние прошёл человек, если l = 60 см, n = 1300? Ответ выразите в километрах."
    },
    {
      "id": "math-oge-012-p013",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "item_number": 3,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Период колебания математического маятника T (в секундах) приближённо можно вычислить по формуле T = 2sqrt(l), где l — длина нити (в метрах). Пользуясь этой формулой, найдите длину нити маятника (в метрах), период колебаний которого составляет 11 секунд."
    },
    {
      "id": "math-oge-012-p014",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "item_number": 4,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон Кулона можно записать в виде F = kq_1q_2 / r^2, где F — сила взаимодействия зарядов (в ньютонах), q_1 и q_2 — величины зарядов (в кулонах), k — коэффициент пропорциональности (в Н·м^2/Кл^2), а r — расстояние между зарядами (в метрах). Пользуясь формулой, найдите величину заряда q_2, если k = 9·10^9 Н·м^2/Кл^2, q_1 = 0.008 Кл, r = 400 м, а F = 0.225 Н."
    },
    {
      "id": "math-oge-012-p015",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "item_number": 5,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон всемирного тяготения можно записать в виде F = γm_1m_2 / r^2, где F — сила притяжения между телами (в ньютонах), m_1 и m_2 — массы тел (в килограммах), r — расстояние между центрами масс (в метрах), а γ — гравитационная постоянная, равная 6.67·10^-11 Н·м^2/кг^2. Пользуясь формулой, найдите массу тела m_1 (в килограммах), если F = 0.64032 Н, m_2 = 4·10^9 кг, а r = 5 м."
    },
    {
      "id": "math-oge-012-p016",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "item_number": 6,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон Менделеева-Клапейрона можно записать в виде PV = νRT, где P — давление (в паскалях), V — объём (в м^3), ν — количество вещества (в молях), T — температура (в градусах Кельвина), а R — универсальная газовая постоянная, равная 8.31 Дж/(К·моль). Пользуясь этой формулой, найдите объём V (в м^3), если T = 300 К, P = 53848.8 Па, ν = 32.4 моль."
    },
    {
      "id": "math-oge-012-p017",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "item_number": 7,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон Менделеева-Клапейрона можно записать в виде PV = νRT, где P — давление (в паскалях), V — объём (в м^3), ν — количество вещества (в молях), T — температура (в градусах Кельвина), а R — универсальная газовая постоянная, равная 8.31 Дж/(К·моль). Пользуясь этой формулой, найдите температуру T (в градусах Кельвина), если P = 70219.5 Па, ν = 29.9 моль, V = 2.3 м^3."
    },
    {
      "id": "math-oge-012-p018",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 1,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Высота деревянного стеллажа для книг равна h = (a + b)n + a миллиметров, где a — толщина одной доски (в мм), b — высота одной полки (в мм), n — число таких полок. Найдите высоту книжного стеллажа из 8 полок, если a = 18 мм, b = 310 мм. Ответ выразите в миллиметрах."
    },
    {
      "id": "math-oge-012-p019",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 2,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон Гука можно записать в виде F = kx, где F — сила (в ньютонах), с которой сжимают пружину, x — абсолютное удлинение (сжатие) пружины (в метрах), а k — коэффициент упругости. Пользуясь этой формулой, найдите x (в метрах), если F = 80 Н и k = 5 Н/м."
    },
    {
      "id": "math-oge-012-p020",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 3,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Закон Джоуля-Ленца можно записать в виде Q = I^2Rt, где Q — количество теплоты (в джоулях), I — сила тока (в амперах), R — сопротивление цепи (в омах), а t — время (в секундах). Пользуясь этой формулой, найдите время t (в секундах), если Q = 816.75 Дж, I = 5.5 А, R = 9 Ом."
    },
    {
      "id": "math-oge-012-p021",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 4,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Мощность постоянного тока P (в ваттах) вычисляется по формуле P = U^2 / R, где U — напряжение (в вольтах), R — сопротивление (в омах). Пользуясь этой формулой, найдите P (в ваттах), если R = 9 Ом, U = 18 В."
    },
    {
      "id": "math-oge-012-p022",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 5,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Работа постоянного тока A (в джоулях) вычисляется по формуле A = U^2t / R, где U — напряжение (в вольтах), R — сопротивление (в омах), t — время (в секундах). Пользуясь этой формулой, найдите A (в джоулях), если t = 8 с, U = 6 В, R = 2 Ом."
    },
    {
      "id": "math-oge-012-p023",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 4,
      "item_number": 6,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Кинетическая энергия тела E (в джоулях) вычисляется по формуле E = mv^2 / 2, где m — масса тела (в килограммах), а v — его скорость (в метрах в секунду). Пользуясь этой формулой, найдите E (в джоулях), если v = 5 м/с и m = 12 кг."
    },
    {
      "id": "math-oge-012-p024",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 7,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Площадь треугольника можно вычислить по формуле S = abc / (4R), где a, b и c — стороны треугольника, а R — радиус окружности, описанной около этого треугольника. Пользуясь этой формулой, найдите S, если a = 11, b = 13, c = 20 и R = 65/6."
    },
    {
      "id": "math-oge-012-p025",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 8,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Радиус вписанной в прямоугольный треугольник окружности можно найти по формуле r = (a + b - c) / 2, где a и b — катеты, а c — гипотенуза треугольника. Пользуясь этой формулой, найдите c, если a = 12, b = 35 и r = 5."
    },
    {
      "id": "math-oge-012-p026",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 9,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Теорему косинусов можно записать в виде cos(α) = (a^2 + b^2 - c^2) / (2ab), где a, b и c — стороны треугольника, а α — угол между сторонами a и b. Пользуясь этой формулой, найдите величину cos(α), если a = 3, b = 8, c = 7."
    },
    {
      "id": "math-oge-012-p027",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 10,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Длина медианы m_c, проведённой к стороне c треугольника со сторонами a, b и c, вычисляется по формуле m_c = sqrt(2a^2 + 2b^2 - c^2) / 2. Найдите медиану m_c, если a = 4, b = 7, c = 9."
    },
    {
      "id": "math-oge-012-p028",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 11,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Длина биссектрисы l_c, проведённой к стороне c треугольника со сторонами a, b и c, вычисляется по формуле l_c = sqrt(ab((a + b)^2 - c^2)) / (a + b). Найдите длину биссектрисы l_c, если a = 7, b = 21, c = 26."
    },
    {
      "id": "math-oge-012-p029",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 12,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Площадь треугольника вычисляется по формуле S = bc sin(α) / 2, где b и c — две стороны треугольника, а α — угол между ними. Пользуясь этой формулой, найдите sin(α), если b = 10, c = 5 и S = 20."
    },
    {
      "id": "math-oge-012-p030",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "item_number": 13,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Радиус описанной около треугольника окружности можно найти по формуле R = a / (2sin(α)), где a — сторона треугольника, α — противолежащий этой стороне угол, а R — радиус описанной около этого треугольника окружности. Пользуясь этой формулой, найдите R, если a = 7, а sin(α) = 5/14."
    },
    {
      "id": "math-oge-012-p031",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "item_number": 14,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Теорему синусов можно записать в виде a / sin(α) = b / sin(β), где a и b — две стороны треугольника, а α и β — углы треугольника, лежащие против них соответственно. Пользуясь этой формулой, найдите величину a, если b = 15, sin(α) = 4/13 и sin(β) = 5/13."
    },
    {
      "id": "math-oge-012-p032",
      "subject": "Математика",
      "number": 12,
      "title": "Расчёты по формулам",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "item_number": 15,
      "prompt": "Вычислите по формуле.",
      "question_raw": "Площадь прямоугольника можно вычислить по формуле S = d^2 sin(α) / 2, где d — длина диагонали, α — угол между диагоналями. Пользуясь этой формулой, найдите площадь S, если d = 12 и sin(α) = 5/6."
    },
    {
      "id": "math-oge-007-p013",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 13,
      "prompt": "Впишите правильный ответ.",
      "question": "Перевести значение температуры по шкале Фаренгейта в шкалу Цельсия позволяет формула 𝑡𝐶 =\n5\n9\n⁢(𝑡𝐹−32), где 𝑡𝐶 — температура в градусах Цельсия, 𝑡𝐹 — температура в градусах Фаренгейта. Скольким градусам\nпо шкале Цельсия соответствует 59 градусов по шкале Фаренгейта?",
      "answer": "",
      "solution": "",
      "source_guid": "0166013C6122A7E44593FA69C8A061B0",
      "source_number": "F42F42",
      "source_answer_type": "Краткий ответ",
      "source_kes": "2.1 Буквенные выражения (выражения с переменными)",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Перевести значение температуры по шкале Фаренгейта в шкалу Цельсия позволяет формула <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(18 (2 0 1) 3 (17 (6 4 5) 16 (15 7 (13 (10 8 9) 11 12) 14)))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"18\" data-semantic-children=\"2,17\" data-semantic-content=\"3\" data-semantic-owns=\"2 3 17\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-parent=\"18\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-script></mjx-msub><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"18\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:2\" data-semantic-id=\"17\" data-semantic-children=\"6,15\" data-semantic-content=\"16\" data-semantic-parent=\"18\" data-semantic-owns=\"6 16 15\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mfrac data-semantic-type=\"fraction\" data-semantic-role=\"vulgar\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"6\" data-semantic-children=\"4,5\" data-semantic-parent=\"17\" data-semantic-owns=\"4 5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-frac type=\"d\"><mjx-num><mjx-nstrut type=\"d\"></mjx-nstrut><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:4\" data-semantic-id=\"4\" data-semantic-parent=\"6\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c35\">5</mjx-c></mjx-mn></mjx-num><mjx-dbox><mjx-dtable><mjx-line type=\"d\"></mjx-line><mjx-row><mjx-den><mjx-dstrut type=\"d\"></mjx-dstrut><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"5\" data-semantic-parent=\"6\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c39\">9</mjx-c></mjx-mn></mjx-den></mjx-row></mjx-dtable></mjx-dbox></mjx-frac></mjx-mfrac><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"16\" data-semantic-parent=\"17\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mrow data-semantic-type=\"fenced\" data-semantic-role=\"leftright\" data-semantic-annotation=\"fences:paren;depth:3\" data-semantic-id=\"15\" data-semantic-children=\"13\" data-semantic-content=\"7,14\" data-semantic-parent=\"17\" data-semantic-owns=\"7 13 14\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"open\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"7\" data-semantic-parent=\"15\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c28\">(</mjx-c></mjx-mo><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"13\" data-semantic-children=\"10,12\" data-semantic-content=\"11\" data-semantic-parent=\"15\" data-semantic-owns=\"10 11 12\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"10\" data-semantic-children=\"8,9\" data-semantic-parent=\"13\" data-semantic-owns=\"8 9\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:6\" data-semantic-id=\"8\" data-semantic-parent=\"10\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"simple function\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:6\" data-semantic-id=\"9\" data-semantic-parent=\"10\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D439\">𝐹</mjx-c></mjx-mi></mjx-script></mjx-msub><mjx-mo space=\"3\" data-semantic-type=\"operator\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"11\" data-semantic-parent=\"13\" data-semantic-operator=\"infixop,−\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2212\">−</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"12\" data-semantic-parent=\"13\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c33\" noic=\"true\" style=\"padding-top: 0.666em;\">3</mjx-c><mjx-c class=\"mjx-c32\" style=\"padding-top: 0.666em;\">2</mjx-c></mjx-mn></mjx-mrow><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"close\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"14\" data-semantic-parent=\"15\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c29\">)</mjx-c></mjx-mo></mjx-mrow></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;температура в градусах Цельсия, <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"simple function\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D439\">𝐹</mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;температура в градусах Фаренгейта. Скольким градусам <br> по шкале Цельсия соответствует 59 градусов по шкале Фаренгейта?<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p022",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 22,
      "prompt": "Впишите правильный ответ.",
      "question": "В фирме «Родник» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле 𝐶 =6000 +4100⁢𝑛, где 𝑛 — число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из 20 колец. Ответ дайте в рублях.",
      "answer": "",
      "solution": "",
      "source_guid": "02009753B03AA9804EC79379195166B9",
      "source_number": "0A4D44",
      "source_answer_type": "Краткий ответ",
      "source_kes": "1.5 Приближённые вычисления, правила округления, прикидка и оценка результата вычислений",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В фирме «Родник» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(9 0 1 (8 2 3 (7 4 6 5)))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"9\" data-semantic-children=\"0,8\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 8\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"9\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"9\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"8\" data-semantic-children=\"2,7\" data-semantic-content=\"3\" data-semantic-parent=\"9\" data-semantic-owns=\"2 3 7\" data-semantic-level-number=\"1\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"2\" data-semantic-parent=\"8\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c36\" noic=\"true\" style=\"padding-top: 0.666em;\">6</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.666em;\">0</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.666em;\">0</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.666em;\">0</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"3\" data-semantic-parent=\"8\" data-semantic-operator=\"infixop,+\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2B\">+</mjx-c></mjx-mo><mjx-mrow space=\"3\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:3\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c34\" noic=\"true\" style=\"padding-top: 0.677em;\">4</mjx-c><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.677em;\">1</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.677em;\">0</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.677em;\">0</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D45B\">𝑛</mjx-c></mjx-mi></mjx-mrow></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D45B\">𝑛</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из 20 колец. Ответ дайте в рублях.<span></span></p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p028",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 28,
      "prompt": "Впишите правильный ответ.",
      "question": "В фирме «Чистая вода» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле 𝐶 =6500 +4000⁢𝑛, где 𝑛 — число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из 11 колец. Ответ дайте в рублях.",
      "answer": "",
      "solution": "",
      "source_guid": "02F5026F38D4B51C4CFFD8887FD9D1C8",
      "source_number": "041048",
      "source_answer_type": "Краткий ответ",
      "source_kes": "1.5 Приближённые вычисления, правила округления, прикидка и оценка результата вычислений",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В фирме «Чистая вода» стоимость (в рублях) колодца из железобетонных колец рассчитывается по формуле <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(9 0 1 (8 2 3 (7 4 6 5)))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"9\" data-semantic-children=\"0,8\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 8\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"9\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"9\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"8\" data-semantic-children=\"2,7\" data-semantic-content=\"3\" data-semantic-parent=\"9\" data-semantic-owns=\"2 3 7\" data-semantic-level-number=\"1\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"2\" data-semantic-parent=\"8\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c36\" noic=\"true\" style=\"padding-top: 0.666em;\">6</mjx-c><mjx-c class=\"mjx-c35\" noic=\"true\" style=\"padding-top: 0.666em;\">5</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.666em;\">0</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.666em;\">0</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"3\" data-semantic-parent=\"8\" data-semantic-operator=\"infixop,+\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2B\">+</mjx-c></mjx-mo><mjx-mrow space=\"3\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:3\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c34\" noic=\"true\" style=\"padding-top: 0.677em;\">4</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.677em;\">0</mjx-c><mjx-c class=\"mjx-c30\" noic=\"true\" style=\"padding-top: 0.677em;\">0</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.677em;\">0</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D45B\">𝑛</mjx-c></mjx-mi></mjx-mrow></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D45B\">𝑛</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;число колец, установленных в колодце. Пользуясь этой формулой, рассчитайте стоимость колодца из 11 колец. Ответ дайте в рублях.<span></span></p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p056",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 56,
      "prompt": "Впишите правильный ответ.",
      "question": "Мощность постоянного тока (в ваттах) вычисляется по формуле 𝑃 =𝐼2⁢𝑅,\nгде 𝐼 — сила тока (в амперах), 𝑅 — сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление 𝑅, если мощность составляет 283,5 Вт,\nа сила тока равна 4,5 А. Ответ дайте в омах.",
      "answer": "",
      "solution": "",
      "source_guid": "06841F718F48AD7C47826A9C725BBABF",
      "source_number": "2FB845",
      "source_answer_type": "Краткий ответ",
      "source_kes": "2.2 Степень с целым показателем. Степень с рациональным показателем. Свойства степени",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Мощность постоянного тока (в ваттах) вычисляется по формуле <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(8 0 1 (7 (4 2 3) 6 5))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"8\" data-semantic-children=\"0,7\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 7\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"8\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D443\">𝑃</mjx-c></mjx-mi><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"8\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:2\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-children=\"2,3\" data-semantic-parent=\"7\" data-semantic-owns=\"2 3\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:4\" data-semantic-id=\"2\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D43C\">𝐼</mjx-c></mjx-mi><mjx-script style=\"vertical-align: 0.413em; margin-left: 0.053em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <br> где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D43C\">𝐼</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;сила тока (в амперах), <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, если мощность составляет 283,5&nbsp;Вт, <br> а сила тока равна 4,5&nbsp;А. Ответ дайте в омах.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p075",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 75,
      "prompt": "Впишите правильный ответ.",
      "question": "Чтобы перевести значение температуры по шкале Цельсия в шкалу Фаренгейта, пользуются формулой 𝑡𝐹=1,8⁢𝑡𝐶+32, где 𝑡𝐶 — температура\nв градусах Цельсия, 𝑡𝐹 — температура в градусах Фаренгейта. Скольким градусам по шкале Фаренгейта соответствует −45 градусов по шкале Цельсия?",
      "answer": "",
      "solution": "",
      "source_guid": "08C25A92FAF5AC3E4C8322FFB2272D20",
      "source_number": "510C4E",
      "source_answer_type": "Краткий ответ",
      "source_kes": "2.1 Буквенные выражения (выражения с переменными)",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Чтобы перевести значение температуры по шкале Цельсия в шкалу Фаренгейта, пользуются формулой <span class=\"mml\"><mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(13 (2 0 1) 3 (12 (11 4 10 (7 5 6)) 8 9))\" class=\"NCM-N\"><mjx-mstyle><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"13\" data-semantic-children=\"2,12\" data-semantic-content=\"3\" data-semantic-owns=\"2 3 12\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-parent=\"13\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"simple function\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D439\">𝐹</mjx-c></mjx-mi></mjx-script></mjx-msub><mjx-mo space=\"4\" data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"13\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"12\" data-semantic-children=\"11,9\" data-semantic-content=\"8\" data-semantic-parent=\"13\" data-semantic-owns=\"11 8 9\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:3\" data-semantic-id=\"11\" data-semantic-children=\"4,7\" data-semantic-content=\"10\" data-semantic-parent=\"12\" data-semantic-owns=\"4 10 7\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:4\" data-semantic-id=\"4\" data-semantic-parent=\"11\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.666em;\">1</mjx-c><mjx-c class=\"mjx-c2C\" noic=\"true\" style=\"padding-top: 0.666em;\">,</mjx-c><mjx-c class=\"mjx-c38\" style=\"padding-top: 0.666em;\">8</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"10\" data-semantic-parent=\"11\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"7\" data-semantic-children=\"5,6\" data-semantic-parent=\"11\" data-semantic-owns=\"5 6\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow><mjx-mo space=\"3\" data-semantic-type=\"operator\" data-semantic-role=\"addition\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"8\" data-semantic-parent=\"12\" data-semantic-operator=\"infixop,+\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2B\">+</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"9\" data-semantic-parent=\"12\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c33\" noic=\"true\" style=\"padding-top: 0.666em;\">3</mjx-c><mjx-c class=\"mjx-c32\" style=\"padding-top: 0.666em;\">2</mjx-c></mjx-mn></mjx-mrow></mjx-mrow></mjx-mstyle></mjx-math></mjx-container></span>, где <span class=\"mml\"><mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-mrow><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow></mjx-mstyle></mjx-math></mjx-container></span>&nbsp;— температура <br> в градусах Цельсия, <span class=\"mml\"><mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-mrow><mjx-msub data-semantic-type=\"subscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D461\">𝑡</mjx-c></mjx-mi><mjx-script style=\"vertical-align: -0.15em;\"><mjx-mi size=\"s\" data-semantic-type=\"identifier\" data-semantic-role=\"simple function\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D439\">𝐹</mjx-c></mjx-mi></mjx-script></mjx-msub></mjx-mrow></mjx-mstyle></mjx-math></mjx-container></span>&nbsp;— температура в градусах Фаренгейта. Скольким <span>градусам по шкале Фаренгейта соответствует <span class=\"mml\"><mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-mrow data-semantic-type=\"prefixop\" data-semantic-role=\"negative\" data-semantic-annotation=\"clearspeak:simple;depth:1\" data-semantic-id=\"2\" data-semantic-children=\"1\" data-semantic-content=\"0\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-operator=\"prefixop,−\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2212\">−</mjx-c></mjx-mo><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c34\" noic=\"true\" style=\"padding-top: 0.677em;\">4</mjx-c><mjx-c class=\"mjx-c35\" style=\"padding-top: 0.677em;\">5</mjx-c></mjx-mn></mjx-mrow></mjx-mstyle></mjx-math></mjx-container></span><span>&nbsp;градусов по шкале Цельсия?</span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p091",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 91,
      "prompt": "Впишите правильный ответ.",
      "question": "Центростремительное ускорение при движении по окружности ( в  м /​⁢с2) вычисляется по формуле 𝑎 =ω2⁢𝑅, где ω — угловая скорость ( в  с− ⁢1),\n𝑅 — радиус окружности (в метрах). Пользуясь этой формулой, найдите радиус 𝑅, если угловая скорость равна 9 с− ⁢1, а центростремительное ускорение равно 243 м /​⁢с2. Ответ дайте в метрах.",
      "answer": "",
      "solution": "",
      "source_guid": "0A2D928EEF9B9FDF489A435C1B9FC49E",
      "source_number": "CA6040",
      "source_answer_type": "Краткий ответ",
      "source_kes": "2.2 Степень с целым показателем. Степень с рациональным показателем. Свойства степени",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\"><span>Центростремительное ускорение </span>при движении по окружности<span> <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(22 0 (20 1 2 3 4 5 (14 6 7 (13 8 12 (11 9 10)))) 21)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow><mjx-mrow data-semantic-type=\"fenced\" data-semantic-role=\"leftright\" data-semantic-annotation=\"fences:paren;depth:1\" data-semantic-id=\"22\" data-semantic-children=\"20\" data-semantic-content=\"0,21\" data-semantic-owns=\"0 20 21\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"open\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"22\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c28 NCM-LO\">(</mjx-c></mjx-mo><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"text\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"20\" data-semantic-children=\"1,2,3,4,5,14\" data-semantic-parent=\"22\" data-semantic-collapsed=\"(20 (c 15 16 17 18 19) 1 2 3 4 5 14)\" data-semantic-owns=\"1 2 3 4 5 14\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"20\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"annotation\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"2\" data-semantic-parent=\"20\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c432 NCM-CY\">в</mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"3\" data-semantic-parent=\"20\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"20\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"annotation\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"5\" data-semantic-parent=\"20\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c43C NCM-CY\">м</mjx-c></mjx-mtext><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"division\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"14\" data-semantic-children=\"6,13\" data-semantic-content=\"7\" data-semantic-parent=\"20\" data-semantic-owns=\"6 7 13\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"factor:operator;clearspeak:unit;nemeth:number;depth:4\" data-semantic-id=\"6\" data-semantic-parent=\"14\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c200A\"> </mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"division\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"7\" data-semantic-parent=\"14\" data-semantic-operator=\"infixop,/\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2F\">/</mjx-c></mjx-mo><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:4\" data-semantic-id=\"13\" data-semantic-children=\"8,11\" data-semantic-content=\"12\" data-semantic-parent=\"14\" data-semantic-owns=\"8 12 11\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"general:text;factor:operator;clearspeak:unit;depth:5\" data-semantic-id=\"8\" data-semantic-parent=\"13\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c200B\">​</mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"12\" data-semantic-parent=\"13\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"11\" data-semantic-children=\"9,10\" data-semantic-parent=\"13\" data-semantic-owns=\"9 10\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"unknown\" data-semantic-annotation=\"clearspeak:unit;depth:6\" data-semantic-id=\"9\" data-semantic-parent=\"11\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c441 NCM-CY\">с</mjx-c></mjx-mtext><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:6\" data-semantic-id=\"10\" data-semantic-parent=\"11\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup></mjx-mrow></mjx-mrow></mjx-mrow><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"close\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"21\" data-semantic-parent=\"22\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c29 NCM-LO\">)</mjx-c></mjx-mo></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;вычисляется по формуле <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(8 0 1 (7 (4 2 3) 6 5))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"8\" data-semantic-children=\"0,7\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 7\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"8\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D44E\">𝑎</mjx-c></mjx-mi><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"8\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:2\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"greekletter\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-children=\"2,3\" data-semantic-parent=\"7\" data-semantic-owns=\"2 3\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"greekletter\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:4\" data-semantic-id=\"2\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3C9\">ω</mjx-c></mjx-mtext><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"greekletter\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3C9\">ω</mjx-c></mjx-mtext></mjx-semantics></mjx-mstyle></mjx-math></mjx-container></span>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;угловая скорость <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(19 0 (17 1 2 3 4 (12 5 (11 6 (10 7 9 8)))) 18)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow><mjx-mrow data-semantic-type=\"fenced\" data-semantic-role=\"leftright\" data-semantic-annotation=\"fences:paren;depth:1\" data-semantic-id=\"19\" data-semantic-children=\"17\" data-semantic-content=\"0,18\" data-semantic-owns=\"0 17 18\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"open\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"19\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c28 NCM-LO\">(</mjx-c></mjx-mo><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"text\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"17\" data-semantic-children=\"1,2,3,4,12\" data-semantic-parent=\"19\" data-semantic-collapsed=\"(17 (c 13 14 15 16) 1 2 3 4 12)\" data-semantic-owns=\"1 2 3 4 12\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"17\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"annotation\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"2\" data-semantic-parent=\"17\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c432 NCM-CY\">в</mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"3\" data-semantic-parent=\"17\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"17\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"12\" data-semantic-children=\"5,11\" data-semantic-parent=\"17\" data-semantic-owns=\"5 11\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"unknown\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:4\" data-semantic-id=\"5\" data-semantic-parent=\"12\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c441 NCM-CY\">с</mjx-c></mjx-mtext><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mrow size=\"s\" data-semantic-type=\"prefixop\" data-semantic-role=\"negative\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"11\" data-semantic-children=\"10\" data-semantic-content=\"6\" data-semantic-parent=\"12\" data-semantic-owns=\"6 10\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"6\" data-semantic-parent=\"11\" data-semantic-operator=\"prefixop,−\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2212\">−</mjx-c></mjx-mo><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:5\" data-semantic-id=\"10\" data-semantic-children=\"7,8\" data-semantic-content=\"9\" data-semantic-parent=\"11\" data-semantic-owns=\"7 9 8\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"factor:operator;clearspeak:unit;depth:6\" data-semantic-id=\"7\" data-semantic-parent=\"10\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:6\" data-semantic-id=\"9\" data-semantic-parent=\"10\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:6\" data-semantic-id=\"8\" data-semantic-parent=\"10\" data-semantic-level-number=\"5\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-mrow></mjx-script></mjx-msup></mjx-mrow><mjx-mo data-semantic-type=\"fence\" data-semantic-role=\"close\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"18\" data-semantic-parent=\"19\" data-semantic-operator=\"fenced\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c29 NCM-LO\">)</mjx-c></mjx-mo></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <br> <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;радиус окружности <span>(в метрах)</span>. Пользуясь этой формулой, найдите<span> радиус<span class=\"apple-converted-space\"> <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container></span>, если угловая скорость равна <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(12 0 1 (9 2 (8 3 (7 4 6 5))))\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"text\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"12\" data-semantic-children=\"0,1,9\" data-semantic-collapsed=\"(12 (c 10 11) 0 1 9)\" data-semantic-owns=\"0 1 9\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"12\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c39\">9</mjx-c></mjx-mn><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"12\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"9\" data-semantic-children=\"2,8\" data-semantic-parent=\"12\" data-semantic-owns=\"2 8\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"unknown\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"2\" data-semantic-parent=\"9\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c441 NCM-CY\">с</mjx-c></mjx-mtext><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mrow size=\"s\" data-semantic-type=\"prefixop\" data-semantic-role=\"negative\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"8\" data-semantic-children=\"7\" data-semantic-content=\"3\" data-semantic-parent=\"9\" data-semantic-owns=\"3 7\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"3\" data-semantic-parent=\"8\" data-semantic-operator=\"prefixop,−\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2212\">−</mjx-c></mjx-mo><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:4\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"factor:operator;clearspeak:unit;depth:5\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:5\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-mrow></mjx-script></mjx-msup></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, а центростремительное ускорение равно <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(15 0 1 2 (11 3 4 (10 5 9 (8 6 7))))\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"text\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"15\" data-semantic-children=\"0,1,2,11\" data-semantic-collapsed=\"(15 (c 12 13 14) 0 1 2 11)\" data-semantic-owns=\"0 1 2 11\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"15\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\" noic=\"true\" style=\"padding-top: 0.677em;\">2</mjx-c><mjx-c class=\"mjx-c34\" noic=\"true\" style=\"padding-top: 0.677em;\">4</mjx-c><mjx-c class=\"mjx-c33\" style=\"padding-top: 0.677em;\">3</mjx-c></mjx-mn><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"15\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2009\"> </mjx-c></mjx-mtext><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"annotation\" data-semantic-annotation=\"clearspeak:unit;nemeth:number;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"15\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c43C NCM-CY\">м</mjx-c></mjx-mtext><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"division\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"11\" data-semantic-children=\"3,10\" data-semantic-content=\"4\" data-semantic-parent=\"15\" data-semantic-owns=\"3 4 10\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"factor:operator;clearspeak:unit;nemeth:number;depth:3\" data-semantic-id=\"3\" data-semantic-parent=\"11\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c200A\"> </mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"division\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"11\" data-semantic-operator=\"infixop,/\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2F\">/</mjx-c></mjx-mo><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:3\" data-semantic-id=\"10\" data-semantic-children=\"5,8\" data-semantic-content=\"9\" data-semantic-parent=\"11\" data-semantic-owns=\"5 9 8\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"general:text;factor:operator;clearspeak:unit;depth:4\" data-semantic-id=\"5\" data-semantic-parent=\"10\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c200B\">​</mjx-c></mjx-mtext><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"9\" data-semantic-parent=\"10\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"8\" data-semantic-children=\"6,7\" data-semantic-parent=\"10\" data-semantic-owns=\"6 7\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"unknown\" data-semantic-annotation=\"clearspeak:unit;depth:5\" data-semantic-id=\"6\" data-semantic-parent=\"8\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c441 NCM-CY\">с</mjx-c></mjx-mtext><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"7\" data-semantic-parent=\"8\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup></mjx-mrow></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Ответ дайте в метрах.</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p117",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 2,
      "item_number": 117,
      "prompt": "Впишите правильный ответ.",
      "question": "Мощность постоянного тока (в ваттах) вычисляется по формуле 𝑃 =𝐼2⁢𝑅,\nгде 𝐼 — сила тока (в амперах), 𝑅 — сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление 𝑅, если мощность составляет 423,5 Вт,\nа сила тока равна 5,5 А. Ответ дайте в омах.",
      "answer": "",
      "solution": "",
      "source_guid": "15E88CAB6B82B48D45D3EDE5AB6BBEED",
      "source_number": "155EF3",
      "source_answer_type": "Краткий ответ",
      "source_kes": "2.2 Степень с целым показателем. Степень с рациональным показателем. Свойства степени",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Мощность постоянного тока (в ваттах) вычисляется по формуле <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(8 0 1 (7 (4 2 3) 6 5))\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"8\" data-semantic-children=\"0,7\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 7\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"8\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D443\">𝑃</mjx-c></mjx-mi><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"8\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mrow space=\"4\" data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:2\" data-semantic-id=\"7\" data-semantic-children=\"4,5\" data-semantic-content=\"6\" data-semantic-parent=\"8\" data-semantic-owns=\"4 6 5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-children=\"2,3\" data-semantic-parent=\"7\" data-semantic-owns=\"2 3\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:4\" data-semantic-id=\"2\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D43C\">𝐼</mjx-c></mjx-mi><mjx-script style=\"vertical-align: 0.413em; margin-left: 0.053em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:4\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-mrow></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <br> где <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D43C\">𝐼</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;сила тока (в амперах), <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;<mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mo data-semantic-type=\"punctuation\" data-semantic-role=\"dash\" data-semantic-annotation=\"nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2014\">—</mjx-c></mjx-mo></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;сопротивление (в омах). Пользуясь этой формулой, найдите сопротивление <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D445\">𝑅</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, если мощность составляет 423,5&nbsp;Вт, <br> а сила тока равна 5,5&nbsp;А. Ответ дайте в омах.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
  ]
}
);
