window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push(
{
  "subject": "Математика",
  "number": 9,
  "title": "Уравнения",
  "total_tasks": 73,
  "items": [
    {
      "id": "math-oge-009-p001",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x+3=-9x",
      "expression": "x+3=-9x"
    },
    {
      "id": "math-oge-009-p002",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-3x-9=2x",
      "expression": "-3x-9=2x"
    },
    {
      "id": "math-oge-009-p003",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 3,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "6x+1=-4x",
      "expression": "6x+1=-4x"
    },
    {
      "id": "math-oge-009-p004",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 7,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "7+8x=-2x-5",
      "expression": "7+8x=-2x-5"
    },
    {
      "id": "math-oge-009-p005",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 8,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-5+9x=10x+4",
      "expression": "-5+9x=10x+4"
    },
    {
      "id": "math-oge-009-p006",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 9,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "1-10x=-5x+10",
      "expression": "1-10x=-5x+10"
    },
    {
      "id": "math-oge-009-p007",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 13,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "4(x-8)=-5",
      "expression": "4(x-8)=-5"
    },
    {
      "id": "math-oge-009-p008",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 14,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "10(x-9)=7",
      "expression": "10(x-9)=7"
    },
    {
      "id": "math-oge-009-p009",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 15,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "5(x+9)=-8",
      "expression": "5(x+9)=-8"
    },
    {
      "id": "math-oge-009-p010",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 1,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-9=0",
      "expression": "x^2-9=0"
    },
    {
      "id": "math-oge-009-p011",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 2,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-64=0",
      "expression": "x^2-64=0"
    },
    {
      "id": "math-oge-009-p012",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 3,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-144=0",
      "expression": "x^2-144=0"
    },
    {
      "id": "math-oge-009-p013",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 4,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-81=0",
      "expression": "x^2-81=0"
    },
    {
      "id": "math-oge-009-p014",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 5,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-169=0",
      "expression": "x^2-169=0"
    },
    {
      "id": "math-oge-009-p015",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 6,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-16=0",
      "expression": "x^2-16=0"
    },
    {
      "id": "math-oge-009-p016",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 7,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "4x^2=8x",
      "expression": "4x^2=8x"
    },
    {
      "id": "math-oge-009-p017",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 8,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "7x^2=42x",
      "expression": "7x^2=42x"
    },
    {
      "id": "math-oge-009-p018",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 9,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "10x^2=80x",
      "expression": "10x^2=80x"
    },
    {
      "id": "math-oge-009-p019",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 2,
      "task_group": 2,
      "item_number": 10,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "5x^2=35x",
      "expression": "5x^2=35x"
    },
    {
      "id": "math-oge-009-p020",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 1,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-6x+5=0",
      "expression": "x^2-6x+5=0"
    },
    {
      "id": "math-oge-009-p021",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 2,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-9x+18=0",
      "expression": "x^2-9x+18=0"
    },
    {
      "id": "math-oge-009-p022",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 3,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-10x+24=0",
      "expression": "x^2-10x+24=0"
    },
    {
      "id": "math-oge-009-p023",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 4,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2+x-12=0",
      "expression": "x^2+x-12=0"
    },
    {
      "id": "math-oge-009-p024",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 5,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-11x+30=0",
      "expression": "x^2-11x+30=0"
    },
    {
      "id": "math-oge-009-p025",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 3,
      "task_group": 4,
      "item_number": 6,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "x^2-7x+10=0",
      "expression": "x^2-7x+10=0"
    },
    {
      "id": "math-oge-009-p026",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 1,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "2x^2-3x+1=0",
      "expression": "2x^2-3x+1=0"
    },
    {
      "id": "math-oge-009-p027",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 2,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "5x^2-9x+4=0",
      "expression": "5x^2-9x+4=0"
    },
    {
      "id": "math-oge-009-p028",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 3,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "8x^2-10x+2=0",
      "expression": "8x^2-10x+2=0"
    },
    {
      "id": "math-oge-009-p029",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 4,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "6x^2-9x+3=0",
      "expression": "6x^2-9x+3=0"
    },
    {
      "id": "math-oge-009-p030",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 5,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "8x^2-12x+4=0",
      "expression": "8x^2-12x+4=0"
    },
    {
      "id": "math-oge-009-p031",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 4,
      "task_group": 6,
      "item_number": 6,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "2x^2+5x-7=0",
      "expression": "2x^2+5x-7=0"
    },
    {
      "id": "math-oge-009-p032",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "2+3x=-7x-5",
      "expression": "2+3x=-7x-5"
    },
    {
      "id": "math-oge-009-p033",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "7+8x=-2x-5",
      "expression": "7+8x=-2x-5"
    },
    {
      "id": "math-oge-009-p034",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 3,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-7-2x=-6x+10",
      "expression": "-7-2x=-6x+10"
    },
    {
      "id": "math-oge-009-p035",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 4,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-1-3x=2x+1",
      "expression": "-1-3x=2x+1"
    },
    {
      "id": "math-oge-009-p036",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 5,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "8-5(2x-3)=13-6x",
      "expression": "8-5(2x-3)=13-6x"
    },
    {
      "id": "math-oge-009-p037",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 1,
      "item_number": 6,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "1-7(4+2x)=-9-4x",
      "expression": "1-7(4+2x)=-9-4x"
    },
    {
      "id": "math-oge-009-p038",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "3x+5+(x+5)=(1-x)+4",
      "expression": "3x+5+(x+5)=(1-x)+4"
    },
    {
      "id": "math-oge-009-p039",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x-3-4(x+1)=5(4-x)-1",
      "expression": "x-3-4(x+1)=5(4-x)-1"
    },
    {
      "id": "math-oge-009-p040",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 3,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "4x+4-3(x+1)=5(-2-x)+5",
      "expression": "4x+4-3(x+1)=5(-2-x)+5"
    },
    {
      "id": "math-oge-009-p041",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 4,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "2x+2+3(x+4)=-4(1-x)+3",
      "expression": "2x+2+3(x+4)=-4(1-x)+3"
    },
    {
      "id": "math-oge-009-p042",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 5,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-3x+1+(x-5)=5(3-x)+5",
      "expression": "-3x+1+(x-5)=5(3-x)+5"
    },
    {
      "id": "math-oge-009-p043",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 6,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-x-4+5(x+3)=5(-1-x)-2",
      "expression": "-x-4+5(x+3)=5(-1-x)-2"
    },
    {
      "id": "math-oge-009-p044",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 7,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-3x+1-3(x+3)=-2(1-x)+2",
      "expression": "-3x+1-3(x+3)=-2(1-x)+2"
    },
    {
      "id": "math-oge-009-p045",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 2,
      "item_number": 8,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-5x-2+4(x+1)=4(-3-x)-1",
      "expression": "-5x-2+4(x+1)=4(-3-x)-1"
    },
    {
      "id": "math-oge-009-p046",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-5)^2=(x-8)^2",
      "expression": "(x-5)^2=(x-8)^2"
    },
    {
      "id": "math-oge-009-p047",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x+9)^2=(x+6)^2",
      "expression": "(x+9)^2=(x+6)^2"
    },
    {
      "id": "math-oge-009-p048",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 3,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x+10)^2=(5-x)^2",
      "expression": "(x+10)^2=(5-x)^2"
    },
    {
      "id": "math-oge-009-p049",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 4,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-3)^2=(x+10)^2",
      "expression": "(x-3)^2=(x+10)^2"
    },
    {
      "id": "math-oge-009-p050",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 5,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x+6)^2=(15-x)^2",
      "expression": "(x+6)^2=(15-x)^2"
    },
    {
      "id": "math-oge-009-p051",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 3,
      "item_number": 6,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-2)^2=(x-9)^2",
      "expression": "(x-2)^2=(x-9)^2"
    },
    {
      "id": "math-oge-009-p052",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 4,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x+1)^2+(x-6)^2=2x^2",
      "expression": "(x+1)^2+(x-6)^2=2x^2"
    },
    {
      "id": "math-oge-009-p053",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 4,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-2)^2+(x-8)^2=2x^2",
      "expression": "(x-2)^2+(x-8)^2=2x^2"
    },
    {
      "id": "math-oge-009-p054",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 4,
      "item_number": 3,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-6)^2+(x+8)^2=2x^2",
      "expression": "(x-6)^2+(x+8)^2=2x^2"
    },
    {
      "id": "math-oge-009-p055",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 5,
      "task_group": 4,
      "item_number": 4,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "(x-2)^2+(x-3)^2=2x^2",
      "expression": "(x-2)^2+(x-3)^2=2x^2"
    },
    {
      "id": "math-oge-009-p056",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x+x/9=-10/3",
      "expression": "x+\\frac{x}{9}=-\\frac{10}{3}"
    },
    {
      "id": "math-oge-009-p057",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x-x/7=6",
      "expression": "x-\\frac{x}{7}=6"
    },
    {
      "id": "math-oge-009-p058",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 4,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x-x/12=11/3",
      "expression": "x-\\frac{x}{12}=\\frac{11}{3}"
    },
    {
      "id": "math-oge-009-p059",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 5,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "x+x/2=-9",
      "expression": "x+\\frac{x}{2}=-9"
    },
    {
      "id": "math-oge-009-p060",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 7,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "6+x/2=(x+3)/5",
      "expression": "6+\\frac{x}{2}=\\frac{x+3}{5}"
    },
    {
      "id": "math-oge-009-p061",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 6,
      "task_group": 6,
      "item_number": 8,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "-4+x/5=(x+4)/2",
      "expression": "-4+\\frac{x}{5}=\\frac{x+4}{2}"
    },
    {
      "id": "math-oge-009-p062",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 1,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "12/(x+5)=-12/5",
      "expression": "\\frac{12}{x+5}=-\\frac{12}{5}"
    },
    {
      "id": "math-oge-009-p063",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 2,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "6/(x+8)=-3/4",
      "expression": "\\frac{6}{x+8}=-\\frac{3}{4}"
    },
    {
      "id": "math-oge-009-p064",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 7,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "7/(x-5)=2",
      "expression": "\\frac{7}{x-5}=2"
    },
    {
      "id": "math-oge-009-p065",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 8,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "4/(x-4)=-5",
      "expression": "\\frac{4}{x-4}=-5"
    },
    {
      "id": "math-oge-009-p066",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 13,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "3/(x-19)=19/(x-3)",
      "expression": "\\frac{3}{x-19}=\\frac{19}{x-3}"
    },
    {
      "id": "math-oge-009-p067",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 7,
      "task_group": 7,
      "item_number": 14,
      "prompt": "Найдите корень уравнения.",
      "question_raw": "13/(x-5)=5/(x-13)",
      "expression": "\\frac{13}{x-5}=\\frac{5}{x-13}"
    },
    {
      "id": "math-oge-009-p068",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 1,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(5x-2)(-x+3)=0",
      "expression": "(5x-2)(-x+3)=0"
    },
    {
      "id": "math-oge-009-p069",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 2,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(x-6)(4x-6)=0",
      "expression": "(x-6)(4x-6)=0"
    },
    {
      "id": "math-oge-009-p070",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 3,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(-2x+1)(-2x-7)=0",
      "expression": "(-2x+1)(-2x-7)=0"
    },
    {
      "id": "math-oge-009-p071",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 4,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(x-7)(-5x-9)=0",
      "expression": "(x-7)(-5x-9)=0"
    },
    {
      "id": "math-oge-009-p072",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 5,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(-5x+3)(-x+6)=0",
      "expression": "(-5x+3)(-x+6)=0"
    },
    {
      "id": "math-oge-009-p073",
      "subject": "Математика",
      "number": 9,
      "title": "Уравнения",
      "block": "",
      "page": 8,
      "task_group": 9,
      "item_number": 6,
      "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
      "question_raw": "(x-2)(-2x-3)=0",
      "expression": "(x-2)(-2x-3)=0"
    },
    {
      "id": "math-oge-007-p044",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 44,
      "prompt": "Впишите правильный ответ.",
      "question": "Решите уравнение 𝑥2⁢  −144 =0.\n\nЕсли уравнение имеет более одного корня, в ответ запишите меньший\nиз корней.",
      "answer": "",
      "solution": "",
      "source_guid": "04F72D5A81E484404F0182FFC1A59568",
      "source_number": "B0D648",
      "source_answer_type": "Краткий ответ",
      "source_kes": "3.1 Целые и дробно-рациональные уравнения. Системы и совокупности уравнений",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Решите уравнение <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(11 (10 (9 (2 0 1) 8 3) 4 5) 6 7)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"11\" data-semantic-children=\"10,7\" data-semantic-content=\"6\" data-semantic-owns=\"10 6 7\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"10\" data-semantic-children=\"9,5\" data-semantic-content=\"4\" data-semantic-parent=\"11\" data-semantic-owns=\"9 4 5\" data-semantic-level-number=\"1\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:3\" data-semantic-id=\"9\" data-semantic-children=\"2,3\" data-semantic-content=\"8\" data-semantic-parent=\"10\" data-semantic-owns=\"2 8 3\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-msup data-semantic-type=\"superscript\" data-semantic-role=\"latinletter\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-parent=\"9\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:5\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D465\">𝑥</mjx-c></mjx-mi><mjx-script style=\"vertical-align: 0.413em;\"><mjx-mn size=\"s\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:5\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"4\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-script></mjx-msup><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:4\" data-semantic-id=\"8\" data-semantic-parent=\"9\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mtext data-semantic-type=\"text\" data-semantic-role=\"space\" data-semantic-annotation=\"factor:operator;clearspeak:unit;depth:4\" data-semantic-id=\"3\" data-semantic-parent=\"9\" data-semantic-level-number=\"3\" data-speech-node=\"true\"><mjx-c class=\"mjx-c200A\"> </mjx-c></mjx-mtext></mjx-mrow><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"subtraction\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"10\" data-semantic-operator=\"infixop,−\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2212\">−</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"5\" data-semantic-parent=\"10\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.677em;\">1</mjx-c><mjx-c class=\"mjx-c34\" noic=\"true\" style=\"padding-top: 0.677em;\">4</mjx-c><mjx-c class=\"mjx-c34\" style=\"padding-top: 0.677em;\">4</mjx-c></mjx-mn></mjx-mrow><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"6\" data-semantic-parent=\"11\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mn space=\"4\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"7\" data-semantic-parent=\"11\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c30\">0</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>.</p> <p class=\"MsoNormal\">Если уравнение имеет более одного корня, в ответ запишите меньший <br> из корней.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
  ]
}
);
