window.EGE_TASKS = window.EGE_TASKS || [];
window.EGE_TASKS.push(
{
    "id": "math-oge-009-p001",
    "subject": "Математика",
    "number": 1,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "7x-5=3x+19",
    "expression": "7x-5=3x+19",
    "answer": "6"
  },
  {
    "id": "math-oge-009-p002",
    "subject": "Математика",
    "number": 2,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "-3(2x-5)+4x=7",
    "expression": "-3(2x-5)+4x=7",
    "answer": "4"
  },
  {
    "id": "math-oge-009-p003",
    "subject": "Математика",
    "number": 3,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "5x+2(7-3x)=9",
    "expression": "5x+2(7-3x)=9",
    "answer": "5"
  },
  {
    "id": "math-oge-009-p004",
    "subject": "Математика",
    "number": 4,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 4,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "4(3x-2)-5x=13",
    "expression": "4(3x-2)-5x=13",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p005",
    "subject": "Математика",
    "number": 5,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "2-5(x-1)=3x+7",
    "expression": "2-5(x-1)=3x+7",
    "answer": "0"
  },
  {
    "id": "math-oge-009-p006",
    "subject": "Математика",
    "number": 6,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 6,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "6(x+2)-4(2x-1)=10",
    "expression": "6(x+2)-4(2x-1)=10",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p007",
    "subject": "Математика",
    "number": 7,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "9-2(3x+4)=5x-10",
    "expression": "9-2(3x+4)=5x-10",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p008",
    "subject": "Математика",
    "number": 8,
    "title": "Уравнения",
    "block": "Линейные уравнения",
    "page": 1,
    "task_group": 1,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "7(2x-1)-3(x+4)=14",
    "expression": "7(2x-1)-3(x+4)=14",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p009",
    "subject": "Математика",
    "number": 9,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(x-5)^2-x^2=0",
    "expression": "(x-5)^2-x^2=0",
    "answer": "2.5"
  },
  {
    "id": "math-oge-009-p010",
    "subject": "Математика",
    "number": 10,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(2x+3)^2-4x^2=0",
    "expression": "(2x+3)^2-4x^2=0",
    "answer": "-0.75"
  },
  {
    "id": "math-oge-009-p011",
    "subject": "Математика",
    "number": 11,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(x+7)^2=(x-1)^2",
    "expression": "(x+7)^2=(x-1)^2",
    "answer": "-3"
  },
  {
    "id": "math-oge-009-p012",
    "subject": "Математика",
    "number": 12,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 4,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "(3x-4)^2-(x+2)^2=0",
    "expression": "(3x-4)^2-(x+2)^2=0",
    "answer": "0.5"
  },
  {
    "id": "math-oge-009-p013",
    "subject": "Математика",
    "number": 13,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 5,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "(x-6)^2-9=0",
    "expression": "(x-6)^2-9=0",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p014",
    "subject": "Математика",
    "number": 14,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 6,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "(2x-1)^2=25",
    "expression": "(2x-1)^2=25",
    "answer": "-2"
  },
  {
    "id": "math-oge-009-p015",
    "subject": "Математика",
    "number": 15,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "x^2-16x+64=0",
    "expression": "x^2-16x+64=0",
    "answer": "8"
  },
  {
    "id": "math-oge-009-p016",
    "subject": "Математика",
    "number": 16,
    "title": "Уравнения",
    "block": "Уравнения с квадратами выражений",
    "page": 2,
    "task_group": 2,
    "item_number": 8,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "(x+4)^2=36",
    "expression": "(x+4)^2=36",
    "answer": "-10"
  },
  {
    "id": "math-oge-009-p017",
    "subject": "Математика",
    "number": 17,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 1,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2+7x=0",
    "expression": "x^2+7x=0",
    "answer": "-7"
  },
  {
    "id": "math-oge-009-p018",
    "subject": "Математика",
    "number": 18,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 2,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2-9x=0",
    "expression": "x^2-9x=0",
    "answer": "0"
  },
  {
    "id": "math-oge-009-p019",
    "subject": "Математика",
    "number": 19,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 3,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2-49=0",
    "expression": "x^2-49=0",
    "answer": "-7"
  },
  {
    "id": "math-oge-009-p020",
    "subject": "Математика",
    "number": 20,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 4,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2=81",
    "expression": "x^2=81",
    "answer": "-9"
  },
  {
    "id": "math-oge-009-p021",
    "subject": "Математика",
    "number": 21,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 5,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2+13x+40=0",
    "expression": "x^2+13x+40=0",
    "answer": "-8"
  },
  {
    "id": "math-oge-009-p022",
    "subject": "Математика",
    "number": 22,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 6,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2-2x=35",
    "expression": "x^2-2x=35",
    "answer": "-5"
  },
  {
    "id": "math-oge-009-p023",
    "subject": "Математика",
    "number": 23,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 7,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2+5=6x",
    "expression": "x^2+5=6x",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p024",
    "subject": "Математика",
    "number": 24,
    "title": "Уравнения",
    "block": "Квадратные уравнения",
    "page": 3,
    "task_group": 3,
    "item_number": 8,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "x^2=-8x+20",
    "expression": "x^2=-8x+20",
    "answer": "-10"
  },
  {
    "id": "math-oge-009-p025",
    "subject": "Математика",
    "number": 25,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "sqrt(3x+1)=4",
    "expression": "sqrt(3x+1)=4",
    "answer": "5"
  },
  {
    "id": "math-oge-009-p026",
    "subject": "Математика",
    "number": 26,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "sqrt(20-2x)=6",
    "expression": "sqrt(20-2x)=6",
    "answer": "-8"
  },
  {
    "id": "math-oge-009-p027",
    "subject": "Математика",
    "number": 27,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "1/sqrt(x)=1/5",
    "expression": "1/sqrt(x)=1/5",
    "answer": "25"
  },
  {
    "id": "math-oge-009-p028",
    "subject": "Математика",
    "number": 28,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 4,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "sqrt(5x-4)=x",
    "expression": "sqrt(5x-4)=x",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p029",
    "subject": "Математика",
    "number": 29,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "sqrt(x+6)=x",
    "expression": "sqrt(x+6)=x",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p030",
    "subject": "Математика",
    "number": 30,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 6,
    "prompt": "Решите уравнение. Если уравнение имеет более одного корня, в ответ запишите меньший из корней.",
    "question_raw": "sqrt(4x+9)=x+3",
    "expression": "sqrt(4x+9)=x+3",
    "answer": "-2"
  },
  {
    "id": "math-oge-009-p031",
    "subject": "Математика",
    "number": 31,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "sqrt(7-x)=2",
    "expression": "sqrt(7-x)=2",
    "answer": "3"
  },
  {
    "id": "math-oge-009-p032",
    "subject": "Математика",
    "number": 32,
    "title": "Уравнения",
    "block": "Иррациональные уравнения",
    "page": 4,
    "task_group": 4,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "3/sqrt(x)=1",
    "expression": "3/sqrt(x)=1",
    "answer": "9"
  },
  {
    "id": "math-oge-009-p033",
    "subject": "Математика",
    "number": 33,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "2^(3x-1)=2^(x+7)",
    "expression": "2^(3x-1)=2^(x+7)",
    "answer": "4"
  },
  {
    "id": "math-oge-009-p034",
    "subject": "Математика",
    "number": 34,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "5^(2x+3)=125",
    "expression": "5^(2x+3)=125",
    "answer": "0"
  },
  {
    "id": "math-oge-009-p035",
    "subject": "Математика",
    "number": 35,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "3^(7-x)=27^(x-1)",
    "expression": "3^(7-x)=27^(x-1)",
    "answer": "2.5"
  },
  {
    "id": "math-oge-009-p036",
    "subject": "Математика",
    "number": 36,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 4,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "4^(x+1)=64",
    "expression": "4^(x+1)=64",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p037",
    "subject": "Математика",
    "number": 37,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/2)^(x-4)=1/32",
    "expression": "(1/2)^(x-4)=1/32",
    "answer": "9"
  },
  {
    "id": "math-oge-009-p038",
    "subject": "Математика",
    "number": 38,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 6,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/3)^(2x+1)=1/81",
    "expression": "(1/3)^(2x+1)=1/81",
    "answer": "1.5"
  },
  {
    "id": "math-oge-009-p039",
    "subject": "Математика",
    "number": 39,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/5)^(2x-1)=1/125",
    "expression": "(1/5)^(2x-1)=1/125",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p040",
    "subject": "Математика",
    "number": 40,
    "title": "Уравнения",
    "block": "Показательные уравнения",
    "page": 5,
    "task_group": 5,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/4)^(x+2)=16",
    "expression": "(1/4)^(x+2)=16",
    "answer": "-4"
  },
  {
    "id": "math-oge-009-p041",
    "subject": "Математика",
    "number": 41,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "7^(2x+1)*7^(5-x)=343",
    "expression": "7^(2x+1)*7^(5-x)=343",
    "answer": "-3"
  },
  {
    "id": "math-oge-009-p042",
    "subject": "Математика",
    "number": 42,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "3^(4x-2)/3^(x+1)=27",
    "expression": "3^(4x-2)/3^(x+1)=27",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p043",
    "subject": "Математика",
    "number": 43,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "5^(x+4)*25^(2-x)=125",
    "expression": "5^(x+4)*25^(2-x)=125",
    "answer": "5"
  },
  {
    "id": "math-oge-009-p044",
    "subject": "Математика",
    "number": 44,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 4,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "2^(6x-1)/4^(x+2)=8",
    "expression": "2^(6x-1)/4^(x+2)=8",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p045",
    "subject": "Математика",
    "number": 45,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "6^(3-2x)*6^(x+5)=1/36",
    "expression": "6^(3-2x)*6^(x+5)=1/36",
    "answer": "10"
  },
  {
    "id": "math-oge-009-p046",
    "subject": "Математика",
    "number": 46,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 6,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/3)^(2x-1)*(1/3)^(x+4)=1/729",
    "expression": "(1/3)^(2x-1)*(1/3)^(x+4)=1/729",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p047",
    "subject": "Математика",
    "number": 47,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "(1/5)^(7-x)/(1/5)^(2x-2)=1/125",
    "expression": "(1/5)^(7-x)/(1/5)^(2x-2)=1/125",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p048",
    "subject": "Математика",
    "number": 48,
    "title": "Уравнения",
    "block": "Показательные уравнения со степенями",
    "page": 6,
    "task_group": 6,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "4^(5-2x)=(1/64)^(x-1)",
    "expression": "4^(5-2x)=(1/64)^(x-1)",
    "answer": "-2"
  },
  {
    "id": "math-oge-009-p049",
    "subject": "Математика",
    "number": 49,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_2(3x+1)=4",
    "expression": "log_2(3x+1)=4",
    "answer": "5"
  },
  {
    "id": "math-oge-009-p050",
    "subject": "Математика",
    "number": 50,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_5(2x-3)=2",
    "expression": "log_5(2x-3)=2",
    "answer": "14"
  },
  {
    "id": "math-oge-009-p051",
    "subject": "Математика",
    "number": 51,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_3(10-x)=2",
    "expression": "log_3(10-x)=2",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p052",
    "subject": "Математика",
    "number": 52,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 4,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_(1/2)(x+3)=-2",
    "expression": "log_(1/2)(x+3)=-2",
    "answer": "1"
  },
  {
    "id": "math-oge-009-p053",
    "subject": "Математика",
    "number": 53,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_4(5x-4)=1",
    "expression": "log_4(5x-4)=1",
    "answer": "1.6"
  },
  {
    "id": "math-oge-009-p054",
    "subject": "Математика",
    "number": 54,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 6,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_(1/3)(2x+7)=-1",
    "expression": "log_(1/3)(2x+7)=-1",
    "answer": "-2"
  },
  {
    "id": "math-oge-009-p055",
    "subject": "Математика",
    "number": 55,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_7(x-5)=0",
    "expression": "log_7(x-5)=0",
    "answer": "6"
  },
  {
    "id": "math-oge-009-p056",
    "subject": "Математика",
    "number": 56,
    "title": "Уравнения",
    "block": "Логарифмические уравнения",
    "page": 7,
    "task_group": 7,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "ln(3x-2)=ln(10)",
    "expression": "ln(3x-2)=ln(10)",
    "answer": "4"
  },
  {
    "id": "math-oge-009-p057",
    "subject": "Математика",
    "number": 57,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 1,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_2(x+3)+log_2(4)=log_2(28)",
    "expression": "log_2(x+3)+log_2(4)=log_2(28)",
    "answer": "4"
  },
  {
    "id": "math-oge-009-p058",
    "subject": "Математика",
    "number": 58,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 2,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_3(2x-1)-log_3(5)=log_3(3)",
    "expression": "log_3(2x-1)-log_3(5)=log_3(3)",
    "answer": "8"
  },
  {
    "id": "math-oge-009-p059",
    "subject": "Математика",
    "number": 59,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 3,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_5(3x+2)+log_5(2)=log_5(40)",
    "expression": "log_5(3x+2)+log_5(2)=log_5(40)",
    "answer": "6"
  },
  {
    "id": "math-oge-009-p060",
    "subject": "Математика",
    "number": 60,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 4,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "ln(4x+1)-ln(3)=ln(5)",
    "expression": "ln(4x+1)-ln(3)=ln(5)",
    "answer": "3.5"
  },
  {
    "id": "math-oge-009-p061",
    "subject": "Математика",
    "number": 61,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 5,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_(1/2)(x-1)+log_(1/2)(4)=log_(1/2)(12)",
    "expression": "log_(1/2)(x-1)+log_(1/2)(4)=log_(1/2)(12)",
    "answer": "4"
  },
  {
    "id": "math-oge-009-p062",
    "subject": "Математика",
    "number": 62,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 6,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_(1/3)(5x+2)-log_(1/3)(2)=log_(1/3)(6)",
    "expression": "log_(1/3)(5x+2)-log_(1/3)(2)=log_(1/3)(6)",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p063",
    "subject": "Математика",
    "number": 63,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 7,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_4(2x+5)+log_4(2)=log_4(18)",
    "expression": "log_4(2x+5)+log_4(2)=log_4(18)",
    "answer": "2"
  },
  {
    "id": "math-oge-009-p064",
    "subject": "Математика",
    "number": 64,
    "title": "Уравнения",
    "block": "Логарифмические уравнения со свойствами логарифмов",
    "page": 8,
    "task_group": 8,
    "item_number": 8,
    "prompt": "Найдите корень уравнения.",
    "question_raw": "log_(1/5)(7x-1)-log_(1/5)(3)=log_(1/5)(2)",
    "expression": "log_(1/5)(7x-1)-log_(1/5)(3)=log_(1/5)(2)",
    "answer": "1"
  }
);
