window.EGE_TASKS = window.EGE_TASKS || [];
window.EGE_TASKS.push(
{
  "subject": "Математика",
  "number": 6,
  "title": "Дроби и степени",
  "total_tasks": 210,
  "items": [
    {
      "id": "math-oge-006-p001",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "3/4 · 6/5",
      "expression": "\\frac{3}{4}\\cdot\\frac{6}{5}"
    },
    {
      "id": "math-oge-006-p002",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "21/5 · 3/7",
      "expression": "\\frac{21}{5}\\cdot\\frac{3}{7}"
    },
    {
      "id": "math-oge-006-p003",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "3/5 · 25/4",
      "expression": "\\frac{3}{5}\\cdot\\frac{25}{4}"
    },
    {
      "id": "math-oge-006-p004",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "9/5 · 2/3",
      "expression": "\\frac{9}{5}\\cdot\\frac{2}{3}"
    },
    {
      "id": "math-oge-006-p005",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "5/3 · 9/2",
      "expression": "\\frac{5}{3}\\cdot\\frac{9}{2}"
    },
    {
      "id": "math-oge-006-p006",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "7/5 · 12/35",
      "expression": "\\frac{7}{5}\\cdot\\frac{12}{35}"
    },
    {
      "id": "math-oge-006-p007",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "12/5 : 15/2",
      "expression": "\\frac{12}{5}:\\frac{15}{2}"
    },
    {
      "id": "math-oge-006-p008",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "6/5 : 4/11",
      "expression": "\\frac{6}{5}:\\frac{4}{11}"
    },
    {
      "id": "math-oge-006-p009",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "3/5 : 4/35",
      "expression": "\\frac{3}{5}:\\frac{4}{35}"
    },
    {
      "id": "math-oge-006-p010",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "15/4 : 3/7",
      "expression": "\\frac{15}{4}:\\frac{3}{7}"
    },
    {
      "id": "math-oge-006-p011",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "21/2 : 3/5",
      "expression": "\\frac{21}{2}:\\frac{3}{5}"
    },
    {
      "id": "math-oge-006-p012",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "14/5 : 7/2",
      "expression": "\\frac{14}{5}:\\frac{7}{2}"
    },
    {
      "id": "math-oge-006-p013",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 13,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/4 - 3/25",
      "expression": "\\frac{1}{4}-\\frac{3}{25}"
    },
    {
      "id": "math-oge-006-p014",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 14,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/5 - 27/50",
      "expression": "\\frac{1}{5}-\\frac{27}{50}"
    },
    {
      "id": "math-oge-006-p015",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 15,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/2 - 9/25",
      "expression": "\\frac{1}{2}-\\frac{9}{25}"
    },
    {
      "id": "math-oge-006-p016",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 16,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/5 - 3/4",
      "expression": "\\frac{1}{5}-\\frac{3}{4}"
    },
    {
      "id": "math-oge-006-p017",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 17,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/2 - 13/50",
      "expression": "\\frac{1}{2}-\\frac{13}{50}"
    },
    {
      "id": "math-oge-006-p018",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 18,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/10 - 23/20",
      "expression": "\\frac{1}{10}-\\frac{23}{20}"
    },
    {
      "id": "math-oge-006-p019",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 19,
      "prompt": "Найдите значение выражения",
      "question_raw": "14/25 + 3/2",
      "expression": "\\frac{14}{25}+\\frac{3}{2}"
    },
    {
      "id": "math-oge-006-p020",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 20,
      "prompt": "Найдите значение выражения",
      "question_raw": "9/4 + 8/5",
      "expression": "\\frac{9}{4}+\\frac{8}{5}"
    },
    {
      "id": "math-oge-006-p021",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 21,
      "prompt": "Найдите значение выражения",
      "question_raw": "11/5 + 13/4",
      "expression": "\\frac{11}{5}+\\frac{13}{4}"
    },
    {
      "id": "math-oge-006-p022",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 22,
      "prompt": "Найдите значение выражения",
      "question_raw": "1/10 + 21/50",
      "expression": "\\frac{1}{10}+\\frac{21}{50}"
    },
    {
      "id": "math-oge-006-p023",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 23,
      "prompt": "Найдите значение выражения",
      "question_raw": "3/4 + 7/25",
      "expression": "\\frac{3}{4}+\\frac{7}{25}"
    },
    {
      "id": "math-oge-006-p024",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 1,
      "item_number": 24,
      "prompt": "Найдите значение выражения",
      "question_raw": "4/25 + 15/4",
      "expression": "\\frac{4}{25}+\\frac{15}{4}"
    },
    {
      "id": "math-oge-006-p025",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "9,3 + 7,8",
      "expression": "9,3+7,8"
    },
    {
      "id": "math-oge-006-p026",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "8,7 + 4,6",
      "expression": "8,7+4,6"
    },
    {
      "id": "math-oge-006-p027",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "6,9 + 7,4",
      "expression": "6,9+7,4"
    },
    {
      "id": "math-oge-006-p028",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "5,7 - 7,6",
      "expression": "5,7-7,6"
    },
    {
      "id": "math-oge-006-p029",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "4,9 - 9,4",
      "expression": "4,9-9,4"
    },
    {
      "id": "math-oge-006-p030",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "6,1 - 2,5",
      "expression": "6,1-2,5"
    },
    {
      "id": "math-oge-006-p031",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "5,2 · 3,1",
      "expression": "5,2\\cdot3,1"
    },
    {
      "id": "math-oge-006-p032",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "2,1 · 9,6",
      "expression": "2,1\\cdot9,6"
    },
    {
      "id": "math-oge-006-p033",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "8,9 · 4,3",
      "expression": "8,9\\cdot4,3"
    },
    {
      "id": "math-oge-006-p034",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "8,2 / 4,1",
      "expression": "\\frac{8,2}{4,1}"
    },
    {
      "id": "math-oge-006-p035",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "13,2 / 1,2",
      "expression": "\\frac{13,2}{1,2}"
    },
    {
      "id": "math-oge-006-p036",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 2,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "6,5 / 1,3",
      "expression": "\\frac{6,5}{1,3}"
    },
    {
      "id": "math-oge-006-p037",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 3,
      "item_number": 1,
      "prompt": null,
      "question_raw": "Представьте выражение 7/9 - 2/5 в виде дроби со знаменателем 90. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{7}{9}-\\frac{2}{5}"
    },
    {
      "id": "math-oge-006-p038",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 3,
      "item_number": 2,
      "prompt": null,
      "question_raw": "Представьте выражение 6/7 - 3/5 в виде дроби со знаменателем 70. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{6}{7}-\\frac{3}{5}"
    },
    {
      "id": "math-oge-006-p039",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 3,
      "item_number": 3,
      "prompt": null,
      "question_raw": "Представьте выражение 1/7 + 3/4 в виде дроби со знаменателем 56. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{1}{7}+\\frac{3}{4}"
    },
    {
      "id": "math-oge-006-p040",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 1,
      "task_group": 3,
      "item_number": 4,
      "prompt": null,
      "question_raw": "Представьте выражение 5/8 + 1/3 в виде дроби со знаменателем 48. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{5}{8}+\\frac{1}{3}"
    },
    {
      "id": "math-oge-006-p041",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 3,
      "item_number": 5,
      "prompt": null,
      "question_raw": "Представьте выражение 3/4 - 8/11 в виде дроби со знаменателем 88. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{3}{4}-\\frac{8}{11}"
    },
    {
      "id": "math-oge-006-p042",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 3,
      "item_number": 6,
      "prompt": null,
      "question_raw": "Представьте выражение 2/3 - 7/13 в виде дроби со знаменателем 78. В ответ запишите числитель полученной дроби.",
      "expression": "\\frac{2}{3}-\\frac{7}{13}"
    },
    {
      "id": "math-oge-006-p043",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/30 + 1/42)",
      "expression": "\\frac{1}{\\frac{1}{30}+\\frac{1}{42}}"
    },
    {
      "id": "math-oge-006-p044",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/36 - 1/44)",
      "expression": "\\frac{1}{\\frac{1}{36}-\\frac{1}{44}}"
    },
    {
      "id": "math-oge-006-p045",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/36 + 1/45)",
      "expression": "\\frac{1}{\\frac{1}{36}+\\frac{1}{45}}"
    },
    {
      "id": "math-oge-006-p046",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/35 - 1/60)",
      "expression": "\\frac{1}{\\frac{1}{35}-\\frac{1}{60}}"
    },
    {
      "id": "math-oge-006-p047",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/21 + 1/28)",
      "expression": "\\frac{1}{\\frac{1}{21}+\\frac{1}{28}}"
    },
    {
      "id": "math-oge-006-p048",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "",
      "page": 2,
      "task_group": 4,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 / (1/72 - 1/99)",
      "expression": "\\frac{1}{\\frac{1}{72}-\\frac{1}{99}}"
    },
    {
      "id": "math-oge-006-p049",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "(17/10 - 1/20) · 2/15",
      "expression": "\\left(\\frac{17}{10}-\\frac{1}{20}\\right)\\cdot\\frac{2}{15}"
    },
    {
      "id": "math-oge-006-p050",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "(5/22 - 8/11) · 11/5",
      "expression": "\\left(\\frac{5}{22}-\\frac{8}{11}\\right)\\cdot\\frac{11}{5}"
    },
    {
      "id": "math-oge-006-p051",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "(5/26 - 3/25) · 13/2",
      "expression": "\\left(\\frac{5}{26}-\\frac{3}{25}\\right)\\cdot\\frac{13}{2}"
    },
    {
      "id": "math-oge-006-p052",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "(10/13 + 15/4) · 26/5",
      "expression": "\\left(\\frac{10}{13}+\\frac{15}{4}\\right)\\cdot\\frac{26}{5}"
    },
    {
      "id": "math-oge-006-p053",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "(17/26 + 11/13) · 17/6",
      "expression": "\\left(\\frac{17}{26}+\\frac{11}{13}\\right)\\cdot\\frac{17}{6}"
    },
    {
      "id": "math-oge-006-p054",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "(11/12 + 11/20) · 15/8",
      "expression": "\\left(\\frac{11}{12}+\\frac{11}{20}\\right)\\cdot\\frac{15}{8}"
    },
    {
      "id": "math-oge-006-p055",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "(3/4 - 1/6) · 3",
      "expression": "\\left(\\frac{3}{4}-\\frac{1}{6}\\right)\\cdot 3"
    },
    {
      "id": "math-oge-006-p056",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2/5 + 13/15) · 6",
      "expression": "\\left(\\frac{2}{5}+\\frac{13}{15}\\right)\\cdot 6"
    },
    {
      "id": "math-oge-006-p057",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "(3/8 - 1/20) · 10",
      "expression": "\\left(\\frac{3}{8}-\\frac{1}{20}\\right)\\cdot 10"
    },
    {
      "id": "math-oge-006-p058",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2/20 + 7/30) · 15",
      "expression": "\\left(\\frac{2}{20}+\\frac{7}{30}\\right)\\cdot 15"
    },
    {
      "id": "math-oge-006-p059",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "(9/10 - 7/15) · 3",
      "expression": "\\left(\\frac{9}{10}-\\frac{7}{15}\\right)\\cdot 3"
    },
    {
      "id": "math-oge-006-p060",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 1,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1/6 + 1/4) · 9",
      "expression": "\\left(\\frac{1}{6}+\\frac{1}{4}\\right)\\cdot 9"
    },
    {
      "id": "math-oge-006-p061",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "(9/16 + 2 3/8) · 4",
      "expression": "\\left(\\frac{9}{16}+2\\frac{3}{8}\\right)\\cdot 4"
    },
    {
      "id": "math-oge-006-p062",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "(4/9 - 3 1/15) · 9",
      "expression": "\\left(\\frac{4}{9}-3\\frac{1}{15}\\right)\\cdot 9"
    },
    {
      "id": "math-oge-006-p063",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2 3/4 + 2 1/5) · 16",
      "expression": "\\left(2\\frac{3}{4}+2\\frac{1}{5}\\right)\\cdot 16"
    },
    {
      "id": "math-oge-006-p064",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1 11/16 - 3 7/8) · 4",
      "expression": "\\left(1\\frac{11}{16}-3\\frac{7}{8}\\right)\\cdot 4"
    },
    {
      "id": "math-oge-006-p065",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1 3/4 + 2 4/5) · 30",
      "expression": "\\left(1\\frac{3}{4}+2\\frac{4}{5}\\right)\\cdot 30"
    },
    {
      "id": "math-oge-006-p066",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1/13 - 2 3/4) · 26",
      "expression": "\\left(\\frac{1}{13}-2\\frac{3}{4}\\right)\\cdot 26"
    },
    {
      "id": "math-oge-006-p067",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 8/17 : (12/17 + 2 7/11)",
      "expression": "1\\frac{8}{17}:\\left(\\frac{12}{17}+2\\frac{7}{11}\\right)"
    },
    {
      "id": "math-oge-006-p068",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "3 4/9 : (1 5/9 - 4/7)",
      "expression": "3\\frac{4}{9}:\\left(1\\frac{5}{9}-\\frac{4}{7}\\right)"
    },
    {
      "id": "math-oge-006-p069",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "4 7/8 : (2 3/4 + 1 10/19)",
      "expression": "4\\frac{7}{8}:\\left(2\\frac{3}{4}+1\\frac{10}{19}\\right)"
    },
    {
      "id": "math-oge-006-p070",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "1 1/12 : (1 13/18 - 2 5/9)",
      "expression": "1\\frac{1}{12}:\\left(1\\frac{13}{18}-2\\frac{5}{9}\\right)"
    },
    {
      "id": "math-oge-006-p071",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "3 1/2 : (1 4/15 + 2 9/10)",
      "expression": "3\\frac{1}{2}:\\left(1\\frac{4}{15}+2\\frac{9}{10}\\right)"
    },
    {
      "id": "math-oge-006-p072",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 2,
      "task_group": 2,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "4 1/4 : (2 7/10 - 3 1/8)",
      "expression": "4\\frac{1}{4}:\\left(2\\frac{7}{10}-3\\frac{1}{8}\\right)"
    },
    {
      "id": "math-oge-006-p073",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "10 · (1/5)^2 - 12 · 1/5",
      "expression": "10\\cdot\\left(\\frac{1}{5}\\right)^2-12\\cdot\\frac{1}{5}"
    },
    {
      "id": "math-oge-006-p074",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "8 · (1/4)^2 - 14 · 1/4",
      "expression": "8\\cdot\\left(\\frac{1}{4}\\right)^2-14\\cdot\\frac{1}{4}"
    },
    {
      "id": "math-oge-006-p075",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "21 · (1/7)^2 - 10 · 1/7",
      "expression": "21\\cdot\\left(\\frac{1}{7}\\right)^2-10\\cdot\\frac{1}{7}"
    },
    {
      "id": "math-oge-006-p076",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "6 · (1/3)^2 - 17 · 1/3",
      "expression": "6\\cdot\\left(\\frac{1}{3}\\right)^2-17\\cdot\\frac{1}{3}"
    },
    {
      "id": "math-oge-006-p077",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "18 · (1/9)^2 - 20 · 1/9",
      "expression": "18\\cdot\\left(\\frac{1}{9}\\right)^2-20\\cdot\\frac{1}{9}"
    },
    {
      "id": "math-oge-006-p078",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 3,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "15 · (1/5)^2 - 8 · 1/5",
      "expression": "15\\cdot\\left(\\frac{1}{5}\\right)^2-8\\cdot\\frac{1}{5}"
    },
    {
      "id": "math-oge-006-p079",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "2,1 / (6,6 - 2,4)",
      "expression": "\\frac{2,1}{6,6-2,4}"
    },
    {
      "id": "math-oge-006-p080",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "7,2 / (8,3 - 8,6)",
      "expression": "\\frac{7,2}{8,3-8,6}"
    },
    {
      "id": "math-oge-006-p081",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "9,2 / (0,5 - 2,8)",
      "expression": "\\frac{9,2}{0,5-2,8}"
    },
    {
      "id": "math-oge-006-p082",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "1,6 / (2,5 + 0,7)",
      "expression": "\\frac{1,6}{2,5+0,7}"
    },
    {
      "id": "math-oge-006-p083",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "5,6 / (1,9 + 2,1)",
      "expression": "\\frac{5,6}{1,9+2,1}"
    },
    {
      "id": "math-oge-006-p084",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "9,4 / (4,1 + 5,3)",
      "expression": "\\frac{9,4}{4,1+5,3}"
    },
    {
      "id": "math-oge-006-p085",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "(9,5 + 8,9) / 2,3",
      "expression": "\\frac{9,5+8,9}{2,3}"
    },
    {
      "id": "math-oge-006-p086",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "(6,8 - 4,7) / 1,4",
      "expression": "\\frac{6,8-4,7}{1,4}"
    },
    {
      "id": "math-oge-006-p087",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "(7,5 + 3,5) / 2,5",
      "expression": "\\frac{7,5+3,5}{2,5}"
    },
    {
      "id": "math-oge-006-p088",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "(6,9 - 4,1) / 0,2",
      "expression": "\\frac{6,9-4,1}{0,2}"
    },
    {
      "id": "math-oge-006-p089",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1,7 + 3,8) / 2,2",
      "expression": "\\frac{1,7+3,8}{2,2}"
    },
    {
      "id": "math-oge-006-p090",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "(7,2 - 6,1) / 2,2",
      "expression": "\\frac{7,2-6,1}{2,2}"
    },
    {
      "id": "math-oge-006-p091",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 13,
      "prompt": "Найдите значение выражения",
      "question_raw": "27 / (3 · 4,5)",
      "expression": "\\frac{27}{3\\cdot4,5}"
    },
    {
      "id": "math-oge-006-p092",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 14,
      "prompt": "Найдите значение выражения",
      "question_raw": "16 / (3,2 · 2)",
      "expression": "\\frac{16}{3,2\\cdot2}"
    },
    {
      "id": "math-oge-006-p093",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 15,
      "prompt": "Найдите значение выражения",
      "question_raw": "36 / (4 · 4,5)",
      "expression": "\\frac{36}{4\\cdot4,5}"
    },
    {
      "id": "math-oge-006-p094",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 16,
      "prompt": "Найдите значение выражения",
      "question_raw": "21 / (17,5 · 0,8)",
      "expression": "\\frac{21}{17,5\\cdot0,8}"
    },
    {
      "id": "math-oge-006-p095",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 17,
      "prompt": "Найдите значение выражения",
      "question_raw": "22 / (4,4 · 2,5)",
      "expression": "\\frac{22}{4,4\\cdot2,5}"
    },
    {
      "id": "math-oge-006-p096",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 18,
      "prompt": "Найдите значение выражения",
      "question_raw": "7 / (12,5 · 1,4)",
      "expression": "\\frac{7}{12,5\\cdot1,4}"
    },
    {
      "id": "math-oge-006-p097",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 19,
      "prompt": "Найдите значение выражения",
      "question_raw": "(8,4 · 1,3) / 0,7",
      "expression": "\\frac{8,4\\cdot1,3}{0,7}"
    },
    {
      "id": "math-oge-006-p098",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 20,
      "prompt": "Найдите значение выражения",
      "question_raw": "(4,4 · 0,3) / 6,6",
      "expression": "\\frac{4,4\\cdot0,3}{6,6}"
    },
    {
      "id": "math-oge-006-p099",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 21,
      "prompt": "Найдите значение выражения",
      "question_raw": "(4,8 · 0,4) / 0,6",
      "expression": "\\frac{4,8\\cdot0,4}{0,6}"
    },
    {
      "id": "math-oge-006-p100",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 22,
      "prompt": "Найдите значение выражения",
      "question_raw": "(8,8 · 0,8) / 4,4",
      "expression": "\\frac{8,8\\cdot0,8}{4,4}"
    },
    {
      "id": "math-oge-006-p101",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 23,
      "prompt": "Найдите значение выражения",
      "question_raw": "(0,3 · 7,5) / 0,5",
      "expression": "\\frac{0,3\\cdot7,5}{0,5}"
    },
    {
      "id": "math-oge-006-p102",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 4,
      "item_number": 24,
      "prompt": "Найдите значение выражения",
      "question_raw": "(5,6 · 0,3) / 0,8",
      "expression": "\\frac{5,6\\cdot0,3}{0,8}"
    },
    {
      "id": "math-oge-006-p103",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 1,
      "prompt": "Найдите значение выражения.",
      "question_raw": "0,9 / (1 + 1/5)",
      "expression": "\\frac{0,9}{1+\\frac{1}{5}}"
    },
    {
      "id": "math-oge-006-p104",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 2,
      "prompt": "Найдите значение выражения.",
      "question_raw": "2,6 / (1 - 1/14)",
      "expression": "\\frac{2,6}{1-\\frac{1}{14}}"
    },
    {
      "id": "math-oge-006-p105",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 3,
      "prompt": "Найдите значение выражения.",
      "question_raw": "1,3 / (1 + 1/12)",
      "expression": "\\frac{1,3}{1+\\frac{1}{12}}"
    },
    {
      "id": "math-oge-006-p106",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 4,
      "prompt": "Найдите значение выражения.",
      "question_raw": "1,2 / (1 - 1/3)",
      "expression": "\\frac{1,2}{1-\\frac{1}{3}}"
    },
    {
      "id": "math-oge-006-p107",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 5,
      "prompt": "Найдите значение выражения.",
      "question_raw": "0,6 / (1 + 1/2)",
      "expression": "\\frac{0,6}{1+\\frac{1}{2}}"
    },
    {
      "id": "math-oge-006-p108",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 5,
      "item_number": 6,
      "prompt": "Найдите значение выражения.",
      "question_raw": "0,8 / (1 - 1/9)",
      "expression": "\\frac{0,8}{1-\\frac{1}{9}}"
    },
    {
      "id": "math-oge-006-p109",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "-7 · (-4,7) - 6,8",
      "expression": "-7\\cdot(-4,7)-6,8"
    },
    {
      "id": "math-oge-006-p110",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "-13 · (-9,3) - 7,8",
      "expression": "-13\\cdot(-9,3)-7,8"
    },
    {
      "id": "math-oge-006-p111",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "-12 · (-8,6) - 9,4",
      "expression": "-12\\cdot(-8,6)-9,4"
    },
    {
      "id": "math-oge-006-p112",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "7,6 - 8 · (-5,2)",
      "expression": "7,6-8\\cdot(-5,2)"
    },
    {
      "id": "math-oge-006-p113",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "6,8 - 11 · (-6,1)",
      "expression": "6,8-11\\cdot(-6,1)"
    },
    {
      "id": "math-oge-006-p114",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "5,3 - 9 · (-4,4)",
      "expression": "5,3-9\\cdot(-4,4)"
    },
    {
      "id": "math-oge-006-p115",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,8 · (-10)^2 - 95",
      "expression": "-0,8\\cdot(-10)^2-95"
    },
    {
      "id": "math-oge-006-p116",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,7 · (-10)^3 - 20",
      "expression": "0,7\\cdot(-10)^3-20"
    },
    {
      "id": "math-oge-006-p117",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,2 · (-10)^2 + 55",
      "expression": "-0,2\\cdot(-10)^2+55"
    },
    {
      "id": "math-oge-006-p118",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,9 · (-10)^3 + 50",
      "expression": "0,9\\cdot(-10)^3+50"
    },
    {
      "id": "math-oge-006-p119",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,7 · (-10)^2 - 120",
      "expression": "-0,7\\cdot(-10)^2-120"
    },
    {
      "id": "math-oge-006-p120",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,6 · (-10)^3 + 50",
      "expression": "0,6\\cdot(-10)^3+50"
    },
    {
      "id": "math-oge-006-p121",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 13,
      "prompt": "Найдите значение выражения",
      "question_raw": "30 - 0,8 · (-10)^2",
      "expression": "30-0,8\\cdot(-10)^2"
    },
    {
      "id": "math-oge-006-p122",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 14,
      "prompt": "Найдите значение выражения",
      "question_raw": "80 + 0,4 · (-10)^3",
      "expression": "80+0,4\\cdot(-10)^3"
    },
    {
      "id": "math-oge-006-p123",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 15,
      "prompt": "Найдите значение выражения",
      "question_raw": "55 + 0,2 · (-10)^2",
      "expression": "55+0,2\\cdot(-10)^2"
    },
    {
      "id": "math-oge-006-p124",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 16,
      "prompt": "Найдите значение выражения",
      "question_raw": "-60 + 0,4 · (-10)^2",
      "expression": "-60+0,4\\cdot(-10)^2"
    },
    {
      "id": "math-oge-006-p125",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 17,
      "prompt": "Найдите значение выражения",
      "question_raw": "-80 + 0,3 · (-10)^3",
      "expression": "-80+0,3\\cdot(-10)^3"
    },
    {
      "id": "math-oge-006-p126",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 3,
      "task_group": 6,
      "item_number": 18,
      "prompt": "Найдите значение выражения",
      "question_raw": "-45 + 0,5 · (-10)^2",
      "expression": "-45+0,5\\cdot(-10)^2"
    },
    {
      "id": "math-oge-006-p127",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2,6 · 10^-2) · (9 · 10^-3)",
      "expression": "(2,6\\cdot10^{-2})\\cdot(9\\cdot10^{-3})"
    },
    {
      "id": "math-oge-006-p128",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1,6 · 10^-5) · (6 · 10^-2)",
      "expression": "(1,6\\cdot10^{-5})\\cdot(6\\cdot10^{-2})"
    },
    {
      "id": "math-oge-006-p129",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1,7 · 10^-3) · (5 · 10^-4)",
      "expression": "(1,7\\cdot10^{-3})\\cdot(5\\cdot10^{-4})"
    },
    {
      "id": "math-oge-006-p130",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2,1 · 10^-2) · (2 · 10^-2)",
      "expression": "(2,1\\cdot10^{-2})\\cdot(2\\cdot10^{-2})"
    },
    {
      "id": "math-oge-006-p131",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2,2 · 10^-2) · (3 · 10^-4)",
      "expression": "(2,2\\cdot10^{-2})\\cdot(3\\cdot10^{-4})"
    },
    {
      "id": "math-oge-006-p132",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "(1,2 · 10^-3) · (7 · 10^-2)",
      "expression": "(1,2\\cdot10^{-3})\\cdot(7\\cdot10^{-2})"
    },
    {
      "id": "math-oge-006-p133",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 7,
      "prompt": "Найдите значение выражения",
      "question_raw": "(7 · 10^3)^2 · (16 · 10^-4)",
      "expression": "(7\\cdot10^{3})^2\\cdot(16\\cdot10^{-4})"
    },
    {
      "id": "math-oge-006-p134",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 8,
      "prompt": "Найдите значение выражения",
      "question_raw": "(2 · 10^2)^4 · (19 · 10^-6)",
      "expression": "(2\\cdot10^{2})^4\\cdot(19\\cdot10^{-6})"
    },
    {
      "id": "math-oge-006-p135",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 9,
      "prompt": "Найдите значение выражения",
      "question_raw": "(8 · 10^2)^2 · (3 · 10^-2)",
      "expression": "(8\\cdot10^{2})^2\\cdot(3\\cdot10^{-2})"
    },
    {
      "id": "math-oge-006-p136",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 10,
      "prompt": "Найдите значение выражения",
      "question_raw": "(9 · 10^-2)^2 · (11 · 10^5)",
      "expression": "(9\\cdot10^{-2})^2\\cdot(11\\cdot10^{5})"
    },
    {
      "id": "math-oge-006-p137",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 11,
      "prompt": "Найдите значение выражения",
      "question_raw": "(16 · 10^-2)^2 · (13 · 10^4)",
      "expression": "(16\\cdot10^{-2})^2\\cdot(13\\cdot10^{4})"
    },
    {
      "id": "math-oge-006-p138",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 7,
      "item_number": 12,
      "prompt": "Найдите значение выражения",
      "question_raw": "(14 · 10^-2)^2 · (12 · 10^3)",
      "expression": "(14\\cdot10^{-2})^2\\cdot(12\\cdot10^{3})"
    },
    {
      "id": "math-oge-006-p139",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,7 · (-10)^3 - 4 · (-10)^2 - 63",
      "expression": "0,7\\cdot(-10)^3-4\\cdot(-10)^2-63"
    },
    {
      "id": "math-oge-006-p140",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,4 · (-10)^4 + 3 · (-10)^2 - 98",
      "expression": "-0,4\\cdot(-10)^4+3\\cdot(-10)^2-98"
    },
    {
      "id": "math-oge-006-p141",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,8 · (-10)^4 + 3 · (-10)^3 + 78",
      "expression": "0,8\\cdot(-10)^4+3\\cdot(-10)^3+78"
    },
    {
      "id": "math-oge-006-p142",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,7 · (-10)^4 - 8 · (-10)^2 - 26",
      "expression": "-0,7\\cdot(-10)^4-8\\cdot(-10)^2-26"
    },
    {
      "id": "math-oge-006-p143",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,4 · (-10)^3 + 7 · (-10)^2 + 64",
      "expression": "0,4\\cdot(-10)^3+7\\cdot(-10)^2+64"
    },
    {
      "id": "math-oge-006-p144",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 8,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,3 · (-10)^4 + 4 · (-10)^2 - 59",
      "expression": "-0,3\\cdot(-10)^4+4\\cdot(-10)^2-59"
    },
    {
      "id": "math-oge-006-p145",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,0006 · 6 · 600000",
      "expression": "0,0006\\cdot6\\cdot600000"
    },
    {
      "id": "math-oge-006-p146",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,007 · 0,7 · 70",
      "expression": "0,007\\cdot0,7\\cdot70"
    },
    {
      "id": "math-oge-006-p147",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,0008 · 0,008 · 80000",
      "expression": "0,0008\\cdot0,008\\cdot80000"
    },
    {
      "id": "math-oge-006-p148",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,005 · 0,5 · 50",
      "expression": "0,005\\cdot0,5\\cdot50"
    },
    {
      "id": "math-oge-006-p149",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,003 · 0,0003 · 300",
      "expression": "0,003\\cdot0,0003\\cdot300"
    },
    {
      "id": "math-oge-006-p150",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 9,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,004 · 0,04 · 40000",
      "expression": "0,004\\cdot0,04\\cdot40000"
    },
    {
      "id": "math-oge-006-p151",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,2 · (-7)^4 - 1 · (-7)^3 - 13",
      "expression": "-0,2\\cdot(-7)^4-1\\cdot(-7)^3-13"
    },
    {
      "id": "math-oge-006-p152",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "-0,9 · (-2)^3 + 2,9 · (-2)^2 - 22",
      "expression": "-0,9\\cdot(-2)^3+2,9\\cdot(-2)^2-22"
    },
    {
      "id": "math-oge-006-p153",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,1 · (-8)^3 + 0,2 · (-8)^2 - 25",
      "expression": "0,1\\cdot(-8)^3+0,2\\cdot(-8)^2-25"
    },
    {
      "id": "math-oge-006-p154",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,5 · (-6)^4 + 2 · (-6)^2 - 30",
      "expression": "0,5\\cdot(-6)^4+2\\cdot(-6)^2-30"
    },
    {
      "id": "math-oge-006-p155",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 5,
      "prompt": "Найдите значение выражения",
      "question_raw": "-1,1 · (-3)^4 - 0,9 · (-3)^3 - 15",
      "expression": "-1,1\\cdot(-3)^4-0,9\\cdot(-3)^3-15"
    },
    {
      "id": "math-oge-006-p156",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 10,
      "item_number": 6,
      "prompt": "Найдите значение выражения",
      "question_raw": "0,2 · (-4)^3 + 3 · (-4)^2 - 17",
      "expression": "0,2\\cdot(-4)^3+3\\cdot(-4)^2-17"
    },
    {
      "id": "math-oge-006-p157",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 1,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 1·10^-1 + 7·10^-3 + 2·10^-4.",
      "expression": "1\\cdot10^{-1}+7\\cdot10^{-3}+2\\cdot10^{-4}"
    },
    {
      "id": "math-oge-006-p158",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 2,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 9·10^1 + 3·10^-3 + 8·10^-4.",
      "expression": "9\\cdot10^{1}+3\\cdot10^{-3}+8\\cdot10^{-4}"
    },
    {
      "id": "math-oge-006-p159",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 3,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 2·10^0 + 6·10^-1 + 4·10^-3.",
      "expression": "2\\cdot10^{0}+6\\cdot10^{-1}+4\\cdot10^{-3}"
    },
    {
      "id": "math-oge-006-p160",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 4,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 8·10^0 + 9·10^-2 + 3·10^-4.",
      "expression": "8\\cdot10^{0}+9\\cdot10^{-2}+3\\cdot10^{-4}"
    },
    {
      "id": "math-oge-006-p161",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 5,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 6·10^1 + 7·10^-2 + 5·10^-3.",
      "expression": "6\\cdot10^{1}+7\\cdot10^{-2}+5\\cdot10^{-3}"
    },
    {
      "id": "math-oge-006-p162",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 2. ФИПИ. Расширенная версия",
      "page": 4,
      "task_group": 11,
      "item_number": 6,
      "prompt": null,
      "question_raw": "Запишите десятичную дробь, равную сумме 5·10^-1 + 6·10^-2 + 4·10^-4.",
      "expression": "5\\cdot10^{-1}+6\\cdot10^{-2}+4\\cdot10^{-4}"
    },
    {
      "id": "math-oge-006-p163",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/17 + 1 1/4) : 1/34",
      "expression": "\\left(\\frac{1}{17}+1\\frac{1}{4}\\right):\\frac{1}{34}"
    },
    {
      "id": "math-oge-006-p164",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 2,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(3/4 - 2 9/10) : 1/12",
      "expression": "\\left(\\frac{3}{4}-2\\frac{9}{10}\\right):\\frac{1}{12}"
    },
    {
      "id": "math-oge-006-p165",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 3,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(7/9 + 1 4/5) : 1/18",
      "expression": "\\left(\\frac{7}{9}+1\\frac{4}{5}\\right):\\frac{1}{18}"
    },
    {
      "id": "math-oge-006-p166",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 4,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(4/11 - 2 1/4) : 1/22",
      "expression": "\\left(\\frac{4}{11}-2\\frac{1}{4}\\right):\\frac{1}{22}"
    },
    {
      "id": "math-oge-006-p167",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 5,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(13/24 + 1/15) : 1/24",
      "expression": "\\left(\\frac{13}{24}+\\frac{1}{15}\\right):\\frac{1}{24}"
    },
    {
      "id": "math-oge-006-p168",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 1,
      "item_number": 6,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(15/26 - 2 3/4) : 1/26",
      "expression": "\\left(\\frac{15}{26}-2\\frac{3}{4}\\right):\\frac{1}{26}"
    },
    {
      "id": "math-oge-006-p169",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 1,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/20 + 1/12) / (1/27)",
      "expression": "\\left(\\frac{1}{20}+\\frac{1}{12}\\right):\\frac{1}{27}"
    },
    {
      "id": "math-oge-006-p170",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 2,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/12 - 1/21) / (1/70)",
      "expression": "\\left(\\frac{1}{12}-\\frac{1}{21}\\right):\\frac{1}{70}"
    },
    {
      "id": "math-oge-006-p171",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 3,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/18 + 1/45) / (5/27)",
      "expression": "\\left(\\frac{1}{18}+\\frac{1}{45}\\right):\\frac{5}{27}"
    },
    {
      "id": "math-oge-006-p172",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 4,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/72 - 1/88) / (5/99)",
      "expression": "\\left(\\frac{1}{72}-\\frac{1}{88}\\right):\\frac{5}{99}"
    },
    {
      "id": "math-oge-006-p173",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 5,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/28 + 1/42) / (1/21)",
      "expression": "\\left(\\frac{1}{28}+\\frac{1}{42}\\right):\\frac{1}{21}"
    },
    {
      "id": "math-oge-006-p174",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 2,
      "item_number": 6,
      "prompt": "Найдите значение выражения.",
      "question_raw": "(1/40 - 1/65) / (1/78)",
      "expression": "\\left(\\frac{1}{40}-\\frac{1}{65}\\right):\\frac{1}{78}"
    },
    {
      "id": "math-oge-006-p175",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 3,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "1,9 - 3,5 · 7,2",
      "expression": "1,9-3,5\\cdot7,2"
    },
    {
      "id": "math-oge-006-p176",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 3,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "-9,2 - 0,4 · 6,5",
      "expression": "-9,2-0,4\\cdot6,5"
    },
    {
      "id": "math-oge-006-p177",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 3,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "5,1 + 2,8 · 2,5",
      "expression": "5,1+2,8\\cdot2,5"
    },
    {
      "id": "math-oge-006-p178",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 3,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "-3,6 + 7,2 · 1,5",
      "expression": "-3,6+7,2\\cdot1,5"
    },
    {
      "id": "math-oge-006-p179",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 4,
      "item_number": 1,
      "prompt": "Найдите значение выражения",
      "question_raw": "3/16 : (-5/56) + 3,8",
      "expression": "\\frac{3}{16}:\\left(-\\frac{5}{56}\\right)+3,8"
    },
    {
      "id": "math-oge-006-p180",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 4,
      "item_number": 2,
      "prompt": "Найдите значение выражения",
      "question_raw": "7/18 : (-10/27) - 2,4",
      "expression": "\\frac{7}{18}:\\left(-\\frac{10}{27}\\right)-2,4"
    },
    {
      "id": "math-oge-006-p181",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 4,
      "item_number": 3,
      "prompt": "Найдите значение выражения",
      "question_raw": "-14/23 : 35/46 + 2,9",
      "expression": "-\\frac{14}{23}:\\frac{35}{46}+2,9"
    },
    {
      "id": "math-oge-006-p182",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 4,
      "item_number": 4,
      "prompt": "Найдите значение выражения",
      "question_raw": "-15/58 : 3/29 - 5,63",
      "expression": "-\\frac{15}{58}:\\frac{3}{29}-5,63"
    },
    {
      "id": "math-oge-006-p183",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 1,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 2/5 + 3/11.",
      "expression": "\\frac{2}{5}+\\frac{3}{11}"
    },
    {
      "id": "math-oge-006-p184",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 2,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 7/13 + 1/3.",
      "expression": "\\frac{7}{13}+\\frac{1}{3}"
    },
    {
      "id": "math-oge-006-p185",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 3,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 5/7 + 4/21.",
      "expression": "\\frac{5}{7}+\\frac{4}{21}"
    },
    {
      "id": "math-oge-006-p186",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 4,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1/45 + 5/9.",
      "expression": "\\frac{1}{45}+\\frac{5}{9}"
    },
    {
      "id": "math-oge-006-p187",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 5,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 3/20 + 7/36.",
      "expression": "\\frac{3}{20}+\\frac{7}{36}"
    },
    {
      "id": "math-oge-006-p188",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 6,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 2/45 + 9/35.",
      "expression": "\\frac{2}{45}+\\frac{9}{35}"
    },
    {
      "id": "math-oge-006-p189",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 7,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 3 1/12 - 2 1/4.",
      "expression": "3\\frac{1}{12}-2\\frac{1}{4}"
    },
    {
      "id": "math-oge-006-p190",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 8,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 5 1/15 - 4 2/5.",
      "expression": "5\\frac{1}{15}-4\\frac{2}{5}"
    },
    {
      "id": "math-oge-006-p191",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 9,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 7 1/18 - 6 13/14.",
      "expression": "7\\frac{1}{18}-6\\frac{13}{14}"
    },
    {
      "id": "math-oge-006-p192",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 10,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 9 2/15 - 8 32/33.",
      "expression": "9\\frac{2}{15}-8\\frac{32}{33}"
    },
    {
      "id": "math-oge-006-p193",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 11,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 2 3/28 - 1 17/36.",
      "expression": "2\\frac{3}{28}-1\\frac{17}{36}"
    },
    {
      "id": "math-oge-006-p194",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 5,
      "task_group": 5,
      "item_number": 12,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 6 2/21 - 5 31/33.",
      "expression": "6\\frac{2}{21}-5\\frac{31}{33}"
    },
    {
      "id": "math-oge-006-p195",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 1,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1 19/29 · 7/48.",
      "expression": "1\\frac{19}{29}\\cdot\\frac{7}{48}"
    },
    {
      "id": "math-oge-006-p196",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 2,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1 13/58 · 9/71.",
      "expression": "1\\frac{13}{58}\\cdot\\frac{9}{71}"
    },
    {
      "id": "math-oge-006-p197",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 3,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1 15/34 · 17/49.",
      "expression": "1\\frac{15}{34}\\cdot\\frac{17}{49}"
    },
    {
      "id": "math-oge-006-p198",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 4,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1 11/45 · 25/56.",
      "expression": "1\\frac{11}{45}\\cdot\\frac{25}{56}"
    },
    {
      "id": "math-oge-006-p199",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 5,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 7/12 : 2 1/4.",
      "expression": "\\frac{7}{12}:2\\frac{1}{4}"
    },
    {
      "id": "math-oge-006-p200",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 6,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 9/14 : 1 4/7.",
      "expression": "\\frac{9}{14}:1\\frac{4}{7}"
    },
    {
      "id": "math-oge-006-p201",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 7,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 8/11 : 2 2/5.",
      "expression": "\\frac{8}{11}:2\\frac{2}{5}"
    },
    {
      "id": "math-oge-006-p202",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 8,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 6/13 : 1 1/8.",
      "expression": "\\frac{6}{13}:1\\frac{1}{8}"
    },
    {
      "id": "math-oge-006-p203",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 9,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1/15 + 4 4/5 · 2/21.",
      "expression": "\\frac{1}{15}+4\\frac{4}{5}\\cdot\\frac{2}{21}"
    },
    {
      "id": "math-oge-006-p204",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 10,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 3/20 + 3 3/4 · 1/27.",
      "expression": "\\frac{3}{20}+3\\frac{3}{4}\\cdot\\frac{1}{27}"
    },
    {
      "id": "math-oge-006-p205",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 11,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 1/14 + 2 1/12 · 2/15.",
      "expression": "\\frac{1}{14}+2\\frac{1}{12}\\cdot\\frac{2}{15}"
    },
    {
      "id": "math-oge-006-p206",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 12,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 10/21 + 2 2/15 · 3/14.",
      "expression": "\\frac{10}{21}+2\\frac{2}{15}\\cdot\\frac{3}{14}"
    },
    {
      "id": "math-oge-006-p207",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 13,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 4 25/27 · 3/38 - 5/22.",
      "expression": "4\\frac{25}{27}\\cdot\\frac{3}{38}-\\frac{5}{22}"
    },
    {
      "id": "math-oge-006-p208",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 14,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 6 24/35 · 1/9 - 4/15.",
      "expression": "6\\frac{24}{35}\\cdot\\frac{1}{9}-\\frac{4}{15}"
    },
    {
      "id": "math-oge-006-p209",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 15,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 2 39/40 · 2/7 - 3/28.",
      "expression": "2\\frac{39}{40}\\cdot\\frac{2}{7}-\\frac{3}{28}"
    },
    {
      "id": "math-oge-006-p210",
      "subject": "Математика",
      "number": 6,
      "title": "Дроби и степени",
      "block": "Блок 3. Типовые экзаменационные варианты",
      "page": 6,
      "task_group": 6,
      "item_number": 16,
      "prompt": null,
      "question_raw": "Найдите значение выражения. Представьте результат в виде несократимой обыкновенной дроби. В ответ запишите числитель этой дроби. Выражение: 5 25/28 · 4/45 - 5/39.",
      "expression": "5\\frac{25}{28}\\cdot\\frac{4}{45}-\\frac{5}{39}"
    }
  ]
}
);
