window.EGE_TASKS = window.EGE_TASKS || [];
window.EGE_TASKS.push(
  {
    id: "math-ege-base-016-p001",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 1,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{8^{2,5}\\cdot2^{-1,5}}{4^2}",
    answer: "4"
  },
  {
    id: "math-ege-base-016-p002",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 2,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{27^{1,4}\\cdot3^{-0,2}}{9^{1,5}}",
    answer: "3"
  },
  {
    id: "math-ege-base-016-p003",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 3,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{16^{1,8}\\cdot2^{-2,2}}{8}",
    answer: "4"
  },
  {
    id: "math-ege-base-016-p004",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 4,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{25^{2,2}\\cdot5^{-1,4}}{125}",
    answer: "1"
  },
  {
    id: "math-ege-base-016-p005",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 5,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{49^{1,5}\\cdot7^{-1}}{7}",
    answer: "7"
  },
  {
    id: "math-ege-base-016-p006",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 6,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{32^{1,4}\\cdot2^{-1}}{4^2}",
    answer: "4"
  },
  {
    id: "math-ege-base-016-p007",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 7,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{81^{1,25}\\cdot3^{-2}}{9}",
    answer: "3"
  },
  {
    id: "math-ege-base-016-p008",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 8,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{64^{1,2}\\cdot2^{-1,2}}{8}",
    answer: "8"
  },
  {
    id: "math-ege-base-016-p009",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 9,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{125^{1,6}\\cdot5^{-1,8}}{25^{1,5}}",
    answer: "1"
  },
  {
    id: "math-ege-base-016-p010",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 10,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{36^{2,5}\\cdot6^{-2}}{216}",
    answer: "1"
  },
  {
    id: "math-ege-base-016-p011",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 11,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{2^{3,5}\\cdot3^{4,5}}{6^{3,5}}",
    answer: "3"
  },
  {
    id: "math-ege-base-016-p012",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 12,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{4^{2,7}\\cdot8^{1,2}}{2^8}",
    answer: "2"
  },
  {
    id: "math-ege-base-016-p013",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 13,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{9^{1,8}\\cdot27^{0,8}}{3^5}",
    answer: "3"
  },
  {
    id: "math-ege-base-016-p014",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 14,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{25^{1,4}\\cdot125^{0,4}}{5^4}",
    answer: "1"
  },
  {
    id: "math-ege-base-016-p015",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 15,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{16^{1,25}\\cdot8^{0,5}}{2^{5,5}}",
    answer: "2"
  },
  {
    id: "math-ege-base-016-p016",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 16,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{a^{14}\\cdot(b^4)^3}{(ab)^{12}},\\ a=4,\\ b=\\sqrt{2}",
    answer: "16"
  },
  {
    id: "math-ege-base-016-p017",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 17,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{x^{1,36}\\cdot x^{3,29}}{x^{0,65}},\\ x=2",
    answer: "16"
  },
  {
    id: "math-ege-base-016-p018",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 18,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{y^{2,75}\\cdot y^{1,5}}{y^{0,25}},\\ y=3",
    answer: "81"
  },
  {
    id: "math-ege-base-016-p019",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 19,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{a^9\\cdot(b^3)^2}{(ab)^6},\\ a=2,\\ b=\\sqrt{5}",
    answer: "8"
  },
  {
    id: "math-ege-base-016-p020",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 20,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{p^8\\cdot(q^2)^3}{(pq)^6},\\ p=5,\\ q=\\sqrt{3}",
    answer: "25"
  },
  {
    id: "math-ege-base-016-p021",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 21,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{m^{12}\\cdot(n^5)^2}{(mn)^{10}},\\ m=3,\\ n=\\sqrt{2}",
    answer: "9"
  },
  {
    id: "math-ege-base-016-p022",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 22,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{x^{4,7}\\cdot x^{2,8}}{x^{1,5}},\\ x=2",
    answer: "64"
  },
  {
    id: "math-ege-base-016-p023",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 23,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{t^{5,4}\\cdot t^{1,9}}{t^{2,3}},\\ t=3",
    answer: "243"
  },
  {
    id: "math-ege-base-016-p024",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 24,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{a^{11}\\cdot(b^2)^4}{(ab)^8},\\ a=4,\\ b=\\sqrt{7}",
    answer: "64"
  },
  {
    id: "math-ege-base-016-p025",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 25,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{c^{15}\\cdot(d^3)^4}{(cd)^{12}},\\ c=2,\\ d=\\sqrt{3}",
    answer: "8"
  },
  {
    id: "math-ege-base-016-p026",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 26,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{z^{6,25}\\cdot z^{2,5}}{z^{0,75}},\\ z=2",
    answer: "256"
  },
  {
    id: "math-ege-base-016-p027",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 27,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{k^{3,6}\\cdot k^{4,9}}{k^{1,5}},\\ k=2",
    answer: "128"
  },
  {
    id: "math-ege-base-016-p028",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 28,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{a^{10}\\cdot(b^6)^2}{(ab)^{12}},\\ a=2,\\ b=\\sqrt{5}",
    answer: "1/4"
  },
  {
    id: "math-ege-base-016-p029",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 29,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{u^7\\cdot(v^4)^2}{(uv)^8},\\ u=4,\\ v=\\sqrt{3}",
    answer: "1/4"
  },
  {
    id: "math-ege-base-016-p030",
    subject: "Математика",
    ege_level: "base",
    number: 16,
    title: "Степени",
    topic: "Преобразование степеней",
    prototype: 30,
    task_group: 1,
    layout: "one-column",
    prompt: "Найдите значение выражения.",
    expression: "\\frac{r^{13}\\cdot(s^2)^5}{(rs)^{10}},\\ r=3,\\ s=\\sqrt{2}",
    answer: "27"
  }
);
