window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 10,
  "level": "basic",
  "section": "algebra",
  "number": 1,
  "title": "Алгебра",
  "topic": "Базовый уровень",
  "block": "МЦКО 10 класс · Алгебра · Базовый уровень",
  "total_tasks": 9,
  "items": [
    {
      "id": "math-mcko-10-basic-algebra-001",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 1,
      "title": "Проценты",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "В одной из школ 30 % учеников посещают спортивные секции. Остальные школьники спортом не увлекаются. Среди тех, кто посещает секции, 80 % принимают участие в городских соревнованиях. Сколько процентов от всех учеников школы участвуют в соревнованиях?",
      "answer": "24",
      "solution": "30 % учеников посещают секции, из них 80 % участвуют в соревнованиях. 0,3 · 0,8 = 0,24, то есть 24 % всех учеников."
    },
    {
      "id": "math-mcko-10-basic-algebra-002",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите значение выражения при b = 81.",
      "expression": "\\frac{b^6\\cdot b^{-\\frac{11}{4}}}{b^3}",
      "answer": "3",
      "solution": "Соберем степени с одинаковым основанием: 6 - 11/4 - 3 = 1/4. Получаем b^(1/4). При b = 81 значение равно 3."
    },
    {
      "id": "math-mcko-10-basic-algebra-003",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Вычислите:",
      "expression": "\\sin(-30^\\circ)+\\cos^2 45^\\circ",
      "answer": "0",
      "solution": "sin(-30°) = -1/2, cos 45° = √2/2, поэтому cos²45° = 1/2. Сумма равна 0."
    },
    {
      "id": "math-mcko-10-basic-algebra-004",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Геометрическая прогрессия",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите сумму бесконечно убывающей геометрической прогрессии.",
      "expression": "27,\\ 9,\\ 3,\\ 1,\\ \\frac{1}{3},\\ldots",
      "answer": "40,5",
      "solution": "Первый член равен 27, знаменатель прогрессии q = 1/3. Сумма равна 27 / (1 - 1/3) = 40,5."
    },
    {
      "id": "math-mcko-10-basic-algebra-005",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 5,
      "title": "Графики функций",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "На рисунке изображены графики функций f(x) = 2x - 1 и g(x) = ax^2 + bx + c, которые пересекаются в точках A и B. Найдите ординату точки B.",
      "image": "mcko-tasks/grade-10/images/algebra-basic-functions-intersection.svg",
      "image_alt": "Графики линейной функции и параболы с точками пересечения A и B",
      "answer": "-5",
      "solution": "По графику точка B имеет координаты (-2; -5). Ордината точки B равна -5."
    },
    {
      "id": "math-mcko-10-basic-algebra-006",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 6,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Найдите значение.",
      "expression": "\\operatorname{ctg}\\alpha,\\ \\cos\\alpha=-0{,}6,\\ \\frac{\\pi}{2}<\\alpha<\\pi",
      "answer": "-0,75",
      "solution": "Во второй четверти синус положителен. Если cos α = -0,6, то sin α = 0,8. Тогда ctg α = cos α / sin α = -0,6 / 0,8 = -0,75."
    },
    {
      "id": "math-mcko-10-basic-algebra-007",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 7,
      "title": "Тригонометрическое уравнение",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите уравнение. Запишите в ответ количество корней этого уравнения, принадлежащих отрезку [4; 14].",
      "expression": "\\sin^2 x=\\sin x",
      "answer": "4",
      "solution": "sin²x = sin x, значит sin x = 0 или sin x = 1. На отрезке [4; 14] подходят 2π, 3π, 4π и 5π/2. Всего 4 корня."
    },
    {
      "id": "math-mcko-10-basic-algebra-008",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 8,
      "title": "Рациональное неравенство",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите неравенство. В ответ запишите наибольшее целое отрицательное число полученного решения.",
      "expression": "\\frac{2x^2-x-1}{4x+5}\\le 0",
      "answer": "-2",
      "solution": "Нули числителя: -1/2 и 1, нуль знаменателя: -5/4. Решение: (-∞; -5/4) ∪ [-1/2; 1]. Наибольшее целое отрицательное число из решения равно -2."
    },
    {
      "id": "math-mcko-10-basic-algebra-009",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 9,
      "title": "Функция с модулем",
      "topic": "Алгебра",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "question_text": "Дана функция f(x) = ||x| - 5| - 2. При каких значениях c уравнение f(x) = c имеет ровно три решения?",
      "answer": "3",
      "solution": "Пусть ||x| - 5| = c + 2. Ровно три решения получаются при c + 2 = 5: тогда |x| = 0 или |x| = 10. Значит, c = 3."
    }
  ]
});
