window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 10,
  "level": "basic",
  "section": "algebra",
  "number": 4,
  "title": "Алгебра",
  "topic": "Базовый уровень",
  "block": "МЦКО 10 класс · Алгебра · Базовый уровень",
  "total_tasks": 40,
  "items": [
    {
      "id": "math-mcko-10-basic-algebra-004-001",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "Вычислите сумму первых 15 членов арифметической прогрессии, заданной формулой \\(a_n=-7+4n\\).",
      "answer": "375",
      "solution": "Первый член: a₁ = -7 + 4 = -3. Пятнадцатый член: a₁₅ = -7 + 4·15 = 53. S₁₅ = 15·(-3 + 53)/2 = 375."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-002",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 2,
      "prompt": "Решите задачу.",
      "intro": "Найдите восьмой член арифметической прогрессии, если её третий член равен 11, а одиннадцатый равен 43.",
      "answer": "31",
      "solution": "a₁₁ - a₃ = 8d = 43 - 11 = 32, поэтому d = 4. Тогда a₈ = a₃ + 5d = 11 + 20 = 31."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-003",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 3,
      "prompt": "Решите задачу.",
      "intro": "Найдите разность арифметической прогрессии, если её первый член равен 7, а девятый равен 39.",
      "answer": "4",
      "solution": "a₉ = a₁ + 8d. Получаем 39 = 7 + 8d, откуда d = 4."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-004",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 4,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых 10 членов арифметической прогрессии равна 245, а первый член равен 2. Найдите разность прогрессии.",
      "answer": "5",
      "solution": "S₁₀ = 10/2·(2a₁ + 9d). 245 = 5·(4 + 9d), откуда 49 = 4 + 9d и d = 5."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-005",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 5,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 20 членов арифметической прогрессии 3, 7, 11, …",
      "answer": "820",
      "solution": "a₁ = 3, d = 4. S₂₀ = 20/2·(2·3 + 19·4) = 10·82 = 820."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-006",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 6,
      "prompt": "Решите задачу.",
      "intro": "В арифметической прогрессии первый член равен 12, разность равна -3. Найдите сумму первых 9 членов.",
      "answer": "0",
      "solution": "a₉ = 12 + 8·(-3) = -12. S₉ = 9·(12 - 12)/2 = 0."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-007",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 7,
      "prompt": "Решите задачу.",
      "intro": "Найдите количество членов арифметической прогрессии 5, 9, 13, …, если её последний член равен 81.",
      "answer": "20",
      "solution": "81 = 5 + (n - 1)·4. Тогда 76 = 4(n - 1), n - 1 = 19, n = 20."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-008",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 8,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых 12 членов арифметической прогрессии равна 456, а её двенадцатый член равен 71. Найдите первый член.",
      "answer": "5",
      "solution": "456 = 12·(a₁ + 71)/2 = 6(a₁ + 71). Тогда a₁ + 71 = 76, откуда a₁ = 5."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-009",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 9,
      "prompt": "Решите задачу.",
      "intro": "Найдите шестой член арифметической прогрессии, если сумма её первого и одиннадцатого членов равна 50.",
      "answer": "25",
      "solution": "В арифметической прогрессии a₁ + a₁₁ = 2a₆. Поэтому a₆ = 50/2 = 25."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-010",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 10,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых 6 членов арифметической прогрессии равна 90, а разность равна 4. Найдите первый член.",
      "answer": "5",
      "solution": "90 = 6/2·(2a₁ + 5·4) = 3(2a₁ + 20). Получаем 30 = 2a₁ + 20, значит a₁ = 5."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-011",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 11,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 8 членов геометрической прогрессии 3, 6, 12, …",
      "answer": "765",
      "solution": "a₁ = 3, q = 2. S₈ = 3·(2⁸ - 1)/(2 - 1) = 3·255 = 765."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-012",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 12,
      "prompt": "Решите задачу.",
      "intro": "Найдите пятый член геометрической прогрессии, если первый член равен 2, а знаменатель равен 3.",
      "answer": "162",
      "solution": "b₅ = b₁q⁴ = 2·3⁴ = 2·81 = 162."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-013",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 13,
      "prompt": "Решите задачу.",
      "intro": "Найдите знаменатель геометрической прогрессии, если её первый член равен 5, а четвёртый равен 135.",
      "answer": "3",
      "solution": "b₄ = b₁q³. 135 = 5q³, значит q³ = 27 и q = 3."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-014",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 14,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 6 членов геометрической прогрессии 64, 32, 16, …",
      "answer": "126",
      "solution": "a₁ = 64, q = 1/2. S₆ = 64·(1 - (1/2)⁶)/(1 - 1/2) = 126."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-015",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 15,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму бесконечно убывающей геометрической прогрессии 18, 6, 2, …",
      "answer": "27",
      "solution": "q = 1/3. S = b₁/(1 - q) = 18/(1 - 1/3) = 27."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-016",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 16,
      "prompt": "Решите задачу.",
      "intro": "Найдите первый член бесконечно убывающей геометрической прогрессии, если её сумма равна 20, а знаменатель равен 0,25.",
      "answer": "15",
      "solution": "S = b₁/(1 - q). Тогда b₁ = 20·(1 - 0,25) = 15."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-017",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 17,
      "prompt": "Решите задачу.",
      "intro": "Найдите знаменатель бесконечно убывающей геометрической прогрессии, если её первый член равен 12, а сумма равна 16.",
      "answer": "0.25",
      "solution": "16 = 12/(1 - q). Тогда 1 - q = 12/16 = 0,75, значит q = 0,25."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-018",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 18,
      "prompt": "Решите задачу.",
      "intro": "Сумма первого и третьего членов геометрической прогрессии равна 20, а сумма второго и четвёртого равна 40. Найдите знаменатель прогрессии.",
      "answer": "2",
      "solution": "b₁ + b₃ = b₁(1 + q²) = 20, а b₂ + b₄ = b₁q(1 + q²) = 40. Делим второе равенство на первое: q = 2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-019",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 19,
      "prompt": "Решите задачу.",
      "intro": "В геометрической прогрессии b₁ = 81, q = 1/3. Найдите шестой член.",
      "answer": "0.3333333333",
      "solution": "b₆ = 81·(1/3)⁵ = 81/243 = 1/3."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-020",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 20,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 5 членов геометрической прогрессии 2, -4, 8, …",
      "answer": "22",
      "solution": "a₁ = 2, q = -2. S₅ = 2·(1 - (-2)⁵)/(1 - (-2)) = 2·33/3 = 22."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-021",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 21,
      "prompt": "Решите задачу.",
      "intro": "Арифметическая прогрессия 2, 5, 8, … и геометрическая прогрессия 2, 4, 8, … имеют по 20 членов. Сколько одинаковых членов содержат обе прогрессии?",
      "answer": "2",
      "solution": "Общие члены среди первых 20 членов обеих прогрессий: 2 и 8. Следующий член геометрической прогрессии 16 не входит в арифметическую прогрессию вида 2 + 3k."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-022",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 22,
      "prompt": "Решите задачу.",
      "intro": "Арифметическая прогрессия 4, 7, 10, … и геометрическая прогрессия 4, 8, 16, … имеют по 30 членов. Сколько одинаковых членов содержат обе прогрессии?",
      "answer": "1",
      "solution": "Числа арифметической прогрессии имеют вид 4 + 3k. Среди степеней двойки, умноженных на 4, только 4 даёт остаток 1 по модулю 3. Значит общий член один."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-023",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 23,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 7 членов геометрической прогрессии 48, 24, 12, …",
      "answer": "95.25",
      "solution": "a₁ = 48, q = 1/2. S₇ = 48·(1 - (1/2)⁷)/(1 - 1/2) = 95,25."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-024",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 24,
      "prompt": "Решите задачу.",
      "intro": "Геометрическая прогрессия задана формулой \\(b_n=10\\cdot(0,2)^n\\). Найдите сумму всех её членов, начиная с первого.",
      "answer": "2.5",
      "solution": "b₁ = 10·0,2 = 2, q = 0,2. S = 2/(1 - 0,2) = 2,5."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-025",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 25,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму бесконечной геометрической прогрессии \\(b_n=8\\cdot(1/4)^n\\).",
      "answer": "2.6666666667",
      "solution": "b₁ = 8·1/4 = 2, q = 1/4. S = 2/(1 - 1/4) = 8/3."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-026",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 26,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых четырёх членов арифметической прогрессии равна 28, а сумма последних четырёх членов равна 76. Первый член равен 4. Сколько членов в прогрессии?",
      "answer": "10",
      "solution": "S₄ = 4/2·(2·4 + 3d) = 28, откуда 8 + 3d = 14 и d = 2. Сумма последних четырёх равна 2·(2aₙ - 3d) = 76. Тогда 2aₙ - 6 = 38, aₙ = 22. 22 = 4 + 2(n - 1), откуда n = 10."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-027",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 27,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых пяти членов арифметической прогрессии равна 35, а её первый член равен 3. Найдите пятый член.",
      "answer": "11",
      "solution": "35 = 5·(a₁ + a₅)/2. Тогда a₁ + a₅ = 14. При a₁ = 3 получаем a₅ = 11."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-028",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 28,
      "prompt": "Решите задачу.",
      "intro": "Найдите десятый член арифметической прогрессии, если сумма первых 10 членов равна 155, а первый член равен 2.",
      "answer": "29",
      "solution": "155 = 10·(2 + a₁₀)/2 = 5(2 + a₁₀). Тогда 2 + a₁₀ = 31, значит a₁₀ = 29."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-029",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 29,
      "prompt": "Решите задачу.",
      "intro": "В арифметической прогрессии a₄ = 14, a₉ = 34. Найдите a₁.",
      "answer": "2",
      "solution": "a₉ - a₄ = 5d = 20, поэтому d = 4. Тогда a₁ = a₄ - 3d = 14 - 12 = 2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-030",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 30,
      "prompt": "Решите задачу.",
      "intro": "В геометрической прогрессии b₂ = 6, b₅ = 162. Найдите b₁.",
      "answer": "2",
      "solution": "b₅/b₂ = q³ = 162/6 = 27, значит q = 3. Тогда b₁ = b₂/q = 6/3 = 2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-031",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 31,
      "prompt": "Решите задачу.",
      "intro": "В геометрической прогрессии b₃ = 12, b₆ = 96. Найдите знаменатель.",
      "answer": "2",
      "solution": "b₆/b₃ = q³ = 96/12 = 8, значит q = 2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-032",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 32,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 9 членов арифметической прогрессии, если a₁ = 6 и a₉ = 38.",
      "answer": "198",
      "solution": "S₉ = 9·(6 + 38)/2 = 198."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-033",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 33,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму первых 5 членов геометрической прогрессии, если b₁ = 1 и q = 3.",
      "answer": "121",
      "solution": "S₅ = (3⁵ - 1)/(3 - 1) = (243 - 1)/2 = 121."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-034",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 34,
      "prompt": "Решите задачу.",
      "intro": "Найдите сумму бесконечно убывающей геометрической прогрессии 7, 3,5, 1,75, …",
      "answer": "14",
      "solution": "q = 0,5. S = 7/(1 - 0,5) = 14."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-035",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 35,
      "prompt": "Решите задачу.",
      "intro": "Найдите первый член арифметической прогрессии, если a₇ = 31, а разность равна 5.",
      "answer": "1",
      "solution": "a₇ = a₁ + 6d. Тогда a₁ = 31 - 30 = 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-036",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 36,
      "prompt": "Решите задачу.",
      "intro": "Найдите номер члена арифметической прогрессии 3, 8, 13, …, равного 98.",
      "answer": "20",
      "solution": "98 = 3 + (n - 1)·5. Тогда 95 = 5(n - 1), n - 1 = 19, n = 20."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-037",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 37,
      "prompt": "Решите задачу.",
      "intro": "Найдите номер члена геометрической прогрессии 2, 6, 18, …, равного 486.",
      "answer": "6",
      "solution": "2·3^(n - 1) = 486. Тогда 3^(n - 1) = 243 = 3^5, значит n = 6."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-038",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 38,
      "prompt": "Решите задачу.",
      "intro": "Сумма бесконечно убывающей геометрической прогрессии равна 30, а первый член равен 18. Найдите второй член.",
      "answer": "7.2",
      "solution": "30 = 18/(1 - q), значит 1 - q = 0,6 и q = 0,4. Тогда b₂ = 18·0,4 = 7,2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-039",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 39,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых 3 членов геометрической прогрессии равна 21, а первый член равен 3 и знаменатель положителен. Найдите знаменатель.",
      "answer": "2",
      "solution": "3(1 + q + q²) = 21. Тогда q² + q - 6 = 0. Корни 2 и -3, но q > 0, поэтому q = 2."
    },
    {
      "id": "math-mcko-10-basic-algebra-004-040",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 4,
      "title": "Прогрессии",
      "topic": "Алгебра",
      "task_group": 4,
      "item_number": 40,
      "prompt": "Решите задачу.",
      "intro": "Сумма первых 8 членов арифметической прогрессии равна 176, а её первый член равен 1. Найдите разность.",
      "answer": "6",
      "solution": "176 = 8/2·(2·1 + 7d) = 4(2 + 7d). Тогда 44 = 2 + 7d, откуда d = 6."
    }
  ]
});
