window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 10,
  "level": "basic",
  "section": "algebra",
  "number": 3,
  "title": "Алгебра",
  "topic": "Базовый уровень",
  "block": "МЦКО 10 класс · Алгебра · Базовый уровень",
  "total_tasks": 40,
  "items": [
    {
      "id": "math-mcko-10-basic-algebra-003-001",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\sqrt{18}\\cos^2\\frac{5\\pi}{6}-\\sqrt{18}\\sin^2\\frac{5\\pi}{6}\\).",
      "answer": "\\(\\frac{3\\sqrt2}{2}\\)",
      "solution": "Используем формулу \\(\\cos^2x-\\sin^2x=\\cos2x\\). Получаем \\(\\sqrt{18}\\cos\\frac{5\\pi}{3}=\\sqrt{18}\\cdot\\frac12=\\frac{3\\sqrt2}{2}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-002",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 2,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\frac{4\\cos\\alpha-3\\sin\\alpha}{5\\sin\\alpha-2\\cos\\alpha}\\), если \\(\\tg\\alpha=2\\).",
      "answer": "\\(-\\frac14\\)",
      "solution": "Делим числитель и знаменатель на \\(\\cos\\alpha\\): \\(\\frac{4-3\\tg\\alpha}{5\\tg\\alpha-2}=\\frac{4-6}{10-2}=-\\frac14\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-003",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 3,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\frac{2\\sin\\alpha+3\\cos\\alpha}{\\sin\\alpha-\\cos\\alpha}=5\\).",
      "answer": "\\(\\frac83\\)",
      "solution": "Пусть \\(t=\\tg\\alpha\\). Тогда \\(\\frac{2t+3}{t-1}=5\\). Получаем \\(2t+3=5t-5\\), откуда \\(t=\\frac83\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-004",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 4,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\sin\\alpha=-\\frac{3}{5}\\) и \\(\\alpha\\in\\left(\\pi;\\frac{3\\pi}{2}\\right)\\).",
      "answer": "\\(\\frac34\\)",
      "solution": "В III четверти \\(\\cos\\alpha<0\\). \\(\\cos\\alpha=-\\sqrt{1-\\frac9{25}}=-\\frac45\\). Тогда \\(\\tg\\alpha=\\frac{-3/5}{-4/5}=\\frac34\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-005",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 5,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(10\\cos\\left(\\frac{3\\pi}{2}+\\alpha\\right)\\), если \\(\\cos\\alpha=\\frac35\\) и \\(\\alpha\\in\\left(\\frac{3\\pi}{2};2\\pi\\right)\\).",
      "answer": "8",
      "solution": "\\(\\cos\\left(\\frac{3\\pi}{2}+\\alpha\\right)=-\\sin\\alpha\\). В IV четверти \\(\\sin\\alpha<0\\), поэтому \\(\\sin\\alpha=-\\frac45\\). Получаем \\(-10\\sin\\alpha=8\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-006",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 6,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\frac{17}{\\cos^2 23^\\circ+1-\\cos^2 67^\\circ}\\).",
      "answer": "17",
      "solution": "\\(\\cos67^\\circ=\\sin23^\\circ\\). Знаменатель равен \\(\\cos^223^\\circ+1-\\sin^223^\\circ=1+\\cos46^\\circ\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-007",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 7,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg2\\alpha\\), если \\(\\sin\\alpha=-\\frac{4}{5}\\) и \\(-\\pi<\\alpha<-\\frac{\\pi}{2}\\).",
      "answer": "\\(-\\frac{24}{7}\\)",
      "solution": "В III четверти \\(\\cos\\alpha=-\\frac35\\), поэтому \\(\\tg\\alpha=\\frac43\\). Тогда \\(\\tg2\\alpha=\\frac{2\\cdot4/3}{1-16/9}=-\\frac{24}{7}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-008",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 8,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos\\alpha\\), если \\(\\sin\\alpha=\\frac{5}{13}\\) и \\(\\alpha\\in\\left(\\frac{\\pi}{2};\\pi\\right)\\).",
      "answer": "\\(-\\frac{12}{13}\\)",
      "solution": "Во II четверти косинус отрицателен. \\(\\cos\\alpha=-\\sqrt{1-\\frac{25}{169}}=-\\frac{12}{13}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-009",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 9,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin2\\alpha\\), если \\(\\sin\\alpha=-\\frac{8}{17}\\) и \\(\\alpha\\in\\left(\\frac{3\\pi}{2};2\\pi\\right)\\).",
      "answer": "\\(-\\frac{240}{289}\\)",
      "solution": "В IV четверти \\(\\cos\\alpha=\\frac{15}{17}\\). Тогда \\(\\sin2\\alpha=2\\sin\\alpha\\cos\\alpha=2\\cdot\\left(-\\frac8{17}\\right)\\cdot\\frac{15}{17}=-\\frac{240}{289}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-010",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 10,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\cos\\alpha=-\\frac{5}{13}\\) и \\(\\alpha\\in\\left(\\frac{\\pi}{2};\\pi\\right)\\).",
      "answer": "\\(-\\frac{12}{5}\\)",
      "solution": "Во II четверти \\(\\sin\\alpha=\\frac{12}{13}\\). Тогда \\(\\tg\\alpha=\\frac{12/13}{-5/13}=-\\frac{12}{5}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-011",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 11,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(6\\sin^2\\frac{\\pi}{4}+6\\cos^2\\frac{\\pi}{4}\\).",
      "answer": "6",
      "solution": "По тождеству \\(\\sin^2x+\\cos^2x=1\\), выражение равно 6."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-012",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 12,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(4\\cos^2\\frac{\\pi}{3}-4\\sin^2\\frac{\\pi}{3}\\).",
      "answer": "-2",
      "solution": "\\(\\cos^2\\frac{\\pi}{3}-\\sin^2\\frac{\\pi}{3}=\\cos\\frac{2\\pi}{3}=-\\frac12\\). Умножаем на 4."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-013",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 13,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\frac{5\\cos\\alpha+2\\sin\\alpha}{3\\cos\\alpha-\\sin\\alpha}\\), если \\(\\tg\\alpha=1\\).",
      "answer": "\\(\\frac72\\)",
      "solution": "Делим на \\(\\cos\\alpha\\): \\(\\frac{5+2}{3-1}=\\frac72\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-014",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 14,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\frac{2\\sin\\alpha-\\cos\\alpha}{\\sin\\alpha+4\\cos\\alpha}\\), если \\(\\tg\\alpha=3\\).",
      "answer": "\\(\\frac57\\)",
      "solution": "Делим на \\(\\cos\\alpha\\): \\(\\frac{2\\cdot3-1}{3+4}=\\frac57\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-015",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 15,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\frac{3\\sin\\alpha+\\cos\\alpha}{2\\sin\\alpha-\\cos\\alpha}=2\\).",
      "answer": "3",
      "solution": "Пусть \\(t=\\tg\\alpha\\). Тогда \\(\\frac{3t+1}{2t-1}=2\\). Получаем \\(3t+1=4t-2\\), значит \\(t=3\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-016",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 16,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\frac{5\\sin\\alpha-2\\cos\\alpha}{\\sin\\alpha+\\cos\\alpha}=1\\).",
      "answer": "\\(\\frac34\\)",
      "solution": "\\(\\frac{5t-2}{t+1}=1\\). Тогда \\(5t-2=t+1\\), откуда \\(t=\\frac34\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-017",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 17,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos\\alpha\\), если \\(\\sin\\alpha=-\\frac{12}{13}\\) и \\(\\alpha\\in\\left(\\pi;\\frac{3\\pi}{2}\\right)\\).",
      "answer": "\\(-\\frac5{13}\\)",
      "solution": "В III четверти косинус отрицателен. \\(\\cos\\alpha=-\\sqrt{1-\\frac{144}{169}}=-\\frac5{13}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-018",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 18,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin\\alpha\\), если \\(\\cos\\alpha=\\frac7{25}\\) и \\(\\alpha\\in\\left(\\frac{3\\pi}{2};2\\pi\\right)\\).",
      "answer": "\\(-\\frac{24}{25}\\)",
      "solution": "В IV четверти синус отрицателен. \\(\\sin\\alpha=-\\sqrt{1-\\frac{49}{625}}=-\\frac{24}{25}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-019",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 19,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg\\alpha\\), если \\(\\cos\\alpha=\\frac8{17}\\) и \\(\\alpha\\in\\left(0;\\frac{\\pi}{2}\\right)\\).",
      "answer": "\\(\\frac{15}{8}\\)",
      "solution": "В I четверти \\(\\sin\\alpha=\\frac{15}{17}\\), поэтому \\(\\tg\\alpha=\\frac{15}{8}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-020",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 20,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\ctg\\alpha\\), если \\(\\sin\\alpha=\\frac{12}{13}\\) и \\(\\alpha\\in\\left(\\frac{\\pi}{2};\\pi\\right)\\).",
      "answer": "\\(-\\frac5{12}\\)",
      "solution": "Во II четверти \\(\\cos\\alpha=-\\frac5{13}\\). Тогда \\(\\ctg\\alpha=\\frac{\\cos\\alpha}{\\sin\\alpha}=-\\frac5{12}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-021",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 21,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(13\\sin\\left(\\pi+\\alpha\\right)\\), если \\(\\sin\\alpha=\\frac5{13}\\).",
      "answer": "-5",
      "solution": "\\(\\sin(\\pi+\\alpha)=-\\sin\\alpha\\), поэтому \\(13\\cdot(-5/13)=-5\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-022",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 22,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(17\\cos\\left(\\pi-\\alpha\\right)\\), если \\(\\cos\\alpha=\\frac8{17}\\).",
      "answer": "-8",
      "solution": "\\(\\cos(\\pi-\\alpha)=-\\cos\\alpha\\), поэтому результат равен -8."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-023",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 23,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(10\\sin\\left(\\frac{\\pi}{2}-\\alpha\\right)\\), если \\(\\cos\\alpha=-0,6\\).",
      "answer": "-6",
      "solution": "\\(\\sin(\\frac{\\pi}{2}-\\alpha)=\\cos\\alpha\\). Получаем \\(10\\cdot(-0,6)=-6\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-024",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 24,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(25\\cos\\left(\\frac{\\pi}{2}+\\alpha\\right)\\), если \\(\\sin\\alpha=-\\frac7{25}\\).",
      "answer": "7",
      "solution": "\\(\\cos(\\frac{\\pi}{2}+\\alpha)=-\\sin\\alpha=\\frac7{25}\\). Умножаем на 25."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-025",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 25,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin2\\alpha\\), если \\(\\sin\\alpha=\\frac35\\) и \\(\\alpha\\in\\left(0;\\frac{\\pi}{2}\\right)\\).",
      "answer": "\\(\\frac{24}{25}\\)",
      "solution": "\\(\\cos\\alpha=\\frac45\\). Тогда \\(\\sin2\\alpha=2\\cdot\\frac35\\cdot\\frac45=\\frac{24}{25}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-026",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 26,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos2\\alpha\\), если \\(\\sin\\alpha=\\frac5{13}\\).",
      "answer": "\\(\\frac{119}{169}\\)",
      "solution": "\\(\\cos2\\alpha=1-2\\sin^2\\alpha=1-\\frac{50}{169}=\\frac{119}{169}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-027",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 27,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos2\\alpha\\), если \\(\\cos\\alpha=\\frac3{5}\\).",
      "answer": "\\(-\\frac7{25}\\)",
      "solution": "\\(\\cos2\\alpha=2\\cos^2\\alpha-1=\\frac{18}{25}-1=-\\frac7{25}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-028",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 28,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg2\\alpha\\), если \\(\\tg\\alpha=\\frac12\\).",
      "answer": "\\(\\frac43\\)",
      "solution": "\\(\\tg2\\alpha=\\frac{2t}{1-t^2}=\\frac1{1-\\frac14}=\\frac43\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-029",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 29,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\tg2\\alpha\\), если \\(\\tg\\alpha=2\\).",
      "answer": "\\(-\\frac43\\)",
      "solution": "\\(\\tg2\\alpha=\\frac4{1-4}=-\\frac43\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-030",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 30,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\frac{1-\\cos2\\alpha}{2\\sin^2\\alpha}\\).",
      "answer": "1",
      "solution": "По формуле \\(1-\\cos2\\alpha=2\\sin^2\\alpha\\), поэтому значение равно 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-031",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 31,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\frac{1+\\cos2\\alpha}{2\\cos^2\\alpha}\\).",
      "answer": "1",
      "solution": "По формуле \\(1+\\cos2\\alpha=2\\cos^2\\alpha\\), поэтому значение равно 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-032",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 32,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\sin^2 20^\\circ+\\sin^2 70^\\circ\\).",
      "answer": "1",
      "solution": "\\(\\sin70^\\circ=\\cos20^\\circ\\). Тогда сумма равна \\(\\sin^220^\\circ+\\cos^220^\\circ=1\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-033",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 33,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\cos^2 15^\\circ+\\cos^2 75^\\circ\\).",
      "answer": "1",
      "solution": "\\(\\cos75^\\circ=\\sin15^\\circ\\). Тогда сумма равна 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-034",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 34,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(\\frac{7}{\\sin^2 32^\\circ+\\cos^2 32^\\circ}\\).",
      "answer": "7",
      "solution": "Знаменатель равен 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-035",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 35,
      "prompt": "Решите задачу.",
      "intro": "Найдите значение выражения \\(3\\sin^2\\alpha+3\\cos^2\\alpha+4\\).",
      "answer": "7",
      "solution": "\\(\\sin^2\\alpha+\\cos^2\\alpha=1\\), поэтому \\(3+4=7\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-036",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 36,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin\\alpha\\), если \\(\\tg\\alpha=\\frac34\\) и \\(\\alpha\\in\\left(0;\\frac{\\pi}{2}\\right)\\).",
      "answer": "\\(\\frac35\\)",
      "solution": "Для прямоугольного треугольника с катетами 3 и 4 гипотенуза равна 5. В I четверти \\(\\sin\\alpha=\\frac35\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-037",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 37,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos\\alpha\\), если \\(\\tg\\alpha=-\\frac{12}{5}\\) и \\(\\alpha\\in\\left(\\frac{\\pi}{2};\\pi\\right)\\).",
      "answer": "\\(-\\frac5{13}\\)",
      "solution": "Во II четверти косинус отрицателен. Для катетов 12 и 5 гипотенуза 13, значит \\(\\cos\\alpha=-\\frac5{13}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-038",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 38,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin\\alpha\\), если \\(\\ctg\\alpha=-\\frac8{15}\\) и \\(\\alpha\\in\\left(\\frac{\\pi}{2};\\pi\\right)\\).",
      "answer": "\\(\\frac{15}{17}\\)",
      "solution": "Во II четверти синус положителен. При отношении катетов 8:15 гипотенуза 17, значит \\(\\sin\\alpha=\\frac{15}{17}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-039",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 39,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\cos\\alpha\\), если \\(\\ctg\\alpha=\\frac7{24}\\) и \\(\\alpha\\in\\left(\\pi;\\frac{3\\pi}{2}\\right)\\).",
      "answer": "\\(-\\frac7{25}\\)",
      "solution": "В III четверти косинус отрицателен. При катетах 7 и 24 гипотенуза 25, значит \\(\\cos\\alpha=-\\frac7{25}\\)."
    },
    {
      "id": "math-mcko-10-basic-algebra-003-040",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 3,
      "title": "Тригонометрия",
      "topic": "Алгебра",
      "task_group": 3,
      "item_number": 40,
      "prompt": "Решите задачу.",
      "intro": "Найдите \\(\\sin2\\alpha\\), если \\(\\tg\\alpha=\\frac13\\).",
      "answer": "\\(\\frac35\\)",
      "solution": "\\(\\sin2\\alpha=\\frac{2\\tg\\alpha}{1+\\tg^2\\alpha}=\\frac{2/3}{1+1/9}=\\frac35\\)."
    }
  ]
});
