window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 10,
  "level": "basic",
  "section": "algebra",
  "number": 2,
  "title": "Алгебра",
  "topic": "Базовый уровень",
  "block": "МЦКО 10 класс · Алгебра · Базовый уровень",
  "total_tasks": 50,
  "items": [
    {
      "id": "math-mcko-10-basic-algebra-002-001",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 1,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{12\\sqrt[9]{m}\\cdot\\sqrt[18]{m}}{\\sqrt[6]{m}},\\quad m>0\\).",
      "answer": "12",
      "solution": "\\sqrt[9]{m}=m^{1/9}, \\sqrt[18]{m}=m^{1/18}, \\sqrt[6]{m}=m^{1/6}. Показатель степени равен \\frac19+\\frac1{18}-\\frac16=0, поэтому значение выражения равно 12."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-002",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 2,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt[5]{10}\\cdot\\sqrt[5]{16}}{\\sqrt[5]{5}}\\).",
      "answer": "2",
      "solution": "\\sqrt[5]{\\frac{10\\cdot16}{5}}=\\sqrt[5]{32}=2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-003",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 3,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{b^{6,3}}{b^{4,9}\\cdot b^{3,4}},\\quad b=\\frac{10}{7}\\).",
      "answer": "0.49",
      "solution": "6,3-4,9-3,4=-2. Получаем b^{-2}=\\left(\\frac7{10}\\right)^2=\\frac{49}{100}=0,49."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-004",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 4,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{0,5^{\\sqrt{10}-1}}{2^{-\\sqrt{10}}}\\).",
      "answer": "2",
      "solution": "0,5=2^{-1}. Тогда числитель равен 2^{1-\\sqrt{10}}, а всё выражение: 2^{1-\\sqrt{10}+\\sqrt{10}}=2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-005",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 5,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt[9]{7}\\cdot\\sqrt[18]{7}}{\\sqrt[6]{7}}\\).",
      "answer": "1",
      "solution": "\\frac19+\\frac1{18}-\\frac16=0, поэтому выражение равно 7^0=1."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-006",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 6,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(b^{1/5}\\cdot\\left(b^{9/10}\\right)^2,\\quad b=7\\).",
      "answer": "49",
      "solution": "b^{1/5}\\cdot b^{9/5}=b^2. При b=7 получаем 49."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-007",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 7,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{3\\sqrt{x}-6}{\\sqrt{x}}+\\frac{2\\sqrt{x}}{x}+2,\\quad x=4\\).",
      "answer": "3",
      "solution": "\\sqrt4=2. Получаем \\frac{6-6}{2}+\\frac4{4}+2=0+1+2=3."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-008",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 8,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(25^{-2,5}\\cdot 5^7:5^{-1}\\).",
      "answer": "125",
      "solution": "25^{-2,5}=(5^2)^{-2,5}=5^{-5}. Тогда 5^{-5}\\cdot5^7:5^{-1}=5^{-5+7+1}=5^3=125."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-009",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 9,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\((b^{16})^{1/4}\\cdot b^{-3}:(b^{-1})^2,\\quad b=0,1\\).",
      "answer": "0.001",
      "solution": "(b^{16})^{1/4}=b^4, а (b^{-1})^2=b^{-2}. Получаем b^{4-3+2}=b^3. При b=0,1: 0,1^3=0,001."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-010",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 10,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt{m}}{\\sqrt[9]{m}\\cdot\\sqrt[18]{m}},\\quad m=64\\).",
      "answer": "4",
      "solution": "\\frac12-\\frac19-\\frac1{18}=\\frac13. Значит, выражение равно m^{1/3}=\\sqrt[3]{64}=4."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-011",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 11,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt[3]{27}\\cdot\\sqrt[3]{2}}{\\sqrt[3]{2}}\\).",
      "answer": "3",
      "solution": "Сокращаем одинаковые множители и получаем \\sqrt[3]{27}=3."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-012",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 12,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt[4]{12}\\cdot\\sqrt[4]{4}}{\\sqrt[4]{3}}\\).",
      "answer": "2",
      "solution": "\\sqrt[4]{\\frac{12\\cdot4}{3}}=\\sqrt[4]{16}=2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-013",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 13,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{(a^{0,4})^5}{a},\\quad a=9\\).",
      "answer": "9",
      "solution": "(a^{0,4})^5=a^2. Тогда \\frac{a^2}{a}=a=9."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-014",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 14,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{c^{2,7}\\cdot c^{1,8}}{c^{3,5}},\\quad c=10\\).",
      "answer": "10",
      "solution": "2,7+1,8-3,5=1. Получаем c^1=10."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-015",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 15,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\((x^{-3})^2\\cdot x^7,\\quad x=2\\).",
      "answer": "2",
      "solution": "(x^{-3})^2=x^{-6}. Тогда x^{-6}\\cdot x^7=x=2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-016",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 16,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{4^{\\sqrt3+1}}{2^{2\\sqrt3}}\\).",
      "answer": "4",
      "solution": "4^{\\sqrt3+1}=2^{2\\sqrt3+2}. После деления на 2^{2\\sqrt3} остаётся 2^2=4."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-017",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 17,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{0,25^{\\,2-\\sqrt5}}{2^{\\,2\\sqrt5-4}}\\).",
      "answer": "1",
      "solution": "0,25=2^{-2}. Числитель равен 2^{-4+2\\sqrt5}. Показатель знаменателя такой же, поэтому частное равно 1."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-018",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 18,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\left(\\sqrt[7]{3}\\right)^{14}\\).",
      "answer": "9",
      "solution": "\\left(3^{1/7}\\right)^{14}=3^2=9."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-019",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 19,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[5]{2^{10}\\cdot3^5}\\).",
      "answer": "12",
      "solution": "\\sqrt[5]{2^{10}\\cdot3^5}=2^2\\cdot3=12."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-020",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 20,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[4]{81}\\cdot\\sqrt9\\).",
      "answer": "9",
      "solution": "\\sqrt[4]{81}=3 и \\sqrt9=3. Произведение равно 9."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-021",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 21,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[6]{64}\\cdot\\sqrt[3]{8}\\).",
      "answer": "4",
      "solution": "\\sqrt[6]{64}=2 и \\sqrt[3]{8}=2. Произведение равно 4."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-022",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 22,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{(\\sqrt[3]{5})^6}{25}\\).",
      "answer": "1",
      "solution": "(\\sqrt[3]{5})^6=5^2=25. Тогда \\frac{25}{25}=1."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-023",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 23,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{a^{5/6}}{\\sqrt[3]{a}},\\quad a=64\\).",
      "answer": "8",
      "solution": "\\frac56-\\frac13=\\frac12. Получаем \\sqrt a=\\sqrt{64}=8."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-024",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 24,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt[4]{b^6}}{\\sqrt b},\\quad b=16\\).",
      "answer": "16",
      "solution": "\\sqrt[4]{b^6}=b^{3/2}. После деления на b^{1/2} получаем b=16."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-025",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 25,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{m^{3/4}\\cdot m^{1/2}}{m^{1/4}},\\quad m=16\\).",
      "answer": "16",
      "solution": "\\frac34+\\frac12-\\frac14=1. Выражение равно m=16."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-026",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 26,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{27^{2/3}}{3}\\).",
      "answer": "3",
      "solution": "27^{2/3}=(\\sqrt[3]{27})^2=9. Тогда \\frac93=3."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-027",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 27,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{16^{3/4}}{2}\\).",
      "answer": "4",
      "solution": "16^{3/4}=(\\sqrt[4]{16})^3=2^3=8. Тогда \\frac82=4."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-028",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 28,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(125^{2/3}-25^{1/2}\\).",
      "answer": "20",
      "solution": "125^{2/3}=25, а 25^{1/2}=5. Разность равна 20."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-029",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 29,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(81^{3/4}:3^2\\).",
      "answer": "3",
      "solution": "81^{3/4}=(\\sqrt[4]{81})^3=3^3=27. 27:9=3."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-030",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 30,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(32^{4/5}:2^3\\).",
      "answer": "2",
      "solution": "32^{4/5}=(\\sqrt[5]{32})^4=2^4=16. 16:8=2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-031",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 31,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(x^{1,2}\\cdot x^{-0,7},\\quad x=100\\).",
      "answer": "10",
      "solution": "1,2-0,7=0,5. Получаем \\sqrt{100}=10."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-032",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 32,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{y^{3,6}}{y^{1,1}},\\quad y=4\\).",
      "answer": "32",
      "solution": "3,6-1,1=2,5. Тогда 4^{2,5}=4^2\\cdot\\sqrt4=16\\cdot2=32."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-033",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 33,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{(z^{0,25})^8}{z},\\quad z=9\\).",
      "answer": "9",
      "solution": "(z^{0,25})^8=z^2. После деления на z получаем z=9."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-034",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 34,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(a^{-1,5}\\cdot a^{2,5},\\quad a=6\\).",
      "answer": "6",
      "solution": "-1,5+2,5=1. Выражение равно a=6."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-035",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 35,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{b^{4,2}}{b^{1,7}\\cdot b^{1,5}},\\quad b=5\\).",
      "answer": "5",
      "solution": "4,2-1,7-1,5=1. Получаем b=5."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-036",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 36,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[3]{64x^3},\\quad x=2\\).",
      "answer": "8",
      "solution": "\\sqrt[3]{64x^3}=4x. При x=2 получаем 8."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-037",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 37,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt{49a^2},\\quad a=3\\).",
      "answer": "21",
      "solution": "При a>0: \\sqrt{49a^2}=7a=21."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-038",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 38,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[4]{16b^4},\\quad b=5\\).",
      "answer": "10",
      "solution": "При b>0: \\sqrt[4]{16b^4}=2b=10."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-039",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 39,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[5]{32c^5},\\quad c=4\\).",
      "answer": "8",
      "solution": "\\sqrt[5]{32c^5}=2c=8."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-040",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 40,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\sqrt[6]{64d^6},\\quad d=3\\).",
      "answer": "6",
      "solution": "При d>0: \\sqrt[6]{64d^6}=2d=6."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-041",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 41,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\((\\sqrt x+1)(\\sqrt x-1),\\quad x=25\\).",
      "answer": "24",
      "solution": "По формуле разности квадратов получаем x-1=25-1=24."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-042",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 42,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{x-9}{\\sqrt x-3},\\quad x=16\\).",
      "answer": "7",
      "solution": "x-9=(\\sqrt x-3)(\\sqrt x+3). После сокращения остаётся \\sqrt x+3=4+3=7."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-043",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 43,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{\\sqrt x-2}{x-4},\\quad x=9\\).",
      "answer": "0.2",
      "solution": "x-4=(\\sqrt x-2)(\\sqrt x+2). После сокращения получаем \\frac1{\\sqrt x+2}=\\frac15=0,2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-044",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 44,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{x-16}{\\sqrt x+4},\\quad x=25\\).",
      "answer": "1",
      "solution": "x-16=(\\sqrt x-4)(\\sqrt x+4). После сокращения остаётся \\sqrt x-4=5-4=1."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-045",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 45,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\((\\sqrt x+3)^2-x,\\quad x=16\\).",
      "answer": "33",
      "solution": "(\\sqrt{16}+3)^2-16=(4+3)^2-16=49-16=33."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-046",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 46,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(2^{\\sqrt7}\\cdot4^{1-\\sqrt7/2}\\).",
      "answer": "4",
      "solution": "4^{1-\\sqrt7/2}=2^{2-\\sqrt7}. Тогда произведение равно 2^{\\sqrt7+2-\\sqrt7}=2^2=4."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-047",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 47,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(3^{2\\sqrt2}\\cdot9^{1-\\sqrt2}\\).",
      "answer": "9",
      "solution": "9^{1-\\sqrt2}=3^{2-2\\sqrt2}. Сумма показателей равна 2, поэтому получаем 3^2=9."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-048",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 48,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(5^{\\sqrt3-1}\\cdot25^{1-\\sqrt3/2}\\).",
      "answer": "5",
      "solution": "25^{1-\\sqrt3/2}=5^{2-\\sqrt3}. Сумма показателей равна 1, поэтому значение равно 5."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-049",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 49,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(0,2^{\\,1-\\sqrt6}\\cdot5^{-\\sqrt6}\\).",
      "answer": "0.2",
      "solution": "0,2=5^{-1}. Тогда 0,2^{1-\\sqrt6}=5^{-1+\\sqrt6}. После умножения на 5^{-\\sqrt6} получаем 5^{-1}=0,2."
    },
    {
      "id": "math-mcko-10-basic-algebra-002-050",
      "subject": "Математика",
      "grade": 10,
      "level": "basic",
      "section": "algebra",
      "number": 2,
      "title": "Степени и корни",
      "topic": "Алгебра",
      "task_group": 2,
      "item_number": 50,
      "prompt": "Найдите значение выражения.",
      "intro": "Найдите значение выражения \\(\\frac{0,125^{\\,2-\\sqrt2}}{8^{\\sqrt2-1}}\\).",
      "answer": "0.125",
      "solution": "0,125=8^{-1}. Числитель равен 8^{-2+\\sqrt2}. После деления получаем 8^{-2+\\sqrt2-\\sqrt2+1}=8^{-1}=0,125."
    }
  ]
});
