window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 7,
  "level": "basic",
  "section": "geometry",
  "number": 1,
  "title": "Геометрия",
  "topic": "Базовый уровень",
  "block": "МЦКО 7 класс · Геометрия · Базовый уровень",
  "total_tasks": 9,
  "items": [
    {
      "id": "math-mcko-07-basic-geometry-001",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 1,
      "title": "Клетчатая бумага",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "На клетчатой бумаге с размером клетки 1 × 1 изображён прямоугольный треугольник. Найдите длину его большего катета.",
      "image": "mcko-tasks/grade-07/images/geometry-basic-grid-triangle.svg",
      "image_alt": "Прямоугольный треугольник на клетчатой бумаге",
      "answer": "7",
      "solution": "По рисунку катеты равны 5 и 7 клеткам. Больший катет равен 7."
    },
    {
      "id": "math-mcko-07-basic-geometry-002",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 2,
      "title": "Внешний угол треугольника",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "В треугольнике ABC внешний угол при вершине B равен 58°, AB = BC. Найдите угол BAC. Ответ дайте в градусах.",
      "image": "mcko-tasks/grade-07/images/geometry-basic-exterior-angle.svg",
      "image_alt": "Треугольник ABC с внешним углом при вершине B",
      "answer": "29",
      "solution": "Внутренний угол при B равен 180° - 58° = 122°. Так как AB = BC, углы при A и C равны. Тогда угол BAC равен (180° - 122°) / 2 = 29°."
    },
    {
      "id": "math-mcko-07-basic-geometry-003",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 3,
      "title": "Параллельные прямые",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "Прямая EF пересекает параллельные прямые AB и CD в точках K и N соответственно. Угол CNF равен 136°. Найдите угол AKE. Ответ дайте в градусах.",
      "image": "mcko-tasks/grade-07/images/geometry-basic-parallel-lines.svg",
      "image_alt": "Параллельные прямые AB и CD, пересечённые прямой EF",
      "answer": "44",
      "solution": "Угол, смежный с углом 136°, равен 44°. По свойству параллельных прямых соответствующий угол AKE также равен 44°."
    },
    {
      "id": "math-mcko-07-basic-geometry-004",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 4,
      "title": "Медиана в равнобедренном треугольнике",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "question_text": "В треугольнике ABC угол ABC равен 120°, AB = BC, BM - медиана. На луче BM отметили точку F такую, что ∠BAF = 90°. Найдите FM, если AB = 30.",
      "answer": "45",
      "solution": "В равнобедренном треугольнике медиана BM является высотой и биссектрисой. В прямоугольном треугольнике ABM угол B равен 60°, поэтому BM = 15. Из условия ∠BAF = 90° получается FM = 3BM = 45."
    },
    {
      "id": "math-mcko-07-basic-geometry-005",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 5,
      "title": "Верное утверждение",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Укажите верное утверждение.",
      "options": [
        "Сумма вертикальных углов равна 180°.",
        "Треугольник является остроугольным, если у него хотя бы один угол острый.",
        "Если гипотенуза и острый угол одного прямоугольного треугольника равны гипотенузе и острому углу другого прямоугольного треугольника, то эти треугольники всегда равны."
      ],
      "answer": "3",
      "solution": "Верно третье утверждение: прямоугольные треугольники равны по гипотенузе и острому углу."
    },
    {
      "id": "math-mcko-07-basic-geometry-006-1",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 6,
      "title": "Таблица баллов",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "В таблице показаны данные о количестве баллов, полученных семиклассниками по итогам проведения олимпиады.",
      "image": "mcko-tasks/grade-07/images/geometry-basic-scores-table.svg",
      "image_alt": "Таблица баллов семиклассников по итогам олимпиады",
      "question_text": "Найдите медиану количества баллов.",
      "answer": "69",
      "solution": "Упорядочим баллы: 46, 53, 54, 62, 69, 73, 78, 87, 90. Среднее, пятое значение равно 69."
    },
    {
      "id": "math-mcko-07-basic-geometry-006-2",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 6,
      "title": "Таблица баллов",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 2,
      "prompt": "Решите задачу.",
      "intro": "В таблице показаны данные о количестве баллов, полученных семиклассниками по итогам проведения олимпиады.",
      "image": "mcko-tasks/grade-07/images/geometry-basic-scores-table.svg",
      "image_alt": "Таблица баллов семиклассников по итогам олимпиады",
      "question_text": "Найдите размах количества баллов.",
      "answer": "44",
      "solution": "Наибольшее количество баллов равно 90, наименьшее - 46. Размах равен 90 - 46 = 44."
    },
    {
      "id": "math-mcko-07-basic-geometry-007",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 7,
      "title": "Сравнение величин",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Укажите все верные утверждения.",
      "intro": "Витя на 3 см ниже Бори и на 6 см ниже Егора. Боря на 4 см выше Димы.",
      "options": [
        "Дима выше Вити.",
        "Егор выше Бори на 2 см.",
        "Дима ниже Егора на 7 см.",
        "Среди указанных мальчиков нет двоих одного роста."
      ],
      "answer": "3, 4",
      "solution": "Если рост Вити принять за V, то Боря: V + 3, Егор: V + 6, Дима: V - 1. Поэтому верны утверждения 3 и 4."
    },
    {
      "id": "math-mcko-07-basic-geometry-008",
      "subject": "Математика",
      "grade": 7,
      "level": "basic",
      "section": "geometry",
      "number": 8,
      "title": "Графы",
      "topic": "Геометрия",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Решите задачу.",
      "intro": "На рисунке показана схема улиц небольшого города. Какое наименьшее число улиц можно закрыть на ремонт так, чтобы маршрут автобуса проходил бы ровно по одному разу по каждой улице, на которой нет ремонта?",
      "image": "mcko-tasks/grade-07/images/geometry-basic-street-graph.svg",
      "image_alt": "Схема улиц небольшого города",
      "answer": "1",
      "solution": "В графе четыре вершины нечётной степени. Если закрыть одну улицу, соединяющую две нечётные вершины, останутся две нечётные вершины, значит маршрут Эйлера станет возможен. Поэтому достаточно закрыть 1 улицу."
    }
  ]
});
