window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push(
{
  id: "math-oge-018-p001",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 1,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге с размером клетки 1×1 изображён треугольник.",
  image: "images/task-18/task-18-001.png",
  image_alt: "Треугольник на клетчатой бумаге",
  question_text: "Найдите его площадь.",
  answer: "",
  solution: "Площадь находится по формуле S = 1/2 · основание · высота или через координаты (формула площади по точкам)."
},
{
  id: "math-oge-018-p002",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 2,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге с размером клетки 1×1 изображён ромб.",
  image: "images/task-18/task-18-002.png",
  image_alt: "Ромб на клетчатой бумаге",
  question_text: "Найдите длину его большей диагонали.",
  answer: "",
  solution: "Диагонали считаются по клеткам как расстояние между вершинами."
},
{
  id: "math-oge-018-p003",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 3,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге с размером клетки 1×1 изображён прямоугольный треугольник.",
  image: "images/task-18/task-18-003.png",
  image_alt: "Прямоугольный треугольник",
  question_text: "Найдите длину его большего катета.",
  answer: "",
  solution: "Длина катета определяется по координатам или подсчётом клеток."
},
{
  id: "math-oge-018-p004",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 4,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображён треугольник ABC.",
  image: "images/task-18/task-18-004.png",
  image_alt: "Треугольник ABC",
  question_text: "Найдите длину его средней линии, параллельной стороне AC.",
  answer: "",
  solution: "Средняя линия равна половине соответствующей стороны: m = AC/2."
},
{
  id: "math-oge-018-p005",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 5,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображён параллелограмм.",
  image: "images/task-18/task-18-005.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите его площадь.",
  answer: "",
  solution: "S = основание × высота, высота считается по клеткам."
},
{
  id: "math-oge-018-p006",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 6,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображён параллелограмм.",
  image: "images/task-18/task-18-006.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите его площадь.",
  answer: "",
  solution: "Площадь через основание и высоту по клеткам."
},
{
  id: "math-oge-018-p007",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 7,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображён ромб.",
  image: "images/task-18/task-18-007.png",
  image_alt: "Ромб",
  question_text: "Найдите длину его большей диагонали.",
  answer: "",
  solution: "Диагональ определяется по координатам вершин."
},
{
  id: "math-oge-018-p008",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 8,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображена трапеция.",
  image: "images/task-18/task-18-008.png",
  image_alt: "Трапеция",
  question_text: "Найдите её площадь.",
  answer: "",
  solution: "S = (a + b)/2 · h, все величины считаются по клеткам."
},
{
  id: "math-oge-018-p009",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 9,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображена трапеция.",
  image: "images/task-18/task-18-009.png",
  image_alt: "Трапеция",
  question_text: "Найдите длину её средней линии.",
  answer: "",
  solution: "Средняя линия = (a + b)/2."
},
{
  id: "math-oge-018-p010",
  subject: "Математика",
  number: 18,
  title: "Планиметрия (по клеткам)",
  block: "Скриншоты",
  task_group: 1,
  item_number: 10,
  prompt: "Решите задачу.",
  intro: "На клетчатой бумаге изображён треугольник.",
  image: "images/task-18/task-18-010.png",
  image_alt: "Треугольник",
  question_text: "Найдите его площадь.",
  answer: "",
  solution: "Площадь через координаты или через основание и высоту."
},
{
      "id": "math-oge-018-extra-p027",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 27,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён треугольник. Найдите его площадь.",
      "answer": "",
      "solution": "",
      "source_guid": "0288AD849FD5A3C1476CFC0E408A339F",
      "source_number": "0C5645",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0288AD849FD5A3C1476CFC0E408A339F/xs3qstsrc0288AD849FD5A3C1476CFC0E408A339F_1_1458034082.png",
      "image_alt": "Иллюстрация к заданию 27",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"802\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён треугольник. Найдите его площадь.<span></span></p> </td> <td width=\"467\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0288AD849FD5A3C1476CFC0E408A339F/xs3qstsrc0288AD849FD5A3C1476CFC0E408A339F_1_1458034082.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0288AD849FD5A3C1476CFC0E408A339F/xs3qstsrc0288AD849FD5A3C1476CFC0E408A339F_1_1458034082.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-018-extra-p046",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 46,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён ромб. Найдите длину его большей диагонали.",
      "answer": "",
      "solution": "",
      "source_guid": "0548AB78BD539CEF4D4187BA2E821942",
      "source_number": "1C594B",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0548AB78BD539CEF4D4187BA2E821942/xs3qstsrc0548AB78BD539CEF4D4187BA2E821942_1_1458023702.png",
      "image_alt": "Иллюстрация к заданию 46",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"754\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён ромб. Найдите длину его большей диагонали.<span></span></p> </td> <td width=\"515\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0548AB78BD539CEF4D4187BA2E821942/xs3qstsrc0548AB78BD539CEF4D4187BA2E821942_1_1458023702.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/0548AB78BD539CEF4D4187BA2E821942/xs3qstsrc0548AB78BD539CEF4D4187BA2E821942_1_1458023702.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-018-extra-p059",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 59,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён прямоугольный треугольник. Найдите длину его большего катета.",
      "answer": "",
      "solution": "",
      "source_guid": "069740327DA2A57540ABE757418FFC3E",
      "source_number": "2BD44A",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.2 Треугольник\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069740327DA2A57540ABE757418FFC3E/xs3qstsrc069740327DA2A57540ABE757418FFC3E_1_1458011909.png",
      "image_alt": "Иллюстрация к заданию 59",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"826\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён прямоугольный треугольник. Найдите длину его большего катета.<span></span></p> </td> <td width=\"443\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069740327DA2A57540ABE757418FFC3E/xs3qstsrc069740327DA2A57540ABE757418FFC3E_1_1458011909.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069740327DA2A57540ABE757418FFC3E/xs3qstsrc069740327DA2A57540ABE757418FFC3E_1_1458011909.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-018-extra-p066",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 66,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён треугольник 𝐴⁢𝐵⁢𝐶. Найдите длину его средней линии, параллельной стороне 𝐴⁢𝐶.",
      "answer": "",
      "solution": "",
      "source_guid": "07476B41C43DA6214B2AEADC39796C80",
      "source_number": "D2D94B",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.2 Треугольник\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07476B41C43DA6214B2AEADC39796C80/xs3qstsrc07476B41C43DA6214B2AEADC39796C80_1_1458010479.png",
      "image_alt": "Иллюстрация к заданию 66",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"802\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён треугольник <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(5 0 3 1 4 2)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"5\" data-semantic-children=\"0,1,2\" data-semantic-content=\"3,4\" data-semantic-owns=\"0 3 1 4 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"5\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите длину его средней линии, параллельной стороне <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>.<span></span></p> </td> <td width=\"467\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07476B41C43DA6214B2AEADC39796C80/xs3qstsrc07476B41C43DA6214B2AEADC39796C80_1_1458010479.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07476B41C43DA6214B2AEADC39796C80/xs3qstsrc07476B41C43DA6214B2AEADC39796C80_1_1458010479.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-018-extra-p077",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 77,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён параллелограмм. Найдите его площадь.",
      "answer": "",
      "solution": "",
      "source_guid": "08CDD9E4582CAD6E4ACD738431394466",
      "source_number": "566A4E",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08CDD9E4582CAD6E4ACD738431394466/xs3qstsrc08CDD9E4582CAD6E4ACD738431394466_1_1458040485.png",
      "image_alt": "Иллюстрация к заданию 77",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"850\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён параллелограмм. Найдите его площадь.<span></span></p> </td> <td width=\"419\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08CDD9E4582CAD6E4ACD738431394466/xs3qstsrc08CDD9E4582CAD6E4ACD738431394466_1_1458040485.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08CDD9E4582CAD6E4ACD738431394466/xs3qstsrc08CDD9E4582CAD6E4ACD738431394466_1_1458040485.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-018-extra-p078",
      "subject": "Математика",
      "number": 18,
      "title": "Планиметрия (по клеткам)",
      "block": "",
      "page": 1,
      "item_number": 78,
      "prompt": "Впишите правильный ответ.",
      "question": "На клетчатой бумаге с размером клетки 1 ×1 изображён параллелограмм. Найдите его площадь.",
      "answer": "",
      "solution": "",
      "source_guid": "08D8A213544DA8C9435F01EDD153AEA3",
      "source_number": "5C5046",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08D8A213544DA8C9435F01EDD153AEA3/xs3qstsrc08D8A213544DA8C9435F01EDD153AEA3_1_1458040480.png",
      "image_alt": "Иллюстрация к заданию 78",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"850\" valign=\"top\"> <p class=\"MsoNormal\">На клетчатой бумаге с размером клетки <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 1 2)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,2\" data-semantic-content=\"1\" data-semantic-owns=\"0 1 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn><mjx-break size=\"3\"> </mjx-break><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-operator=\"infixop,×\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cD7\">×</mjx-c></mjx-mo><mjx-mn space=\"3\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\">1</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;изображён параллелограмм. Найдите его площадь.<span></span></p> </td> <td width=\"419\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><span><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08D8A213544DA8C9435F01EDD153AEA3/xs3qstsrc08D8A213544DA8C9435F01EDD153AEA3_1_1458040480.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/08D8A213544DA8C9435F01EDD153AEA3/xs3qstsrc08D8A213544DA8C9435F01EDD153AEA3_1_1458040480.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </span></p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
);

