window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push(
{
  "subject": "Математика",
  "number": 20,
  "title": "Задача повышенного уровня",
  "total_tasks": 36,
  "items": [
    {
      "id": "math-oge-020-p001",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 1,
      "item_number": 1,
      "prompt": "Решите задание.",
      "question_raw": "x^3+2x^2-x-2=0"
    },
    {
      "id": "math-oge-020-p002",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 2,
      "item_number": 2,
      "prompt": "Решите задание.",
      "question_raw": "x^3+2x^2=9x+18"
    },
    {
      "id": "math-oge-020-p030",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 14,
      "item_number": 14,
      "prompt": "Решите задание.",
      "question_raw": "x^3+3x^2-x-3=0"
    },
    {
      "id": "math-oge-020-p031",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 15,
      "item_number": 15,
      "prompt": "Решите задание.",
      "question_raw": "x^3+5x^2-9x-45=0"
    },
    {
      "id": "math-oge-020-p032",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 16,
      "item_number": 16,
      "prompt": "Решите задание.",
      "question_raw": "x^3+5x^2-9x-45=0"
    },
    {
      "id": "math-oge-020-p033",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 17,
      "item_number": 17,
      "prompt": "Решите задание.",
      "question_raw": "(x-1)(x^2+6x+9)=5(x+3)"
    },
    {
      "id": "math-oge-020-p034",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 18,
      "item_number": 18,
      "prompt": "Решите задание.",
      "question_raw": "x*(x^2+6x+9)=4(x+3)"
    },
    {
      "id": "math-oge-020-p035",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 19,
      "item_number": 19,
      "prompt": "Решите задание.",
      "question_raw": "x*(x^2+2x+1)=2(x+1)"
    },
    {
      "id": "math-oge-020-p036",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 20,
      "item_number": 20,
      "prompt": "Решите задание.",
      "question_raw": "(x-2)(x^2+6x+9)=6(x+3)"
    },
    {
      "id": "math-oge-020-p003",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 3,
      "item_number": 3,
      "prompt": "Решите задание.",
      "question_raw": "(x-1)*(x^2+8x+16)=6(x+4)"
    },
    {
      "id": "math-oge-020-p004",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 4,
      "item_number": 4,
      "prompt": "Решите задание.",
      "question_raw": "x^4=(2x-3)^2"
    },
    {
      "id": "math-oge-020-p005",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 5,
      "item_number": 5,
      "prompt": "Решите задание.",
      "question_raw": "(x^2-9)^2+(x^2+x-6)^2=0"
    },
    {
      "id": "math-oge-020-p006",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 6,
      "item_number": 6,
      "prompt": "Решите задание.",
      "question_raw": "x^2-2x+\\sqrt{3-x}=\\sqrt{3-x}+8"
    },
    {
      "id": "math-oge-020-p007",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 7,
      "item_number": 7,
      "prompt": "Решите задание.",
      "question_raw": "1/x^2+4/x-12=0"
    },
    {
      "id": "math-oge-020-p008",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 8,
      "item_number": 8,
      "prompt": "Решите задание.",
      "question_raw": "1/(x-1)^2+2/(x-1)-3=0"
    },
    {
      "id": "math-oge-020-p009",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 9,
      "item_number": 9,
      "prompt": "Решите задание.",
      "question_raw": "(x-3)^4-3(x-3)^2-10=0"
    },
    {
      "id": "math-oge-020-p010",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 10,
      "item_number": 10,
      "prompt": "Решите задание.",
      "question_raw": "3x^2+y=6; 4x^2-y=1"
    },
    {
      "id": "math-oge-020-p011",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 11,
      "item_number": 11,
      "prompt": "Решите задание.",
      "question_raw": "\n\n{2x^2-5x=y\n2x-5=y."
    },
    {
      "id": "math-oge-020-p012",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 12,
      "item_number": 12,
      "prompt": "Решите задание.",
      "question_raw": "3x^2+2y^2=45;9x^2+6y^2=45x"
    },
    {
      "id": "math-oge-020-p013",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Уравнения №20",
      "page": 13,
      "item_number": 13,
      "prompt": "Решите задание.",
      "question_raw": "28a-7b+40; 2a-5b+7; 5a-2b+7=6"
    },
    {
      "id": "math-oge-020-p014",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 1,
      "item_number": 1,
      "prompt": "Решите задание.",
      "question_raw": "(x-1)^2<2(x-1)"
    },
    {
      "id": "math-oge-020-p015",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 2,
      "item_number": 2,
      "prompt": "Решите задание.",
      "question_raw": "-15(x+1)^2-3>0"
    },
    {
      "id": "math-oge-020-p016",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 3,
      "item_number": 3,
      "prompt": "Решите задание.",
      "question_raw": "x^2<49x"
    },
    {
      "id": "math-oge-020-p017",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 4,
      "item_number": 4,
      "prompt": "Решите задание.",
      "question_raw": "x^2<16x"
    },
    {
      "id": "math-oge-020-p018",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 5,
      "item_number": 5,
      "prompt": "Решите задание.",
      "question_raw": "x^2/(x-5)>x"
    },
    {
      "id": "math-oge-020-p019",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 6,
      "item_number": 6,
      "prompt": "Решите задание.",
      "question_raw": "x^2/(x-3)>x"
    },
    {
      "id": "math-oge-020-p020",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 7,
      "item_number": 7,
      "prompt": "Решите задание.",
      "question_raw": "1/x>1/(x-3)"
    },
    {
      "id": "math-oge-020-p021",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 8,
      "item_number": 8,
      "prompt": "Решите задание.",
      "question_raw": "1/x>1/(x-5)"
    },
    {
      "id": "math-oge-020-p022",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 9,
      "item_number": 9,
      "prompt": "Решите задание.",
      "question_raw": "(x^2-7)/(x+12)+(x)/(x-3)>0"
    },
    {
      "id": "math-oge-020-p023",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 10,
      "item_number": 10,
      "prompt": "Решите задание.",
      "question_raw": "(2x^2-16)/(x+32)+(x+6)>0"
    },
    {
      "id": "math-oge-020-p024",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 11,
      "item_number": 11,
      "prompt": "Решите задание.",
      "question_raw": "(9-x)(x^2-81)>0"
    },
    {
      "id": "math-oge-020-p025",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 12,
      "item_number": 12,
      "prompt": "Решите задание.",
      "question_raw": "(3-x)(x^2-9)>0"
    },
    {
      "id": "math-oge-020-p026",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 13,
      "item_number": 13,
      "prompt": "Решите задание.",
      "question_raw": "(4-x)(x^2+x-20)>0"
    },
    {
      "id": "math-oge-020-p027",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 14,
      "item_number": 14,
      "prompt": "Решите задание.",
      "question_raw": "(3-x)(x^2+4x-21)>0"
    },
    {
      "id": "math-oge-020-p028",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 15,
      "item_number": 15,
      "prompt": "Решите задание.",
      "question_raw": "(x^2+3x-18)(x^2-5x+6)>0"
    },
    {
      "id": "math-oge-020-p029",
      "subject": "Математика",
      "number": 20,
      "title": "Задача повышенного уровня",
      "block": "Неравенства №20",
      "page": 16,
      "item_number": 16,
      "prompt": "Решите задание.",
      "question_raw": "(x^2+x-12)(x^2+x-20)>0"
    },
    {
      "id": "math-oge-007-p018",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 18,
      "prompt": "Дайте развернутый ответ.",
      "question": "Решите неравенство",
      "answer": "",
      "solution": "",
      "source_guid": "01B98FD3FD15957D4CE88AAED0C1CADE",
      "source_number": "F5A849",
      "source_answer_type": "Развернутый ответ",
      "source_kes": "3.2 Целые и дробно-рациональные неравенства. Системы и совокупности неравенств",
      "source_hint": "Дайте развернутый ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01B98FD3FD15957D4CE88AAED0C1CADE/innerimg0.gif",
      "image_alt": "Иллюстрация к заданию 18",
      "source_question_html": "<p class=\"Basis\"><span style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">Решите\n  неравенство </span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\"><span style=\"position:relative;top:6.0pt\"><script language=\"JavaScript\">ShowPictureQ(\"docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01B98FD3FD15957D4CE88AAED0C1CADE/innerimg0.gif\",\"\");</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01B98FD3FD15957D4CE88AAED0C1CADE/innerimg0.gif\" align=\"ABSMIDDLE\" alt=\"\" border=\"0\"> </span></span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">&nbsp;</span></p>",
      "source_variants_html": "&nbsp;"
    },
    {
      "id": "math-oge-007-p047",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 47,
      "prompt": "Дайте развернутый ответ.",
      "question": "Решите неравенство",
      "answer": "",
      "solution": "",
      "source_guid": "056DD121E615812D428A159FEBDF3BC4",
      "source_number": "166F42",
      "source_answer_type": "Развернутый ответ",
      "source_kes": "3.2 Целые и дробно-рациональные неравенства. Системы и совокупности неравенств",
      "source_hint": "Дайте развернутый ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/056DD121E615812D428A159FEBDF3BC4/innerimg0.gif",
      "image_alt": "Иллюстрация к заданию 47",
      "source_question_html": "<p class=\"Basis\"><span style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">Решите\n  неравенство </span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\"><span style=\"position:relative;top:6.0pt\"><script language=\"JavaScript\">ShowPictureQ(\"docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/056DD121E615812D428A159FEBDF3BC4/innerimg0.gif\",\"\");</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/056DD121E615812D428A159FEBDF3BC4/innerimg0.gif\" align=\"ABSMIDDLE\" alt=\"\" border=\"0\"> </span></span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">&nbsp;</span></p>",
      "source_variants_html": "&nbsp;"
    },
    {
      "id": "math-oge-007-p058",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 58,
      "prompt": "Дайте развернутый ответ.",
      "question": "Решите неравенство",
      "answer": "",
      "solution": "",
      "source_guid": "069294FD06A4A6534AA5B62F62B8B3EA",
      "source_number": "2A0B4A",
      "source_answer_type": "Развернутый ответ",
      "source_kes": "3.2 Целые и дробно-рациональные неравенства. Системы и совокупности неравенств",
      "source_hint": "Дайте развернутый ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069294FD06A4A6534AA5B62F62B8B3EA/innerimg0.gif",
      "image_alt": "Иллюстрация к заданию 58",
      "source_question_html": "<p class=\"Basis\"><span style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">Решите\n  неравенство </span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\"><span style=\"position:relative;top:6.0pt\"><script language=\"JavaScript\">ShowPictureQ(\"docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069294FD06A4A6534AA5B62F62B8B3EA/innerimg0.gif\",\"\");</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/069294FD06A4A6534AA5B62F62B8B3EA/innerimg0.gif\" align=\"ABSMIDDLE\" alt=\"\" border=\"0\"> </span></span><span lang=\"EN-US\" style=\"font-size:14.0pt;font-family:&quot;Times New Roman&quot;,serif\">&nbsp;</span></p>",
      "source_variants_html": "&nbsp;"
    }
  ]
}
);
