window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push(
{
  id: "math-oge-017-p001",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 1,
  prompt: "Решите задачу.",
  intro: "Один из углов прямоугольной трапеции равен 64°.",
  image: "images/task-17/task-17-001.png",
  image_alt: "Прямоугольная трапеция",
  question_text: "Найдите больший угол этой трапеции. Ответ дайте в градусах.",
  answer: "116",
  solution: "Соседние углы при боковой стороне дополняют друг друга до 180°: 180 − 64 = 116."
},
{
  id: "math-oge-017-p002",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 2,
  prompt: "Решите задачу.",
  intro: "Диагонали AC и BD параллелограмма ABCD пересекаются в точке O, AC = 22, BD = 24.",
  image: "images/task-17/task-17-002.png",
  image_alt: "Параллелограмм с диагоналями",
  question_text: "Найдите DO.",
  answer: "12",
  solution: "Диагонали параллелограмма делятся пополам: DO = BD/2 = 12."
},
{
  id: "math-oge-017-p003",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 3,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 11√2.",
  image: "images/task-17/task-17-003.png",
  image_alt: "Квадрат",
  question_text: "Найдите диагональ этого квадрата.",
  answer: "22",
  solution: "d = a√2 = 11√2 · √2 = 22."
},
{
  id: "math-oge-017-p004",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 4,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 1 и 19.",
  image: "images/task-17/task-17-004.png",
  image_alt: "Трапеция с диагональю",
  question_text: "Найдите больший из отрезков, на которые делит среднюю линию этой трапеции одна из её диагоналей.",
  answer: "9.5",
  solution: "Диагональ делит среднюю линию на отрезки, равные половинам оснований: 19/2 = 9.5 (больший)."
},
{
  id: "math-oge-017-p005",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 5,
  prompt: "Решите задачу.",
  intro: "Сторона ромба равна 34, один из углов равен 150°.",
  image: "images/task-17/task-17-005.png",
  image_alt: "Ромб",
  question_text: "Найдите высоту этого ромба.",
  answer: "17",
  solution: "h = a·sinα = 34·sin150° = 34·1/2 = 17."
},
{
  id: "math-oge-017-p006",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 6,
  prompt: "Решите задачу.",
  intro: "В равнобедренной трапеции известны высота, меньшее основание и угол при основании.",
  image: "images/task-17/task-17-006.png",
  image_alt: "Равнобедренная трапеция",
  question_text: "Найдите большее основание.",
  answer: "см. рисунок",
  solution: "Через проекцию боковой стороны: разность оснований = 2·h·ctg(угла). Затем прибавить к меньшему основанию."
},
{
  id: "math-oge-017-p007",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 7,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 8 и 18, высота равна 5.",
  image: "images/task-17/task-17-007.png",
  image_alt: "Трапеция",
  question_text: "Найдите среднюю линию этой трапеции.",
  answer: "13",
  solution: "Средняя линия = (a + b)/2 = (8 + 18)/2 = 13."
},
{
  id: "math-oge-017-p008",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 8,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 11 и 19, высота равна 9.",
  image: "images/task-17/task-17-007.png",
  image_alt: "Трапеция",
  question_text: "Найдите среднюю линию этой трапеции.",
  answer: "15",
  solution: "Средняя линия = (11 + 19)/2 = 15."
},
{
  id: "math-oge-017-p009",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 9,
  prompt: "Решите задачу.",
  intro: "Один из углов равнобедренной трапеции равен 131°.",
  image: "images/task-17/task-17-008png",
  image_alt: "Равнобедренная трапеция",
  question_text: "Найдите меньший угол этой трапеции. Ответ дайте в градусах.",
  answer: "49",
  solution: "Соседние углы в трапеции дополняют до 180°: 180 − 131 = 49."
},
{
  id: "math-oge-017-p010",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 10,
  prompt: "Решите задачу.",
  intro: "В параллелограмме ABCD биссектриса угла A образует со стороной BC угол 33°.",
  image: "images/task-17/task-17-009.png",
  image_alt: "Параллелограмм с биссектрисой",
  question_text: "Найдите острый угол параллелограмма. Ответ дайте в градусах.",
  answer: "66",
  solution: "Биссектриса делит угол пополам: угол A = 2·33 = 66°."
},
{
  id: "math-oge-017-p011",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 11,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 1 и 5, высота равна 3.",
  image: "images/task-17/task-17-007.png",
  image_alt: "Трапеция",
  question_text: "Найдите среднюю линию этой трапеции.",
  answer: "3",
  solution: "Средняя линия = (a + b)/2 = (1 + 5)/2 = 3."
},
{
  id: "math-oge-017-p012",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 12,
  prompt: "Решите задачу.",
  intro: "В параллелограмме ABCD биссектриса угла A образует со стороной BC угол 41°.",
  image: "images/task-17/task-17-009.png",
  image_alt: "Параллелограмм с биссектрисой",
  question_text: "Найдите острый угол параллелограмма. Ответ дайте в градусах.",
  answer: "82",
  solution: "Угол A = 2·41 = 82°."
},
{
  id: "math-oge-017-p013",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 13,
  prompt: "Решите задачу.",
  intro: "Диагонали AC и BD параллелограмма ABCD пересекаются в точке O, AC = 12, BD = 20.",
  image: "images/task-17/task-17-002.png",
  image_alt: "Параллелограмм с диагоналями",
  question_text: "Найдите DO.",
  answer: "10",
  solution: "Диагонали делятся пополам: DO = BD/2 = 10."
},
{
  id: "math-oge-017-p014",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 14,
  prompt: "Решите задачу.",
  intro: "Диагональ BD параллелограмма ABCD образует с его сторонами углы 65° и 50°.",
  image: "images/task-17/task-17-010.png",
  image_alt: "Параллелограмм с диагональю",
  question_text: "Найдите меньший угол этого параллелограмма. Ответ дайте в градусах.",
  answer: "65",
  solution: "Угол параллелограмма равен сумме углов между диагональю и сторонами: 65 + 50 = 115°, меньший = 180 − 115 = 65°."
},
{
  id: "math-oge-017-p015",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 15,
  prompt: "Решите задачу.",
  intro: "Радиус окружности, вписанной в прямоугольную трапецию, равен 10.",
  image: "images/task-17/task-17-011.png",
  image_alt: "Прямоугольная трапеция",
  question_text: "Найдите высоту этой трапеции.",
  answer: "20",
  solution: "Высота равна диаметру вписанной окружности: h = 2r = 20."
},
{
  id: "math-oge-017-p016",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 16,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 26.",
  image: "images/task-17/task-17-012.png",
  image_alt: "Квадрат",
  question_text: "Найдите радиус окружности, вписанной в этот квадрат.",
  answer: "13",
  solution: "r = a/2 = 26/2 = 13."
},
{
  id: "math-oge-017-p017",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 17,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 2√2.",
  image: "images/task-17/task-17-003.png",
  image_alt: "Квадрат",
  question_text: "Найдите диагональ этого квадрата.",
  answer: "4",
  solution: "d = a√2 = 2√2 · √2 = 4."
},
{
  id: "math-oge-017-p018",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 18,
  prompt: "Решите задачу.",
  intro: "Радиус окружности, описанной около квадрата, равен 4√2.",
  image: "images/task-17/task-17-013.png",
  image_alt: "Квадрат и окружность",
  question_text: "Найдите длину стороны этого квадрата.",
  answer: "8",
  solution: "R = d/2, d = a√2 → a = (2R)/√2 = (2·4√2)/√2 = 8."
},
{
  id: "math-oge-017-p019",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 19,
  prompt: "Решите задачу.",
  intro: "Периметр ромба равен 56, один из углов равен 30°.",
  image: "images/task-17/task-17-014.png",
  image_alt: "Ромб",
  question_text: "Найдите площадь этого ромба.",
  answer: "98",
  solution: "a = 56/4 = 14, S = a²·sin30° = 196·1/2 = 98."
},
{
  id: "math-oge-017-p020",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 20,
  prompt: "Решите задачу.",
  intro: "В ромбе ABCD угол ABC равен 84°.",
  image: "images/task-17/task-17-015.png",
  image_alt: "Ромб",
  question_text: "Найдите угол ACD. Ответ дайте в градусах.",
  answer: "48",
  solution: "∠C = 180 − 84 = 96°, диагональ делит угол пополам → 96/2 = 48."
},
{
  id: "math-oge-017-p021",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 21,
  prompt: "Решите задачу.",
  intro: "Один из углов параллелограмма равен 74°.",
  image: "images/task-17/task-17-014.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите больший угол этого параллелограмма. Ответ дайте в градусах.",
  answer: "106",
  solution: "Смежные углы: 180 − 74 = 106."
},
{
  id: "math-oge-017-p022",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 22,
  prompt: "Решите задачу.",
  intro: "Диагональ прямоугольника образует угол 51° с одной из его сторон.",
  image: "images/task-17/task-17-016.png",
  image_alt: "Прямоугольник",
  question_text: "Найдите острый угол между диагоналями этого прямоугольника. Ответ дайте в градусах.",
  answer: "78",
  solution: "Острый угол между диагоналями равен 180 − 2·51 = 78."
},
{
  id: "math-oge-017-p023",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 23,
  prompt: "Решите задачу.",
  intro: "Один из углов равнобедренной трапеции равен 29°.",
  image: "images/task-17/task-17-008.png",
  image_alt: "Равнобедренная трапеция",
  question_text: "Найдите больший угол этой трапеции. Ответ дайте в градусах.",
  answer: "151",
  solution: "Смежные углы: 180 − 29 = 151."
},
{
  id: "math-oge-017-p024",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 24,
  prompt: "Решите задачу.",
  intro: "Радиус окружности, вписанной в трапецию, равен 36.",
  image: "images/task-17/task-17-011.png",
  image_alt: "Трапеция с вписанной окружностью",
  question_text: "Найдите высоту этой трапеции.",
  answer: "72",
  solution: "Высота равна диаметру: h = 2r = 72."
},
{
  id: "math-oge-017-p025",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 25,
  prompt: "Решите задачу.",
  intro: "Радиус окружности, вписанной в равнобедренную трапецию, равен 22.",
  image: "images/task-17/task-17-017.png",
  image_alt: "Равнобедренная трапеция",
  question_text: "Найдите высоту этой трапеции.",
  answer: "44",
  solution: "h = 2r = 44."
},
{
  id: "math-oge-017-p026",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 26,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 1 и 17.",
  image: "images/task-17/task-17-004.png",
  image_alt: "Трапеция",
  question_text: "Найдите больший из отрезков, на которые делит среднюю линию этой трапеции одна из её диагоналей.",
  answer: "8.5",
  solution: "Больший отрезок равен половине большего основания: 17/2 = 8.5."
},
{
  id: "math-oge-017-p027",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 27,
  prompt: "Решите задачу.",
  intro: "Периметр ромба равен 36, один из углов равен 30°.",
  image: "images/task-17/task-17-014.png",
  image_alt: "Ромб",
  question_text: "Найдите площадь этого ромба.",
  answer: "40.5",
  solution: "a = 36/4 = 9, S = a²·sin30° = 81·0.5 = 40.5."
},
{
  id: "math-oge-017-p028",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 28,
  prompt: "Решите задачу.",
  intro: "Основания трапеции равны 7 и 19, высота равна 6.",
  image: "images/task-17/task-17-007.png",
  image_alt: "Трапеция",
  question_text: "Найдите площадь этой трапеции.",
  answer: "78",
  solution: "S = (a + b)/2 · h = (7 + 19)/2 · 6 = 78."
},
{
  id: "math-oge-017-p029",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 29,
  prompt: "Решите задачу.",
  intro: "Сторона ромба равна 46, один из углов равен 150°.",
  image: "images/task-17/task-17-014.png",
  image_alt: "Ромб",
  question_text: "Найдите высоту этого ромба.",
  answer: "23",
  solution: "h = a·sin150° = 46·0.5 = 23."
},
{
  id: "math-oge-017-p030",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 30,
  prompt: "Решите задачу.",
  intro: "Диагональ BD параллелограмма ABCD образует с его сторонами углы 65° и 80°.",
  image: "images/task-17/task-17-018.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите меньший угол этого параллелограмма. Ответ дайте в градусах.",
  answer: "35",
  solution: "Угол = 65 + 80 = 145°, меньший = 180 − 145 = 35°."
},
{
  id: "math-oge-017-p031",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 31,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 24√2.",
  image: "images/task-17/task-17-013.png",
  image_alt: "Квадрат",
  question_text: "Найдите радиус окружности, описанной около этого квадрата.",
  answer: "24",
  solution: "R = d/2 = a√2/2 = 24√2·√2/2 = 24."
},
{
  id: "math-oge-017-p032",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 32,
  prompt: "Решите задачу.",
  intro: "Один из углов параллелограмма равен 91°.",
  image: "images/task-17/task-17-014.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите меньший угол этого параллелограмма. Ответ дайте в градусах.",
  answer: "89",
  solution: "Смежные углы: 180 − 91 = 89."
},
{
  id: "math-oge-017-p033",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 33,
  prompt: "Решите задачу.",
  intro: "Радиус окружности, описанной около квадрата, равен 18√2.",
  image: "images/task-17/task-17-013.png",
  image_alt: "Квадрат",
  question_text: "Найдите длину стороны этого квадрата.",
  answer: "36",
  solution: "R = d/2, d = a√2 → a = (2R)/√2 = (2·18√2)/√2 = 36."
},
{
  id: "math-oge-017-p034",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 34,
  prompt: "Решите задачу.",
  intro: "Радиус вписанной в квадрат окружности равен 14√2.",
  image: "images/task-17/task-17-012.png",
  image_alt: "Квадрат",
  question_text: "Найдите диагональ этого квадрата.",
  answer: "56",
  solution: "r = a/2 → a = 28√2, d = a√2 = 28√2·√2 = 56."
},
{
  id: "math-oge-017-p035",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 35,
  prompt: "Решите задачу.",
  intro: "Трапеция ABCD с основаниями AD и BC описана около окружности, AB = 11, BC = 6, CD = 9.",
  image: "images/task-17/task-17-021.png",
  image_alt: "Трапеция с вписанной окружностью",
  question_text: "Найдите AD.",
  answer: "14",
  solution: "В описанной трапеции суммы противоположных сторон равны: AD + BC = AB + CD → AD + 6 = 11 + 9 → AD = 14."
},
{
  id: "math-oge-017-p036",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 36,
  prompt: "Решите задачу.",
  intro: "Сторона квадрата равна 46.",
  image: "images/task-17/task-17-013.png",
  image_alt: "Квадрат",
  question_text: "Найдите радиус окружности, вписанной в этот квадрат.",
  answer: "23",
  solution: "r = a/2 = 46/2 = 23."
},
{
  id: "math-oge-017-p037",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 37,
  prompt: "Решите задачу.",
  intro: "Угол A трапеции ABCD с основаниями AD и BC, вписанной в окружность, равен 35°.",
  image: "images/task-17/task-17-021.png",
  image_alt: "Трапеция, вписанная в окружность",
  question_text: "Найдите угол B этой трапеции. Ответ дайте в градусах.",
  answer: "145",
  solution: "Вписанная трапеция — равнобедренная, ∠A + ∠B = 180° → B = 180 − 35 = 145."
},
{
  id: "math-oge-017-p038",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 38,
  prompt: "Решите задачу.",
  intro: "Диагональ прямоугольника образует угол 44° с одной из его сторон.",
  image: "images/task-17/task-17-016.png",
  image_alt: "Прямоугольник",
  question_text: "Найдите острый угол между диагоналями этого прямоугольника. Ответ дайте в градусах.",
  answer: "92",
  solution: "Острый угол между диагоналями равен 2·44 = 88? Но берётся дополнительный: 180 − 2·44 = 92."
},
{
  id: "math-oge-017-p039",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 39,
  prompt: "Решите задачу.",
  intro: "Площадь параллелограмма равна 40, его стороны равны 5 и 10.",
  image: "images/task-17/task-17-022.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите его высоты. В ответе укажите большую высоту.",
  answer: "8",
  solution: "h₁ = S/a = 40/5 = 8, h₂ = 40/10 = 4 → большая 8."
},
{
  id: "math-oge-017-p040",
  subject: "Математика",
  number: 17,
  title: "Планиметрия",
  block: "Скриншоты",
  task_group: 1,
  item_number: 40,
  prompt: "Решите задачу.",
  intro: "Площадь параллелограмма равна 30, его стороны равны 6 и 10.",
  image: "images/task-17/task-17-022.png",
  image_alt: "Параллелограмм",
  question_text: "Найдите его высоты. В ответе укажите большую высоту.",
  answer: "5",
  solution: "h₁ = 30/6 = 5, h₂ = 30/10 = 3 → большая 5."
},
{
      "id": "math-oge-017-extra-p012",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 12,
      "prompt": "Впишите правильный ответ.",
      "question": "Диагонали 𝐴⁢𝐶 и 𝐵⁢𝐷 параллелограмма 𝐴⁢𝐵⁢𝐶⁢𝐷 пересекаются в точке 𝑂, 𝐴⁢𝐶 =22, 𝐵⁢𝐷 =24, 𝐴⁢𝐵 =3. Найдите 𝐷⁢𝑂.",
      "answer": "",
      "solution": "",
      "source_guid": "015335B180948987409BF365FB1D329B",
      "source_number": "F77141",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/015335B180948987409BF365FB1D329B/xs3qstsrc015335B180948987409BF365FB1D329B_1_1487180861.png",
      "image_alt": "Иллюстрация к заданию 12",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/015335B180948987409BF365FB1D329B/xs3qstsrc015335B180948987409BF365FB1D329B_1_1487180861.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/015335B180948987409BF365FB1D329B/xs3qstsrc015335B180948987409BF365FB1D329B_1_1487180861.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Диагонали <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;и <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;параллелограмма <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(7 0 4 1 5 2 6 3)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"7\" data-semantic-children=\"0,1,2,3\" data-semantic-content=\"4,5,6\" data-semantic-owns=\"0 4 1 5 2 6 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;пересекаются в точке <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D442\">𝑂</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(6 (5 0 4 1) 2 3)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"6\" data-semantic-children=\"5,3\" data-semantic-content=\"2\" data-semantic-owns=\"5 2 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:2\" data-semantic-id=\"5\" data-semantic-children=\"0,1\" data-semantic-content=\"4\" data-semantic-parent=\"6\" data-semantic-owns=\"0 4 1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"6\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mn space=\"4\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"6\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\" noic=\"true\" style=\"padding-top: 0.666em;\">2</mjx-c><mjx-c class=\"mjx-c32\" style=\"padding-top: 0.666em;\">2</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(6 (5 0 4 1) 2 3)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"6\" data-semantic-children=\"5,3\" data-semantic-content=\"2\" data-semantic-owns=\"5 2 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:2\" data-semantic-id=\"5\" data-semantic-children=\"0,1\" data-semantic-content=\"4\" data-semantic-parent=\"6\" data-semantic-owns=\"0 4 1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"6\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mn space=\"4\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"6\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\" noic=\"true\" style=\"padding-top: 0.677em;\">2</mjx-c><mjx-c class=\"mjx-c34\" style=\"padding-top: 0.677em;\">4</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(6 (5 0 4 1) 2 3)\" breakable=\"true\" class=\"NCM-N\"><mjx-mstyle inline-breaks=\"true\"><mjx-semantics inline-breaks=\"true\"><mjx-mrow data-semantic-type=\"relseq\" data-semantic-role=\"equality\" data-semantic-annotation=\"depth:1\" data-semantic-id=\"6\" data-semantic-children=\"5,3\" data-semantic-content=\"2\" data-semantic-owns=\"5 2 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\" inline-breaks=\"true\"><mjx-mrow data-semantic-added=\"true\" data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:2\" data-semantic-id=\"5\" data-semantic-children=\"0,1\" data-semantic-content=\"4\" data-semantic-parent=\"6\" data-semantic-owns=\"0 4 1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:3\" data-semantic-id=\"0\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:3\" data-semantic-id=\"4\" data-semantic-parent=\"5\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"5\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi></mjx-mrow><mjx-break size=\"4\"> </mjx-break><mjx-mo data-semantic-type=\"relation\" data-semantic-role=\"equality\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"6\" data-semantic-operator=\"relseq,=\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c3D\">=</mjx-c></mjx-mo><mjx-mn space=\"4\" data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"6\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c33\">3</mjx-c></mjx-mn></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D442\">𝑂</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
{
      "id": "math-oge-017-extra-p017",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 17,
      "prompt": "Впишите правильный ответ.",
      "question": "Сторона квадрата равна 11⁢√2. Найдите диагональ этого квадрата.",
      "answer": "",
      "solution": "",
      "source_guid": "01A59B7F5AE1B6E24A5D11079A2F1C12",
      "source_number": "FA194C",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01A59B7F5AE1B6E24A5D11079A2F1C12/xs3qstsrc01A59B7F5AE1B6E24A5D11079A2F1C12_1_1485780082.png",
      "image_alt": "Иллюстрация к заданию 17",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01A59B7F5AE1B6E24A5D11079A2F1C12/xs3qstsrc01A59B7F5AE1B6E24A5D11079A2F1C12_1_1485780082.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/01A59B7F5AE1B6E24A5D11079A2F1C12/xs3qstsrc01A59B7F5AE1B6E24A5D11079A2F1C12_1_1485780082.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Сторона квадрата равна <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(4 0 3 (2 1))\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"4\" data-semantic-children=\"0,2\" data-semantic-content=\"3\" data-semantic-owns=\"0 3 2\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"4\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.666em;\">1</mjx-c><mjx-c class=\"mjx-c31\" style=\"padding-top: 0.666em;\">1</mjx-c></mjx-mn><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"4\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-msqrt data-semantic-type=\"sqrt\" data-semantic-role=\"unknown\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-children=\"1\" data-semantic-parent=\"4\" data-semantic-owns=\"1\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-sqrt><mjx-surd><mjx-mo><mjx-c class=\"mjx-c221A\">√</mjx-c></mjx-mo></mjx-surd><mjx-box style=\"padding-top: 0.222em;\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;depth:3\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-level-number=\"2\" data-speech-node=\"true\"><mjx-c class=\"mjx-c32\">2</mjx-c></mjx-mn></mjx-box></mjx-sqrt></mjx-msqrt></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите диагональ этого квадрата.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-017-extra-p045",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 45,
      "prompt": "Впишите правильный ответ.",
      "question": "Основания трапеции равны 1 и 19. Найдите больший из отрезков, на которые делит среднюю линию этой трапеции одна из её диагоналей.",
      "answer": "",
      "solution": "",
      "source_guid": "053D0C62D2ACB6274BCB69971255FE19",
      "source_number": "146E47",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/053D0C62D2ACB6274BCB69971255FE19/xs3qstsrc053D0C62D2ACB6274BCB69971255FE19_1_1456478366.png",
      "image_alt": "Иллюстрация к заданию 45",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"898\" valign=\"top\"> <p class=\"MsoNormal\">Основания трапеции равны 1 и 19. Найдите больший из отрезков, на которые делит среднюю линию этой трапеции одна из её диагоналей.</p> </td> <td width=\"372\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/053D0C62D2ACB6274BCB69971255FE19/xs3qstsrc053D0C62D2ACB6274BCB69971255FE19_1_1456478366.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/053D0C62D2ACB6274BCB69971255FE19/xs3qstsrc053D0C62D2ACB6274BCB69971255FE19_1_1456478366.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-017-extra-p050",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 50,
      "prompt": "Впишите правильный ответ.",
      "question": "Сторона ромба равна 34, а один из углов этого ромба равен 150°. Найдите высоту этого ромба.",
      "answer": "",
      "solution": "",
      "source_guid": "05B46A146CC8ACB940708A4B28F64F21",
      "source_number": "12BC49",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/05B46A146CC8ACB940708A4B28F64F21/xs3qstsrc05B46A146CC8ACB940708A4B28F64F21_1_1485785224.png",
      "image_alt": "Иллюстрация к заданию 50",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td width=\"191\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/05B46A146CC8ACB940708A4B28F64F21/xs3qstsrc05B46A146CC8ACB940708A4B28F64F21_1_1485785224.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/05B46A146CC8ACB940708A4B28F64F21/xs3qstsrc05B46A146CC8ACB940708A4B28F64F21_1_1485785224.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Сторона ромба равна 34, а один из углов этого ромба равен <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"endpunct\" data-semantic-annotation=\"clearspeak:simple;depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-content=\"1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c31\" noic=\"true\" style=\"padding-top: 0.666em;\">1</mjx-c><mjx-c class=\"mjx-c35\" noic=\"true\" style=\"padding-top: 0.666em;\">5</mjx-c><mjx-c class=\"mjx-c30\" style=\"padding-top: 0.666em;\">0</mjx-c></mjx-mn><mjx-mi data-semantic-type=\"punctuation\" data-semantic-role=\"degree\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-operator=\"punctuated\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cB0 NCM-I\">°</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите высоту этого ромба.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-017-extra-p065",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 65,
      "prompt": "Впишите правильный ответ.",
      "question": "В равнобедренной трапеции известны высота, меньшее основание и угол\nпри основании (см. рисунок). Найдите большее основание.",
      "answer": "",
      "solution": "",
      "source_guid": "07378B41D3E3A7734BABED5EC6E55449",
      "source_number": "D5D947",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.2 Треугольник\n7.3 Многоугольники",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07378B41D3E3A7734BABED5EC6E55449/xs3qstsrc07378B41D3E3A7734BABED5EC6E55449_1_1456397364.png",
      "image_alt": "Иллюстрация к заданию 65",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\"> <tbody><tr> <td width=\"659\" valign=\"top\"> <p class=\"MsoNormal\">В равнобедренной трапеции известны высота, меньшее основание и угол <br> при основании (см. рисунок). Найдите большее основание.</p> </td> <td width=\"610\" valign=\"top\"> <p class=\"MsoNormal\" align=\"right\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07378B41D3E3A7734BABED5EC6E55449/xs3qstsrc07378B41D3E3A7734BABED5EC6E55449_1_1456397364.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/07378B41D3E3A7734BABED5EC6E55449/xs3qstsrc07378B41D3E3A7734BABED5EC6E55449_1_1456397364.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-017-extra-p068",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 68,
      "prompt": "Впишите правильный ответ.",
      "question": "Угол 𝐴 трапеции 𝐴⁢𝐵⁢𝐶⁢𝐷 с основаниями 𝐴⁢𝐷 и 𝐵⁢𝐶, вписанной в окружность, равен 59°. Найдите угол 𝐵 этой трапеции. Ответ дайте в градусах.",
      "answer": "",
      "solution": "",
      "source_guid": "077F8E596CCAAD01414C98786389A0F0",
      "source_number": "D5834D",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.4 Окружность и круг\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/077F8E596CCAAD01414C98786389A0F0/xs3qstsrc077F8E596CCAAD01414C98786389A0F0_1_1485519703.png",
      "image_alt": "Иллюстрация к заданию 68",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/077F8E596CCAAD01414C98786389A0F0/xs3qstsrc077F8E596CCAAD01414C98786389A0F0_1_1485519703.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/077F8E596CCAAD01414C98786389A0F0/xs3qstsrc077F8E596CCAAD01414C98786389A0F0_1_1485519703.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Угол <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;трапеции <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(7 0 4 1 5 2 6 3)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:unit;depth:1\" data-semantic-id=\"7\" data-semantic-children=\"0,1,2,3\" data-semantic-content=\"4,5,6\" data-semantic-owns=\"0 4 1 5 2 6 3\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"4\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"5\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"6\" data-semantic-parent=\"7\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"3\" data-semantic-parent=\"7\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;с основаниями <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D434\">𝐴</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D437\">𝐷</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;и <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(3 0 2 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"infixop\" data-semantic-role=\"implicit\" data-semantic-annotation=\"clearspeak:simple;clearspeak:unit;depth:1\" data-semantic-id=\"3\" data-semantic-children=\"0,1\" data-semantic-content=\"2\" data-semantic-owns=\"0 2 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi><mjx-mo data-semantic-type=\"operator\" data-semantic-role=\"multiplication\" data-semantic-annotation=\"depth:2\" data-semantic-id=\"2\" data-semantic-parent=\"3\" data-semantic-added=\"true\" data-semantic-operator=\"infixop,⁢\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c2062\">⁢</mjx-c></mjx-mo><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"3\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D436\">𝐶</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>, вписанной в окружность, равен <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"(2 0 1)\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mrow data-semantic-type=\"punctuated\" data-semantic-role=\"endpunct\" data-semantic-annotation=\"clearspeak:simple;depth:1\" data-semantic-id=\"2\" data-semantic-children=\"0,1\" data-semantic-content=\"1\" data-semantic-owns=\"0 1\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-mn data-semantic-type=\"number\" data-semantic-role=\"integer\" data-semantic-font=\"normal\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:2\" data-semantic-id=\"0\" data-semantic-parent=\"2\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-c35\" noic=\"true\" style=\"padding-top: 0.666em;\">5</mjx-c><mjx-c class=\"mjx-c39\" style=\"padding-top: 0.666em;\">9</mjx-c></mjx-mn><mjx-mi data-semantic-type=\"punctuation\" data-semantic-role=\"degree\" data-semantic-annotation=\"nemeth:number;depth:2\" data-semantic-id=\"1\" data-semantic-parent=\"2\" data-semantic-operator=\"punctuated\" data-semantic-level-number=\"1\" data-speech-node=\"true\"><mjx-c class=\"mjx-cB0 NCM-I\">°</mjx-c></mjx-mi></mjx-mrow></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>. Найдите угол <mjx-container class=\"MathJax\" jax=\"CHTML\" overflow=\"overflow\" style=\"font-size: 101.2%;\"><mjx-math data-semantic-structure=\"0\" class=\"NCM-N\"><mjx-mstyle><mjx-semantics><mjx-mi data-semantic-type=\"identifier\" data-semantic-role=\"latinletter\" data-semantic-font=\"italic\" data-semantic-annotation=\"clearspeak:simple;nemeth:number;depth:1\" data-semantic-id=\"0\" data-semantic-level-number=\"0\" data-speech-node=\"true\"><mjx-c class=\"mjx-c1D435\">𝐵</mjx-c></mjx-mi></mjx-semantics></mjx-mstyle></mjx-math></mjx-container>&nbsp;этой трапеции. Ответ дайте в градусах.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-017-extra-p071",
      "subject": "Математика",
      "number": 17,
      "title": "Планиметрия",
      "block": "",
      "page": 1,
      "item_number": 71,
      "prompt": "Впишите правильный ответ.",
      "question": "Основания трапеции равны 8 и 18, а высота равна 5. Найдите среднюю линию этой трапеции.",
      "answer": "",
      "solution": "",
      "source_guid": "082E7A2C9C84A010484BF45BE3F5FCA2",
      "source_number": "5D3C40",
      "source_answer_type": "Краткий ответ",
      "source_kes": "7.3 Многоугольники\n7.5 Измерение геометрических величин",
      "source_hint": "Впишите правильный ответ.",
      "image": "https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/082E7A2C9C84A010484BF45BE3F5FCA2/xs3qstsrc082E7A2C9C84A010484BF45BE3F5FCA2_1_1485780001.png",
      "image_alt": "Иллюстрация к заданию 71",
      "source_question_html": "<table class=\"MsoTableGrid\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"right\"> <tbody><tr> <td valign=\"top\"> <p class=\"MsoNormal\"><script language=\"javascript\"> ShowPictureQ('docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/082E7A2C9C84A010484BF45BE3F5FCA2/xs3qstsrc082E7A2C9C84A010484BF45BE3F5FCA2_1_1485780001.png');</script><img src=\"https://oge.fipi.ru/docs/DE0E276E497AB3784C3FC4CC20248DC0/questions/082E7A2C9C84A010484BF45BE3F5FCA2/xs3qstsrc082E7A2C9C84A010484BF45BE3F5FCA2_1_1485780001.png\" align=\"ABSMIDDLE\" alt=\"undefined\" border=\"0\"> </p> </td> </tr> </tbody></table> <p class=\"MsoNormal\">Основания трапеции равны 8 и 18, а высота равна 5. Найдите среднюю линию этой трапеции.</p> <p class=\"MsoNormal\"><span>&nbsp;</span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
);

