window.OGE_TASKS = window.OGE_TASKS || [];
window.OGE_TASKS.push({
      "id": "math-oge-010-p015",
      "subject": "Математика",
      "number": 10,
      "title": "Задание 10",
      "block": "",
      "page": 1,
      "item_number": 15,
      "prompt": "Впишите правильный ответ.",
      "question": "В среднем из 80 карманных фонариков, поступивших в продажу,\nдвенадцать неисправных. Найдите вероятность того, что выбранный наудачу\nв магазине фонарик окажется исправен.",
      "answer": "",
      "solution": "",
      "source_guid": "018D731A201D942D4E01607178FF7A8B",
      "source_number": "FD6745",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В среднем из 80 карманных фонариков, поступивших в продажу, <br> двенадцать неисправных. Найдите вероятность того, что выбранный наудачу <br> в магазине фонарик окажется исправен.</p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-010-p037",
      "subject": "Математика",
      "number": 10,
      "title": "Задание 10",
      "block": "",
      "page": 1,
      "item_number": 37,
      "prompt": "Впишите правильный ответ.",
      "question": "В фирме такси в данный момент свободно 10 машин: 5 чёрных, 1 жёлтая\nи 4 зелёных. По вызову выехала одна из машин, случайно оказавшаяся\nближе всего к заказчику. Найдите вероятность того, что к нему приедет жёлтое такси.",
      "answer": "",
      "solution": "",
      "source_guid": "0402D51408708F3B43E396FA18E91926",
      "source_number": "B60144",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В фирме такси в данный момент свободно 10 машин: 5 чёрных, 1 жёлтая <br> и 4 зелёных. По вызову выехала одна из машин, случайно оказавшаяся <br> ближе всего к заказчику. Найдите вероятность того, что к нему приедет жёлтое такси.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-010-p041",
      "subject": "Математика",
      "number": 10,
      "title": "Задание 10",
      "block": "",
      "page": 1,
      "item_number": 41,
      "prompt": "Впишите правильный ответ.",
      "question": "У бабушки 15 чашек: 9 с красными цветами, остальные с синими. Бабушка наливает чай в случайно выбранную чашку. Найдите вероятность того,\nчто это будет чашка с синими цветами.",
      "answer": "",
      "solution": "",
      "source_guid": "049D234A4670A5524FBB350402943409",
      "source_number": "B0674A",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">У бабушки 15 чашек: 9 с красными цветами, остальные с синими. Бабушка наливает чай в случайно выбранную чашку. Найдите вероятность того, <br> что это будет чашка с синими цветами.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p063",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 63,
      "prompt": "Впишите правильный ответ.",
      "question": "В среднем из 150 карманных фонариков, поступивших в продажу, восемнадцать неисправных. Найдите вероятность того, что выбранный наудачу в магазине фонарик окажется исправен.",
      "answer": "",
      "solution": "",
      "source_guid": "06E74286F0F78F8F4F4213B221D24C42",
      "source_number": "2BD043",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В среднем из 150 карманных фонариков, поступивших в продажу, восемнадцать неисправных. Найдите вероятность того, что выбранный наудачу в магазине фонарик окажется исправен.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p087",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 87,
      "prompt": "Впишите правильный ответ.",
      "question": "В лыжных гонках участвуют 7 спортсменов из России, 1 спортсмен\nиз Швеции и 2 спортсмена из Норвегии. Порядок, в котором спортсмены стартуют, определяется жребием. Найдите вероятность того, что первым будет стартовать спортсмен из Швеции.",
      "answer": "",
      "solution": "",
      "source_guid": "09D51C5305F4B8584D8A63A042F28062",
      "source_number": "AF1E46",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В лыжных гонках участвуют 7 спортсменов из России, 1 спортсмен <br> из Швеции и 2 спортсмена из Норвегии. Порядок, в котором спортсмены стартуют, определяется жребием. Найдите вероятность того, что первым будет стартовать спортсмен из Швеции.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p097",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 97,
      "prompt": "Впишите правильный ответ.",
      "question": "Вероятность того, что новая шариковая ручка пишет плохо (или не пишет), равна 0,02. Покупатель в магазине выбирает одну шариковую ручку. Найдите вероятность того, что эта ручка пишет хорошо.",
      "answer": "",
      "solution": "",
      "source_guid": "0AA92CC6C08892B245A20A40F047DE6B",
      "source_number": "C0AE4C",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">Вероятность того, что новая шариковая ручка пишет плохо (или не пишет), равна 0,02. Покупатель в магазине выбирает одну шариковую ручку. Найдите вероятность того, что эта ручка пишет хорошо.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p098",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 1,
      "item_number": 98,
      "prompt": "Впишите правильный ответ.",
      "question": "На экзамене 20 билетов, Оскар не выучил 7 из них. Найдите вероятность того, что ему попадётся выученный билет.",
      "answer": "",
      "solution": "",
      "source_guid": "0AC3DA172189A20745824AEA5CBF16E3",
      "source_number": "C67C4E",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">На экзамене 20 билетов, Оскар <b>не выучил</b> 7 из них. Найдите вероятность того, что ему попадётся выученный билет.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    },
    {
      "id": "math-oge-007-p113",
      "subject": "Математика",
      "number": 7,
      "title": "Задание 7",
      "block": "",
      "page": 2,
      "item_number": 113,
      "prompt": "Впишите правильный ответ.",
      "question": "В фирме такси в данный момент свободно 20 машин: 2 чёрных, 2 жёлтых\nи 16 зелёных. По вызову выехала одна из машин, случайно оказавшаяся ближе всего к заказчику. Найдите вероятность того, что к нему приедет жёлтое такси.",
      "answer": "",
      "solution": "",
      "source_guid": "158A5091538DBECA48E6C07205D9411B",
      "source_number": "11C4F5",
      "source_answer_type": "Краткий ответ",
      "source_kes": "8.2 Вероятность",
      "source_hint": "Впишите правильный ответ.",
      "source_question_html": "<p class=\"MsoNormal\">В фирме такси в данный момент свободно 20 машин: 2 чёрных, 2 жёлтых <br> и 16 зелёных. По вызову выехала одна из машин, случайно оказавшаяся ближе всего к заказчику. Найдите вероятность того, что к нему приедет жёлтое такси.<span></span></p>",
      "source_variants_html": "<table width=\"100%\" cellspacing=\"0\" cellpadding=\"1\"><tbody><tr><td width=\"100%\"><input type=\"text\" name=\"answer\" size=\"40\" value=\"\" maxlength=\"250\"></td></tr></tbody></table>"
    }
);
