window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push(
{
  "subject": "Математика",
  "grade": 6,
  "number": 1,
  "title": "Вычисление выражений",
  "topic": "Умножение числа на сумму и разность",
  "block": "МЦКО 6 класс",
  "total_tasks": 20,
  "items": [
    {
      "id": "math-mcko-06-001-p001",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Вычислите",
      "question_raw": "-6 · (28 + 15)",
      "expression": "-6\\cdot(28+15)",
      "answer": "-258",
      "solution": "28 + 15 = 43. Затем -6 · 43 = -258."
    },
    {
      "id": "math-mcko-06-001-p002",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 2,
      "prompt": "Вычислите",
      "question_raw": "-8 · (94 - 36)",
      "expression": "-8\\cdot(94-36)",
      "answer": "-464",
      "solution": "94 - 36 = 58. Затем -8 · 58 = -464."
    },
    {
      "id": "math-mcko-06-001-p003",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 3,
      "prompt": "Вычислите",
      "question_raw": "-7 · (18 + 22)",
      "expression": "-7\\cdot(18+22)",
      "answer": "-280",
      "solution": "18 + 22 = 40. Затем -7 · 40 = -280."
    },
    {
      "id": "math-mcko-06-001-p004",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 4,
      "prompt": "Вычислите",
      "question_raw": "-9 · (75 - 27)",
      "expression": "-9\\cdot(75-27)",
      "answer": "-432",
      "solution": "75 - 27 = 48. Затем -9 · 48 = -432."
    },
    {
      "id": "math-mcko-06-001-p005",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 5,
      "prompt": "Вычислите",
      "question_raw": "-12 · (16 + 14)",
      "expression": "-12\\cdot(16+14)",
      "answer": "-360",
      "solution": "16 + 14 = 30. Затем -12 · 30 = -360."
    },
    {
      "id": "math-mcko-06-001-p006",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 6,
      "prompt": "Вычислите",
      "question_raw": "-5 · (81 - 29)",
      "expression": "-5\\cdot(81-29)",
      "answer": "-260",
      "solution": "81 - 29 = 52. Затем -5 · 52 = -260."
    },
    {
      "id": "math-mcko-06-001-p007",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 7,
      "prompt": "Вычислите",
      "question_raw": "-14 · (11 + 19)",
      "expression": "-14\\cdot(11+19)",
      "answer": "-420",
      "solution": "11 + 19 = 30. Затем -14 · 30 = -420."
    },
    {
      "id": "math-mcko-06-001-p008",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 8,
      "prompt": "Вычислите",
      "question_raw": "-10 · (63 - 18)",
      "expression": "-10\\cdot(63-18)",
      "answer": "-450",
      "solution": "63 - 18 = 45. Затем -10 · 45 = -450."
    },
    {
      "id": "math-mcko-06-001-p009",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 9,
      "prompt": "Вычислите",
      "question_raw": "-13 · (25 + 35)",
      "expression": "-13\\cdot(25+35)",
      "answer": "-780",
      "solution": "25 + 35 = 60. Затем -13 · 60 = -780."
    },
    {
      "id": "math-mcko-06-001-p010",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 10,
      "prompt": "Вычислите",
      "question_raw": "-4 · (98 - 23)",
      "expression": "-4\\cdot(98-23)",
      "answer": "-300",
      "solution": "98 - 23 = 75. Затем -4 · 75 = -300."
    },
    {
      "id": "math-mcko-06-001-p011",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 11,
      "prompt": "Вычислите",
      "question_raw": "-15 · (17 + 13)",
      "expression": "-15\\cdot(17+13)",
      "answer": "-450",
      "solution": "17 + 13 = 30. Затем -15 · 30 = -450."
    },
    {
      "id": "math-mcko-06-001-p012",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 12,
      "prompt": "Вычислите",
      "question_raw": "-11 · (84 - 44)",
      "expression": "-11\\cdot(84-44)",
      "answer": "-440",
      "solution": "84 - 44 = 40. Затем -11 · 40 = -440."
    },
    {
      "id": "math-mcko-06-001-p013",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 13,
      "prompt": "Вычислите",
      "question_raw": "-3 · (56 + 24)",
      "expression": "-3\\cdot(56+24)",
      "answer": "-240",
      "solution": "56 + 24 = 80. Затем -3 · 80 = -240."
    },
    {
      "id": "math-mcko-06-001-p014",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 14,
      "prompt": "Вычислите",
      "question_raw": "-16 · (52 - 27)",
      "expression": "-16\\cdot(52-27)",
      "answer": "-400",
      "solution": "52 - 27 = 25. Затем -16 · 25 = -400."
    },
    {
      "id": "math-mcko-06-001-p015",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 15,
      "prompt": "Вычислите",
      "question_raw": "-18 · (12 + 18)",
      "expression": "-18\\cdot(12+18)",
      "answer": "-540",
      "solution": "12 + 18 = 30. Затем -18 · 30 = -540."
    },
    {
      "id": "math-mcko-06-001-p016",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 16,
      "prompt": "Вычислите",
      "question_raw": "-7 · (91 - 35)",
      "expression": "-7\\cdot(91-35)",
      "answer": "-392",
      "solution": "91 - 35 = 56. Затем -7 · 56 = -392."
    },
    {
      "id": "math-mcko-06-001-p017",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 17,
      "prompt": "Вычислите",
      "question_raw": "-20 · (9 + 11)",
      "expression": "-20\\cdot(9+11)",
      "answer": "-400",
      "solution": "9 + 11 = 20. Затем -20 · 20 = -400."
    },
    {
      "id": "math-mcko-06-001-p018",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 18,
      "prompt": "Вычислите",
      "question_raw": "-6 · (72 - 14)",
      "expression": "-6\\cdot(72-14)",
      "answer": "-348",
      "solution": "72 - 14 = 58. Затем -6 · 58 = -348."
    },
    {
      "id": "math-mcko-06-001-p019",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Вычисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 19,
      "prompt": "Вычислите",
      "question_raw": "-9 · (31 + 29)",
      "expression": "-9\\cdot(31+29)",
      "answer": "-540",
      "solution": "31 + 29 = 60. Затем -9 · 60 = -540."
    },
    {
      "id": "math-mcko-06-001-p020",
      "subject": "Математика",
      "grade": 6,
      "number": 1,
      "title": "Выччисление выражений",
      "topic": "Умножение числа на сумму и разность",
      "task_group": 1,
      "item_number": 20,
      "prompt": "Вычислите",
      "question_raw": "-8 · (67 - 42)",
      "expression": "-8\\cdot(67-42)",
      "answer": "-200",
      "solution": "67 - 42 = 25. Затем -8 · 25 = -200."
    }
  ]
}
);

