window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push(
{
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "block": "МЦКО 6 класс",
  "total_tasks": 20,
  "items": [
{
  "id": "math-mcko-06-002-p001",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 1,
  "prompt": "Вычислите",
  "question_raw": "(7/8 - 1/4) · 4/5",
  "expression": "\\left(\\frac{7}{8}-\\frac{1}{4}\\right)\\cdot\\frac{4}{5}",
  "answer": "\\frac{1}{2}",
  "solution": "7/8 - 1/4 = 5/8. Затем 5/8 · 4/5 = 1/2."
},
{
  "id": "math-mcko-06-002-p002",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 2,
  "prompt": "Вычислите",
  "question_raw": "(5/6 + 1/3) · 3/7",
  "expression": "\\left(\\frac{5}{6}+\\frac{1}{3}\\right)\\cdot\\frac{3}{7}",
  "answer": "\\frac{1}{2}",
  "solution": "5/6 + 1/3 = 7/6. Затем 7/6 · 3/7 = 1/2."
},
{
  "id": "math-mcko-06-002-p003",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 3,
  "prompt": "Вычислите",
  "question_raw": "(9/10 - 2/5) · 5/6",
  "expression": "\\left(\\frac{9}{10}-\\frac{2}{5}\\right)\\cdot\\frac{5}{6}",
  "answer": "\\frac{5}{12}",
  "solution": "9/10 - 2/5 = 1/2. Затем 1/2 · 5/6 = 5/12."
},
{
  "id": "math-mcko-06-002-p004",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 4,
  "prompt": "Вычислите",
  "question_raw": "(11/12 - 1/6) · 3/5",
  "expression": "\\left(\\frac{11}{12}-\\frac{1}{6}\\right)\\cdot\\frac{3}{5}",
  "answer": "\\frac{9}{20}",
  "solution": "11/12 - 1/6 = 3/4. Затем 3/4 · 3/5 = 9/20."
},
{
  "id": "math-mcko-06-002-p005",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 5,
  "prompt": "Вычислите",
  "question_raw": "(3/4 + 1/2) · 2/5",
  "expression": "\\left(\\frac{3}{4}+\\frac{1}{2}\\right)\\cdot\\frac{2}{5}",
  "answer": "\\frac{1}{2}",
  "solution": "3/4 + 1/2 = 5/4. Затем 5/4 · 2/5 = 1/2."
},
{
  "id": "math-mcko-06-002-p006",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 6,
  "prompt": "Вычислите",
  "question_raw": "(7/9 - 2/9) · 9/10",
  "expression": "\\left(\\frac{7}{9}-\\frac{2}{9}\\right)\\cdot\\frac{9}{10}",
  "answer": "\\frac{1}{2}",
  "solution": "7/9 - 2/9 = 5/9. Затем 5/9 · 9/10 = 1/2."
},
{
  "id": "math-mcko-06-002-p007",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 7,
  "prompt": "Вычислите",
  "question_raw": "(5/8 + 3/8) · 4/7",
  "expression": "\\left(\\frac{5}{8}+\\frac{3}{8}\\right)\\cdot\\frac{4}{7}",
  "answer": "\\frac{4}{7}",
  "solution": "5/8 + 3/8 = 1. Затем 1 · 4/7 = 4/7."
},
{
  "id": "math-mcko-06-002-p008",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 8,
  "prompt": "Вычислите",
  "question_raw": "(13/15 - 1/3) · 5/8",
  "expression": "\\left(\\frac{13}{15}-\\frac{1}{3}\\right)\\cdot\\frac{5}{8}",
  "answer": "\\frac{1}{3}",
  "solution": "13/15 - 1/3 = 8/15. Затем 8/15 · 5/8 = 1/3."
},
{
  "id": "math-mcko-06-002-p009",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 9,
  "prompt": "Вычислите",
  "question_raw": "(7/12 + 1/6) · 4/5",
  "expression": "\\left(\\frac{7}{12}+\\frac{1}{6}\\right)\\cdot\\frac{4}{5}",
  "answer": "\\frac{3}{5}",
  "solution": "7/12 + 1/6 = 3/4. Затем 3/4 · 4/5 = 3/5."
},
{
  "id": "math-mcko-06-002-p010",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 10,
  "prompt": "Вычислите",
  "question_raw": "(4/5 - 1/10) · 2/7",
  "expression": "\\left(\\frac{4}{5}-\\frac{1}{10}\\right)\\cdot\\frac{2}{7}",
  "answer": "\\frac{1}{5}",
  "solution": "4/5 - 1/10 = 7/10. Затем 7/10 · 2/7 = 1/5."
},
{
  "id": "math-mcko-06-002-p011",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 11,
  "prompt": "Вычислите",
  "question_raw": "(5/6 + 1/6) · 3/4",
  "expression": "\\left(\\frac{5}{6}+\\frac{1}{6}\\right)\\cdot\\frac{3}{4}",
  "answer": "\\frac{3}{4}",
  "solution": "5/6 + 1/6 = 1. Затем 1 · 3/4 = 3/4."
},
{
  "id": "math-mcko-06-002-p012",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 12,
  "prompt": "Вычислите",
  "question_raw": "(7/10 - 1/5) · 5/6",
  "expression": "\\left(\\frac{7}{10}-\\frac{1}{5}\\right)\\cdot\\frac{5}{6}",
  "answer": "\\frac{5}{12}",
  "solution": "7/10 - 1/5 = 1/2. Затем 1/2 · 5/6 = 5/12."
},
{
  "id": "math-mcko-06-002-p013",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 13,
  "prompt": "Вычислите",
  "question_raw": "(11/14 - 2/7) · 7/10",
  "expression": "\\left(\\frac{11}{14}-\\frac{2}{7}\\right)\\cdot\\frac{7}{10}",
  "answer": "\\frac{7}{20}",
  "solution": "11/14 - 2/7 = 1/2. Затем 1/2 · 7/10 = 7/20."
},
{
  "id": "math-mcko-06-002-p014",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 14,
  "prompt": "Вычислите",
  "question_raw": "(2/3 + 1/6) · 4/9",
  "expression": "\\left(\\frac{2}{3}+\\frac{1}{6}\\right)\\cdot\\frac{4}{9}",
  "answer": "\\frac{10}{27}",
  "solution": "2/3 + 1/6 = 5/6. Затем 5/6 · 4/9 = 10/27."
},
{
  "id": "math-mcko-06-002-p015",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 15,
  "prompt": "Вычислите",
  "question_raw": "(5/12 + 1/4) · 3/4",
  "expression": "\\left(\\frac{5}{12}+\\frac{1}{4}\\right)\\cdot\\frac{3}{4}",
  "answer": "\\frac{1}{2}",
  "solution": "5/12 + 1/4 = 2/3. Затем 2/3 · 3/4 = 1/2."
},
{
  "id": "math-mcko-06-002-p016",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 16,
  "prompt": "Вычислите",
  "question_raw": "(9/10 - 3/10) · 5/9",
  "expression": "\\left(\\frac{9}{10}-\\frac{3}{10}\\right)\\cdot\\frac{5}{9}",
  "answer": "\\frac{1}{3}",
  "solution": "9/10 - 3/10 = 3/5. Затем 3/5 · 5/9 = 1/3."
},
{
  "id": "math-mcko-06-002-p017",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 17,
  "prompt": "Вычислите",
  "question_raw": "(7/8 + 1/8) · 2/3",
  "expression": "\\left(\\frac{7}{8}+\\frac{1}{8}\\right)\\cdot\\frac{2}{3}",
  "answer": "\\frac{2}{3}",
  "solution": "7/8 + 1/8 = 1. Затем 1 · 2/3 = 2/3."
},
{
  "id": "math-mcko-06-002-p018",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 18,
  "prompt": "Вычислите",
  "question_raw": "(4/9 + 2/9) · 3/8",
  "expression": "\\left(\\frac{4}{9}+\\frac{2}{9}\\right)\\cdot\\frac{3}{8}",
  "answer": "\\frac{1}{4}",
  "solution": "4/9 + 2/9 = 2/3. Затем 2/3 · 3/8 = 1/4."
},
{
  "id": "math-mcko-06-002-p019",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 19,
  "prompt": "Вычислите",
  "question_raw": "(5/6 - 1/3) · 6/7",
  "expression": "\\left(\\frac{5}{6}-\\frac{1}{3}\\right)\\cdot\\frac{6}{7}",
  "answer": "\\frac{3}{7}",
  "solution": "5/6 - 1/3 = 1/2. Затем 1/2 · 6/7 = 3/7."
},
{
  "id": "math-mcko-06-002-p020",
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Действия с дробями",
  "topic": "Вычисление выражений с обыкновенными дробями",
  "task_group": 1,
  "item_number": 20,
  "prompt": "Вычислите",
  "question_raw": "(3/5 + 2/5) · 5/8",
  "expression": "\\left(\\frac{3}{5}+\\frac{2}{5}\\right)\\cdot\\frac{5}{8}",
  "answer": "\\frac{5}{8}",
  "solution": "3/5 + 2/5 = 1. Затем 1 · 5/8 = 5/8."
}
  ]
},
{
  "subject": "Математика",
  "grade": 6,
  "number": 2,
  "title": "Вычисление выражений",
  "topic": "Действия с десятичными дробями",
  "block": "МЦКО 6 класс",
  "total_tasks": 10,
  "items": [
    {
      "id": "math-mcko-06-002-dec-p001",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 1,
      "prompt": "Вычислите",
      "question_raw": "8,4 - 6,72 : 2,4",
      "expression": "8{,}4 - 6{,}72 : 2{,}4",
      "answer": "5,6",
      "solution": "6,72 : 2,4 = 2,8. Затем 8,4 - 2,8 = 5,6."
    },
    {
      "id": "math-mcko-06-002-dec-p002",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 2,
      "prompt": "Вычислите",
      "question_raw": "-2,5 + 7,2 : 1,8",
      "expression": "-2{,}5 + 7{,}2 : 1{,}8",
      "answer": "1,5",
      "solution": "7,2 : 1,8 = 4. Затем -2,5 + 4 = 1,5."
    },
    {
      "id": "math-mcko-06-002-dec-p003",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 3,
      "prompt": "Вычислите",
      "question_raw": "12,6 : 4,2 - 1,5",
      "expression": "12{,}6 : 4{,}2 - 1{,}5",
      "answer": "1,5",
      "solution": "12,6 : 4,2 = 3. Затем 3 - 1,5 = 1,5."
    },
    {
      "id": "math-mcko-06-002-dec-p004",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 4,
      "prompt": "Вычислите",
      "question_raw": "(2,8 - 0,6) : 0,2",
      "expression": "(2{,}8 - 0{,}6) : 0{,}2",
      "answer": "11",
      "solution": "2,8 - 0,6 = 2,2. Затем 2,2 : 0,2 = 11."
    },
    {
      "id": "math-mcko-06-002-dec-p005",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 5,
      "prompt": "Вычислите",
      "question_raw": "(3,4 - 1,8) : 0,4",
      "expression": "(3{,}4 - 1{,}8) : 0{,}4",
      "answer": "4",
      "solution": "3,4 - 1,8 = 1,6. Затем 1,6 : 0,4 = 4."
    },
    {
      "id": "math-mcko-06-002-dec-p006",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 6,
      "prompt": "Вычислите",
      "question_raw": "(-4,5 + 8,5) · 0,5",
      "expression": "(-4{,}5 + 8{,}5)\\cdot 0{,}5",
      "answer": "2",
      "solution": "-4,5 + 8,5 = 4. Затем 4 · 0,5 = 2."
    },
    {
      "id": "math-mcko-06-002-dec-p007",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 7,
      "prompt": "Вычислите",
      "question_raw": "(-6,8 + 7,6) · 0,5",
      "expression": "(-6{,}8 + 7{,}6)\\cdot 0{,}5",
      "answer": "0,4",
      "solution": "-6,8 + 7,6 = 0,8. Затем 0,8 · 0,5 = 0,4."
    },
    {
      "id": "math-mcko-06-002-dec-p008",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 8,
      "prompt": "Вычислите",
      "question_raw": "9,9 - 8,1 : 2,7",
      "expression": "9{,}9 - 8{,}1 : 2{,}7",
      "answer": "6,9",
      "solution": "8,1 : 2,7 = 3. Затем 9,9 - 3 = 6,9."
    },
    {
      "id": "math-mcko-06-002-dec-p009",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 9,
      "prompt": "Вычислите",
      "question_raw": "-3,2 + 9,6 : 3,2",
      "expression": "-3{,}2 + 9{,}6 : 3{,}2",
      "answer": "-0,2",
      "solution": "9,6 : 3,2 = 3. Затем -3,2 + 3 = -0,2."
    },
    {
      "id": "math-mcko-06-002-dec-p010",
      "subject": "Математика",
      "grade": 6,
      "number": 2,
      "title": "Вычисление выражений",
      "topic": "Действия с десятичными дробями",
      "task_group": 2,
      "item_number": 10,
      "prompt": "Вычислите",
      "question_raw": "7,35 : 2,1 - 2",
      "expression": "7{,}35 : 2{,}1 - 2",
      "answer": "1,5",
      "solution": "7,35 : 2,1 = 3,5. Затем 3,5 - 2 = 1,5."
    }
  ]
}
);
