window.MCKO_TASKS = window.MCKO_TASKS || [];
window.MCKO_TASKS.push({
  "subject": "Математика",
  "grade": 6,
  "number": 6,
  "title": "Сложные выражения с дробями",
  "topic": "Смешанные числа и обыкновенные дроби",
  "block": "МЦКО 6 класс",
  "total_tasks": 25,
  "items": [
    {
      "id": "math-mcko-06-006-p001",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 1,
      "prompt": "Вычислите",
      "expression": "2\\frac{1}{2}:\\left(\\frac{5}{6}-\\frac{1}{3}\\right)+2\\cdot1\\frac{1}{5}",
      "answer": "12",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p002",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 2,
      "prompt": "Вычислите",
      "expression": "1\\frac{3}{4}:\\left(\\frac{7}{8}-\\frac{3}{8}\\right)+3\\cdot1\\frac{1}{2}",
      "answer": "8\\frac{7}{8}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p003",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 3,
      "prompt": "Вычислите",
      "expression": "2\\frac{2}{3}:\\left(\\frac{11}{12}-\\frac{1}{4}\\right)-2\\cdot\\frac{3}{4}",
      "answer": "2\\frac{1}{2}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p004",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 4,
      "prompt": "Вычислите",
      "expression": "3\\frac{1}{5}:\\left(\\frac{9}{10}-\\frac{2}{5}\\right)+2\\cdot1\\frac{2}{5}",
      "answer": "8",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p005",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 5,
      "prompt": "Вычислите",
      "expression": "1\\frac{4}{5}:\\left(\\frac{5}{6}-\\frac{7}{18}\\right)+4\\cdot\\frac{1}{2}",
      "answer": "6\\frac{1}{2}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p006",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 6,
      "prompt": "Вычислите",
      "expression": "2\\frac{1}{4}:\\left(\\frac{7}{9}-\\frac{2}{9}\\right)+3\\cdot1\\frac{1}{3}",
      "answer": "8\\frac{23}{60}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p007",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 7,
      "prompt": "Вычислите",
      "expression": "3\\frac{3}{4}:\\left(\\frac{5}{8}-\\frac{1}{4}\\right)-2\\cdot1\\frac{1}{2}",
      "answer": "12",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p008",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 8,
      "prompt": "Вычислите",
      "expression": "2\\frac{2}{5}:\\left(\\frac{13}{15}-\\frac{1}{3}\\right)+2\\cdot2\\frac{1}{5}",
      "answer": "8\\frac{2}{5}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p009",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 9,
      "prompt": "Вычислите",
      "expression": "1\\frac{5}{6}:\\left(\\frac{3}{4}-\\frac{1}{6}\\right)+3\\cdot\\frac{2}{3}",
      "answer": "5\\frac{3}{10}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p010",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 10,
      "prompt": "Вычислите",
      "expression": "2\\frac{3}{5}:\\left(\\frac{7}{10}-\\frac{1}{5}\\right)+2\\cdot1\\frac{4}{5}",
      "answer": "8",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p011",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 11,
      "prompt": "Вычислите",
      "expression": "3\\frac{1}{3}:\\left(\\frac{5}{6}-\\frac{1}{2}\\right)+2\\cdot\\frac{5}{6}",
      "answer": "11\\frac{2}{3}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p012",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 12,
      "prompt": "Вычислите",
      "expression": "2\\frac{4}{5}:\\left(\\frac{11}{15}-\\frac{1}{5}\\right)-3\\cdot\\frac{2}{5}",
      "answer": "3\\frac{1}{4}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p013",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 13,
      "prompt": "Вычислите",
      "expression": "1\\frac{2}{3}:\\left(\\frac{4}{5}-\\frac{2}{5}\\right)+2\\cdot1\\frac{1}{6}",
      "answer": "6\\frac{1}{2}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p014",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 14,
      "prompt": "Вычислите",
      "expression": "2\\frac{5}{6}:\\left(\\frac{7}{12}-\\frac{1}{4}\\right)+2\\cdot\\frac{3}{4}",
      "answer": "10",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p015",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 15,
      "prompt": "Вычислите",
      "expression": "3\\frac{1}{2}:\\left(\\frac{8}{9}-\\frac{5}{9}\\right)+3\\cdot\\frac{1}{2}",
      "answer": "12",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p016",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 16,
      "prompt": "Вычислите",
      "expression": "2\\frac{1}{5}:\\left(\\frac{9}{10}-\\frac{2}{5}\\right)+4\\cdot\\frac{1}{2}",
      "answer": "6\\frac{2}{5}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p017",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 17,
      "prompt": "Вычислите",
      "expression": "1\\frac{3}{5}:\\left(\\frac{5}{8}-\\frac{1}{8}\\right)+2\\cdot2\\frac{1}{4}",
      "answer": "7\\frac{7}{10}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p018",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 18,
      "prompt": "Вычислите",
      "expression": "2\\frac{3}{4}:\\left(\\frac{7}{8}-\\frac{3}{8}\\right)-2\\cdot\\frac{5}{4}",
      "answer": "4",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p019",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 19,
      "prompt": "Вычислите",
      "expression": "3\\frac{2}{5}:\\left(\\frac{11}{15}-\\frac{2}{5}\\right)+2\\cdot1\\frac{3}{5}",
      "answer": "8\\frac{1}{10}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p020",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 20,
      "prompt": "Вычислите",
      "expression": "1\\frac{4}{5}:\\left(\\frac{13}{18}-\\frac{2}{9}\\right)+3\\cdot\\frac{5}{6}",
      "answer": "6\\frac{1}{2}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p021",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 21,
      "prompt": "Вычислите",
      "expression": "2\\frac{2}{3}:\\left(\\frac{3}{4}-\\frac{1}{4}\\right)+2\\cdot1\\frac{2}{3}",
      "answer": "8\\frac{2}{3}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p022",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 22,
      "prompt": "Вычислите",
      "expression": "3\\frac{3}{5}:\\left(\\frac{5}{6}-\\frac{1}{3}\\right)-2\\cdot\\frac{4}{5}",
      "answer": "5\\frac{3}{5}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p023",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 23,
      "prompt": "Вычислите",
      "expression": "2\\frac{1}{4}:\\left(\\frac{7}{10}-\\frac{1}{5}\\right)+3\\cdot1\\frac{1}{4}",
      "answer": "7\\frac{1}{2}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p024",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 24,
      "prompt": "Вычислите",
      "expression": "1\\frac{5}{6}:\\left(\\frac{5}{9}-\\frac{2}{9}\\right)+2\\cdot1\\frac{2}{3}",
      "answer": "7\\frac{5}{6}",
      "solution": ""
    },
    {
      "id": "math-mcko-06-006-p025",
      "subject": "Математика",
      "grade": 6,
      "number": 6,
      "title": "Сложные выражения с дробями",
      "topic": "Смешанные числа и обыкновенные дроби",
      "task_group": 1,
      "item_number": 25,
      "prompt": "Вычислите",
      "expression": "2\\frac{4}{5}:\\left(\\frac{11}{12}-\\frac{5}{12}\\right)+2\\cdot2\\frac{1}{2}",
      "answer": "9\\frac{2}{5}",
      "solution": ""
    }
  ]
});
